In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

import sqlite3 as sq

In [2]:
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)

### Loading data

#### Reading SQLite database - you will need to amend your path

In [17]:
# creating file path
dbfile = 'C:/Users/emitc/OneDrive/Documents/STA/Dresscode/sta-it402-dresscode/code/data/sqa-data-db.sqlite'

# Create a SQL connection to our SQLite database
conn = sq.connect(dbfile)

In [18]:
# creating cursor
cur = conn.cursor()

# reading all table names
table_list = [a for a in cur.execute("SELECT name FROM sqlite_master WHERE type = 'table'")]
# here is your table list
print(table_list)

[('school_rolls',), ('sqa_qualification_list',), ('sqa_data',), ('subject_groups',)]

In [5]:
df1 = pd.read_sql_query('SELECT * FROM school_rolls', conn)
df1.head()

,year,secondary_schools,secondary_pupils,base_year_census,index_factor,predicted
0,1966.0,NaN,283592.0,316594.0,0.895759,0
1,1967.0,665.0,288054.0,316594.0,0.909853,0
2,1968.0,640.0,295625.0,316594.0,0.933767,0
3,1969.0,616.0,307185.0,316594.0,0.970281,0
4,1970.0,441.0,317027.0,316594.0,1.001368,0

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   year               56 non-null     float64
 1   secondary_schools  54 non-null     float64
 2   secondary_pupils   56 non-null     float64
 3   base_year_census   56 non-null     float64
 4   index_factor       56 non-null     float64
 5   predicted          56 non-null     int64
dtypes: float64(5), int64(1)
memory usage: 2.8 KB

In [7]:
df2 = pd.read_sql_query('SELECT * FROM sqa_qualification_list', conn)
df2.head()

,QualificationId,QualificationTitle,SCQFLevel,SecondaryYear,AdditionalYears,DataStartYear,DataEndYear
0,Higher,Higher,6,5.0,6,1986,None
1,AdvancedHigher,Advanced Higher,7,6.0,None,2001,None
2,OrdinaryGrade,Ordinary Grade,5,4.0,5;6,1986,1994
3,NewHigher,New Higher,6,5.0,6,2000;2015,2002;2015
4,StandardGrade,Standard Grade,5,4.0,5;6,1986,2013

In [8]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   QualificationId     19 non-null     object
 1   QualificationTitle  19 non-null     object
 2   SCQFLevel           17 non-null     object
 3   SecondaryYear       12 non-null     float64
 4   AdditionalYears     6 non-null      object
 5   DataStartYear       14 non-null     object
 6   DataEndYear         6 non-null      object
dtypes: float64(1), object(6)
memory usage: 1.2+ KB

In [9]:
df3 = pd.read_sql_query('SELECT * FROM sqa_data', conn)
df3.head()

,qualification,year,Subject,NumberOfCentres,gender,grade,NoOfStudents
0,CSYS,1986,Art and Design (Enquiry),127.0,male,Entries,86.0
1,CSYS,1986,Art and Design (Enquiry),127.0,male,percentage,0.0
2,CSYS,1986,Art and Design (Enquiry),127.0,male,A,7.0
3,CSYS,1986,Art and Design (Enquiry),127.0,male,B,13.0
4,CSYS,1986,Art and Design (Enquiry),127.0,male,C,25.0

In [10]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159668 entries, 0 to 159667
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   qualification    159668 non-null  object
 1   year             159668 non-null  object
 2   Subject          159668 non-null  object
 3   NumberOfCentres  118152 non-null  float64
 4   gender           159668 non-null  object
 5   grade            159668 non-null  object
 6   NoOfStudents     133842 non-null  float64
dtypes: float64(2), object(5)
memory usage: 8.5+ MB

In [11]:
df4 = pd.read_sql_query('SELECT * FROM subject_groups', conn)
df4.head()

,Subject,SubjectGroup,CommonSubjectLabel,qualification,year,SubjectTaken,SCQFLevel
0,English,English,English,National3,2014,Yes,3
1,English,English,English,National3,2015,Yes,3
2,English,English,English,National3,2016,Yes,3
3,English,English,English,National3,2017,Yes,3
4,English,English,English,National3,2018,Yes,3

In [12]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6176 entries, 0 to 6175
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Subject             6176 non-null   object
 1   SubjectGroup        6176 non-null   object
 2   CommonSubjectLabel  2582 non-null   object
 3   qualification       6176 non-null   object
 4   year                6176 non-null   int64
 5   SubjectTaken        6176 non-null   object
 6   SCQFLevel           6176 non-null   int64
dtypes: int64(2), object(5)
memory usage: 337.9+ KB

#### Finished reading SQLite database

##### How many different grades are there?

In [10]:
df3['grade'].unique()

array(['Entries', 'percentage', 'A', 'B', 'C', 'D', 'E', 'Passes', '1',
       '2', '3', '4', '5', '6', '7', 'Comp', 'COMP',
       'PassesesInUngradedCourses', 'PassesUngraded',
       'PassesUngradedCourses', 'A-C', 'Pass', 'Attainment', 'SCQF3',
       'SCQF4', 'SCQF5', 'SCQF6', 'SCQF2', 'NoAward', 'A-B', 'A-D*',
       'A-D'], dtype=object)

In [11]:
df3['grade'].nunique()

32

#### Create and read in grade types table

In [14]:
df_grade_groups = pd.read_csv("grade_groups.csv")

In [15]:
df_grade_groups.head()

  grade grade_type
0     1  numerical
1     2  numerical
2     3  numerical
3     4  numerical
4     5  numerical

In [16]:
df_grade_groups.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   grade       32 non-null     object
 1   grade_type  32 non-null     object
dtypes: object(2)
memory usage: 640.0+ bytes

In [21]:
#conn = sqlite3.connect('cartoon_characters.db')
df_grade_groups.to_sql("grade_groups", conn, if_exists="replace") #need double quotes

In [22]:
# reading all table names
table_list = [a for a in cur.execute("SELECT name FROM sqlite_master WHERE type = 'table'")]
# here is your table list
print(table_list)

[('school_rolls',), ('sqa_qualification_list',), ('sqa_data',), ('subject_groups',), ('grade_groups',)]

In [23]:
# Be sure to close the connection
conn.close()

#### Join grade groups dataframe to grades dataframe

In [27]:
#df5 = df3.join(df_grade_groups, on=)
df5 = pd.merge(df3, df_grade_groups, on='grade')

In [28]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 159668 entries, 0 to 159667
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   qualification    159668 non-null  object
 1   year             159668 non-null  object
 2   Subject          159668 non-null  object
 3   NumberOfCentres  118152 non-null  float64
 4   gender           159668 non-null  object
 5   grade            159668 non-null  object
 6   NoOfStudents     133842 non-null  float64
 7   grade_type       159668 non-null  object
dtypes: float64(2), object(6)
memory usage: 11.0+ MB

In [31]:
#check that it has worked
df5.loc[(df5['grade_type'] == 'scqf')]

,qualification,year,Subject,NumberOfCentres,gender,grade,NoOfStudents,grade_type
143741,NationalCertificate,2014,Accounting,NaN,male,SCQF3,NaN,scqf
143742,NationalCertificate,2014,Accounting,NaN,female,SCQF3,NaN,scqf
143743,NationalCertificate,2014,Accounting,NaN,all,SCQF3,NaN,scqf
143744,NationalCertificate,2014,Acting and Theatre Performance,NaN,male,SCQF3,NaN,scqf
143745,NationalCertificate,2014,Acting and Theatre Performance,NaN,female,SCQF3,NaN,scqf
...,...,...,...,...,...,...,...,...
157164,NationalProgressionAward,2021,Web Design Fundamentals,NaN,male,SCQF2,NaN,scqf
157165,NationalProgressionAward,2021,Web Design Fundamentals,NaN,female,SCQF2,NaN,scqf
157166,NationalProgressionAward,2021,Zoo Animal Behaviour and Welfare,NaN,all,SCQF2,NaN,scqf
157167,NationalProgressionAward,2021,Zoo Animal Behaviour and Welfare,NaN,male,SCQF2,NaN,scqf
157168,NationalProgressionAward,2021,Zoo Animal Behaviour and Welfare,NaN,female,SCQF2,NaN,scqf

In [43]:
dummy = df5.loc[(df5['qualification'] == 'National5') & (df5['Subject'] == 'Urdu') & (df5['year'] == '2020')]

#### Sort the merged dataframe

In [47]:
df5 = df5.sort_values(by = ['qualification', 'year', 'Subject', 'gender', 'grade'])
df5.tail(40)

,qualification,year,Subject,NumberOfCentres,gender,grade,NoOfStudents,grade_type
126346,StandardGrade,2013,Technological Studies,79.0,female,5,6.0,numerical
129229,StandardGrade,2013,Technological Studies,79.0,female,6,2.0,numerical
132112,StandardGrade,2013,Technological Studies,79.0,female,7,0.0,numerical
17353,StandardGrade,2013,Technological Studies,79.0,female,Entries,76.0,entries
34595,StandardGrade,2013,Technological Studies,79.0,female,percentage,6.0,percentage
109838,StandardGrade,2013,Technological Studies,79.0,male,1,439.0,numerical
113951,StandardGrade,2013,Technological Studies,79.0,male,2,299.0,numerical
118064,StandardGrade,2013,Technological Studies,79.0,male,3,187.0,numerical
122232,StandardGrade,2013,Technological Studies,79.0,male,4,143.0,numerical
126345,StandardGrade,2013,Technological Studies,79.0,male,5,91.0,numerical
129228,StandardGrade,2013,Technological Studies,79.0,male,6,48.0,numerical
132111,StandardGrade,2013,Technological Studies,79.0,male,7,6.0,numerical
17352,StandardGrade,2013,Technological Studies,79.0,male,Entries,1218.0,entries
34594,StandardGrade,2013,Technological Studies,79.0,male,percentage,94.0,percentage
109780,StandardGrade,2013,Urdu,10.0,all,1,60.0,numerical
113893,StandardGrade,2013,Urdu,10.0,all,2,11.0,numerical
118006,StandardGrade,2013,Urdu,10.0,all,3,19.0,numerical
122174,StandardGrade,2013,Urdu,10.0,all,4,6.0,numerical
126287,StandardGrade,2013,Urdu,10.0,all,5,6.0,numerical
129170,StandardGrade,2013,Urdu,10.0,all,6,1.0,numerical
132053,StandardGrade,2013,Urdu,10.0,all,7,NaN,numerical
17294,StandardGrade,2013,Urdu,10.0,all,Entries,103.0,entries
109779,StandardGrade,2013,Urdu,10.0,female,1,26.0,numerical
113892,StandardGrade,2013,Urdu,10.0,female,2,4.0,numerical
118005,StandardGrade,2013,Urdu,10.0,female,3,7.0,numerical
122173,StandardGrade,2013,Urdu,10.0,female,4,1.0,numerical
126286,StandardGrade,2013,Urdu,10.0,female,5,2.0,numerical
129169,StandardGrade,2013,Urdu,10.0,female,6,0.0,numerical
132052,StandardGrade,2013,Urdu,10.0,female,7,0.0,numerical
17293,StandardGrade,2013,Urdu,10.0,female,Entries,40.0,entries
34555,StandardGrade,2013,Urdu,10.0,female,percentage,39.0,percentage
109778,StandardGrade,2013,Urdu,10.0,male,1,34.0,numerical
113891,StandardGrade,2013,Urdu,10.0,male,2,7.0,numerical
118004,StandardGrade,2013,Urdu,10.0,male,3,12.0,numerical
122172,StandardGrade,2013,Urdu,10.0,male,4,5.0,numerical
126285,StandardGrade,2013,Urdu,10.0,male,5,4.0,numerical
129168,StandardGrade,2013,Urdu,10.0,male,6,1.0,numerical
132051,StandardGrade,2013,Urdu,10.0,male,7,0.0,numerical
17292,StandardGrade,2013,Urdu,10.0,male,Entries,63.0,entries
34554,StandardGrade,2013,Urdu,10.0,male,percentage,61.0,percentage

### Create a subroutine to deal with letter_groups

In [49]:
#no_change = ['Entries', 'A', 'B', 'C', 'NoAward', 'Pass', 'Passes']

def calculate_grades(x):
#    total = 0
    for i, v in x.iterrows():
#        total += v.
        if v.grade_type == 'letter_group': #and v.compare_previous != 0: #not a cumulation row
            print (v)          
    return x

In [50]:
df_em = df5.groupby(['qualification', 'year', 'Subject', 'gender']).apply(calculate_grades)

qualification      AdvancedHigher
year                         2014
Subject                Accounting
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   11
grade_type           letter_group
Name: 138367, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                Accounting
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                    8
grade_type           letter_group
Name: 138366, dtype: object
qualification           AdvancedHigher
year                              2014
Subject            Applied Mathematics
NumberOfCentres                    NaN
gender                          female
grade                              A-C
NoOfStudents                        86
grade_type                letter_group
Name: 138369, dtype: object
qualification           AdvancedHigher
year                              2014
Subject            Applied Mathematics
NumberOfCentres                    NaN
gender                            male
grade                              A-C
NoOfStudents                       197
grade_type                letter_group
Name: 138368, dtype: object
qualification              AdvancedHigher
year                                 2014
Subject            Art and Design: Design
NumberOfCentres                       NaN
gender                             female
grade                                 A-C
NoOfStudents                          423
grade_type                   letter_group
Name: 138371, dtype: object
qualification              AdvancedHigher
year                                 2014
Subject            Art and Design: Design
NumberOfCentres                       NaN
gender                               male
grade                                 A-C
NoOfStudents                           94
grade_type                   letter_group
Name: 138370, dtype: object
qualification                  AdvancedHigher
year                                     2014
Subject            Art and Design: Expressive
NumberOfCentres                           NaN
gender                                 female
grade                                     A-C
NoOfStudents                              661
grade_type                       letter_group
Name: 138373, dtype: object
qualification                  AdvancedHigher
year                                     2014
Subject            Art and Design: Expressive
NumberOfCentres                           NaN
gender                                   male
grade                                     A-C
NoOfStudents                              121
grade_type                       letter_group
Name: 138372, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                   Biology
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                 1248
grade_type           letter_group
Name: 138375, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                   Biology
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  590
grade_type           letter_group
Name: 138374, dtype: object
qualification         AdvancedHigher
year                            2014
Subject            Biology (Revised)
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                       8
grade_type              letter_group
Name: 138377, dtype: object
qualification         AdvancedHigher
year                            2014
Subject            Biology (Revised)
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                       5
grade_type              letter_group
Name: 138376, dtype: object
qualification           AdvancedHigher
year                              2014
Subject            Business Management
NumberOfCentres                    NaN
gender                          female
grade                              A-C
NoOfStudents                        90
grade_type                letter_group
Name: 138379, dtype: object
qualification           AdvancedHigher
year                              2014
Subject            Business Management
NumberOfCentres                    NaN
gender                            male
grade                              A-C
NoOfStudents                        54
grade_type                letter_group
Name: 138378, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                 Chemistry
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  995
grade_type           letter_group
Name: 138381, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                 Chemistry
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  839
grade_type           letter_group
Name: 138380, dtype: object
qualification           AdvancedHigher
year                              2014
Subject            Chemistry (Revised)
NumberOfCentres                    NaN
gender                          female
grade                              A-C
NoOfStudents                       124
grade_type                letter_group
Name: 138383, dtype: object
qualification           AdvancedHigher
year                              2014
Subject            Chemistry (Revised)
NumberOfCentres                    NaN
gender                            male
grade                              A-C
NoOfStudents                       115
grade_type                letter_group
Name: 138382, dtype: object
qualification         AdvancedHigher
year                            2014
Subject            Chinese Languages
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                      12
grade_type              letter_group
Name: 138385, dtype: object
qualification         AdvancedHigher
year                            2014
Subject            Chinese Languages
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                      14
grade_type              letter_group
Name: 138384, dtype: object
qualification       AdvancedHigher
year                          2014
Subject            Classical Greek
NumberOfCentres                NaN
gender                      female
grade                          A-C
NoOfStudents                   NaN
grade_type            letter_group
Name: 138387, dtype: object
qualification       AdvancedHigher
year                          2014
Subject            Classical Greek
NumberOfCentres                NaN
gender                        male
grade                          A-C
NoOfStudents                   NaN
grade_type            letter_group
Name: 138386, dtype: object
qualification         AdvancedHigher
year                            2014
Subject            Classical Studies
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                      26
grade_type              letter_group
Name: 138389, dtype: object
qualification         AdvancedHigher
year                            2014
Subject            Classical Studies
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                      23
grade_type              letter_group
Name: 138388, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                 Computing
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   54
grade_type           letter_group
Name: 138391, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                 Computing
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  318
grade_type           letter_group
Name: 138390, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                     Drama
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  211
grade_type           letter_group
Name: 138393, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                     Drama
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                   81
grade_type           letter_group
Name: 138392, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                 Economics
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   14
grade_type           letter_group
Name: 138395, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                 Economics
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                   51
grade_type           letter_group
Name: 138394, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                   English
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                 1090
grade_type           letter_group
Name: 138397, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                   English
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  384
grade_type           letter_group
Name: 138396, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                    French
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  386
grade_type           letter_group
Name: 138399, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                    French
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  116
grade_type           letter_group
Name: 138398, dtype: object
qualification         AdvancedHigher
year                            2014
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                      12
grade_type              letter_group
Name: 138401, dtype: object
qualification         AdvancedHigher
year                            2014
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                       7
grade_type              letter_group
Name: 138400, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                 Geography
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  439
grade_type           letter_group
Name: 138405, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                 Geography
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  349
grade_type           letter_group
Name: 138404, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                    German
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   88
grade_type           letter_group
Name: 138407, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                    German
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                   34
grade_type           letter_group
Name: 138406, dtype: object
qualification             AdvancedHigher
year                                2014
Subject            Graphic Communication
NumberOfCentres                      NaN
gender                            female
grade                                A-C
NoOfStudents                         294
grade_type                  letter_group
Name: 138409, dtype: object
qualification             AdvancedHigher
year                                2014
Subject            Graphic Communication
NumberOfCentres                      NaN
gender                              male
grade                                A-C
NoOfStudents                         572
grade_type                  letter_group
Name: 138408, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                  Gàidhlig
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   19
grade_type           letter_group
Name: 138403, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                  Gàidhlig
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                    7
grade_type           letter_group
Name: 138402, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                   History
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  720
grade_type           letter_group
Name: 138411, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                   History
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  478
grade_type           letter_group
Name: 138410, dtype: object
qualification                                  AdvancedHigher
year                                                     2014
Subject            Home Economics: Health and Food Technology
NumberOfCentres                                           NaN
gender                                                 female
grade                                                     A-C
NoOfStudents                                               29
grade_type                                       letter_group
Name: 138413, dtype: object
qualification                                  AdvancedHigher
year                                                     2014
Subject            Home Economics: Health and Food Technology
NumberOfCentres                                           NaN
gender                                                   male
grade                                                     A-C
NoOfStudents                                                3
grade_type                                       letter_group
Name: 138412, dtype: object
qualification           AdvancedHigher
year                              2014
Subject            Information Systems
NumberOfCentres                    NaN
gender                          female
grade                              A-C
NoOfStudents                        13
grade_type                letter_group
Name: 138415, dtype: object
qualification           AdvancedHigher
year                              2014
Subject            Information Systems
NumberOfCentres                    NaN
gender                            male
grade                              A-C
NoOfStudents                        14
grade_type                letter_group
Name: 138414, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                   Italian
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   22
grade_type           letter_group
Name: 138417, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                   Italian
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                   10
grade_type           letter_group
Name: 138416, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                     Latin
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   15
grade_type           letter_group
Name: 138419, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                     Latin
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                   11
grade_type           letter_group
Name: 138418, dtype: object
qualification      AdvancedHigher
year                         2014
Subject               Mathematics
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  982
grade_type           letter_group
Name: 138421, dtype: object
qualification      AdvancedHigher
year                         2014
Subject               Mathematics
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                 1430
grade_type           letter_group
Name: 138420, dtype: object
qualification      AdvancedHigher
year                         2014
Subject            Modern Studies
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  468
grade_type           letter_group
Name: 138423, dtype: object
qualification      AdvancedHigher
year                         2014
Subject            Modern Studies
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  218
grade_type           letter_group
Name: 138422, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                     Music
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  784
grade_type           letter_group
Name: 138425, dtype: object
qualification      AdvancedHigher
year                         2014
Subject                     Music
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  668
grade_type           letter_group
Name: 138424, dtype: object
qualification          AdvancedHigher
year                             2014
Subject            Physical Education
NumberOfCentres                   NaN
gender                         female
grade                             A-C
NoOfStudents                       40
grade_type               letter_group
Name: 138427, dtype: object
qualification          AdvancedHigher
year                             2014
Subject            Physical Education
NumberOfCentres                   NaN
gender                           male
grade                             A-C

Name: 139087, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                   Biology
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  610
grade_type           letter_group
Name: 139086, dtype: object
qualification           AdvancedHigher
year                              2016
Subject            Business Management
NumberOfCentres                    NaN
gender                          female
grade                              A-C
NoOfStudents                       162
grade_type                letter_group
Name: 139089, dtype: object
qualification           AdvancedHigher
year                              2016
Subject            Business Management
NumberOfCentres                    NaN
gender                            male
grade                              A-C
NoOfStudents                       127
grade_type                letter_group
Name: 139088, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                 Chemistry
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                 1142
grade_type           letter_group
Name: 139091, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                 Chemistry
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                 1029
grade_type           letter_group
Name: 139090, dtype: object
qualification         AdvancedHigher
year                            2016
Subject            Chinese Languages
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                      20
grade_type              letter_group
Name: 139093, dtype: object
qualification         AdvancedHigher
year                            2016
Subject            Chinese Languages
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                      12
grade_type              letter_group
Name: 139092, dtype: object
qualification         AdvancedHigher
year                            2016
Subject            Classical Studies
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                      39
grade_type              letter_group
Name: 139095, dtype: object
qualification         AdvancedHigher
year                            2016
Subject            Classical Studies
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                      22
grade_type              letter_group
Name: 139094, dtype: object
qualification         AdvancedHigher
year                            2016
Subject            Computing Science
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                      60
grade_type              letter_group
Name: 139097, dtype: object
qualification         AdvancedHigher
year                            2016
Subject            Computing Science
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                     304
grade_type              letter_group
Name: 139096, dtype: object
qualification              AdvancedHigher
year                                 2016
Subject            Design and Manufacture
NumberOfCentres                       NaN
gender                             female
grade                                 A-C
NoOfStudents                           20
grade_type                   letter_group
Name: 139099, dtype: object
qualification              AdvancedHigher
year                                 2016
Subject            Design and Manufacture
NumberOfCentres                       NaN
gender                               male
grade                                 A-C
NoOfStudents                           14
grade_type                   letter_group
Name: 139098, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                     Drama
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  312
grade_type           letter_group
Name: 139101, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                     Drama
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  126
grade_type           letter_group
Name: 139100, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                 Economics
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   33
grade_type           letter_group
Name: 139103, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                 Economics
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                   56
grade_type           letter_group
Name: 139102, dtype: object
qualification           AdvancedHigher
year                              2016
Subject            Engineering Science
NumberOfCentres                    NaN
gender                          female
grade                              A-C
NoOfStudents                       NaN
grade_type                letter_group
Name: 139105, dtype: object
qualification           AdvancedHigher
year                              2016
Subject            Engineering Science
NumberOfCentres                    NaN
gender                            male
grade                              A-C
NoOfStudents                        54
grade_type                letter_group
Name: 139104, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                   English
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                 1395
grade_type           letter_group
Name: 139107, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                   English
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  491
grade_type           letter_group
Name: 139106, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                    French
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  468
grade_type           letter_group
Name: 139109, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                    French
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  124
grade_type           letter_group
Name: 139108, dtype: object
qualification         AdvancedHigher
year                            2016
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                      17
grade_type              letter_group
Name: 139111, dtype: object
qualification         AdvancedHigher
year                            2016
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                       4
grade_type              letter_group
Name: 139110, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                 Geography
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  497
grade_type           letter_group
Name: 139115, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                 Geography
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  317
grade_type           letter_group
Name: 139114, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                    German
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   84
grade_type           letter_group
Name: 139117, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                    German
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                   42
grade_type           letter_group
Name: 139116, dtype: object
qualification             AdvancedHigher
year                                2016
Subject            Graphic Communication
NumberOfCentres                      NaN
gender                            female
grade                                A-C
NoOfStudents                         177
grade_type                  letter_group
Name: 139119, dtype: object
qualification             AdvancedHigher
year                                2016
Subject            Graphic Communication
NumberOfCentres                      NaN
gender                              male
grade                                A-C
NoOfStudents                         266
grade_type                  letter_group
Name: 139118, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                  Gàidhlig
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   26
grade_type           letter_group
Name: 139113, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                  Gàidhlig
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  NaN
grade_type           letter_group
Name: 139112, dtype: object
qualification                  AdvancedHigher
year                                     2016
Subject            Health and Food Technology
NumberOfCentres                           NaN
gender                                 female
grade                                     A-C
NoOfStudents                               18
grade_type                       letter_group
Name: 139121, dtype: object
qualification                  AdvancedHigher
year                                     2016
Subject            Health and Food Technology
NumberOfCentres                           NaN
gender                                   male
grade                                     A-C
NoOfStudents                              NaN
grade_type                       letter_group
Name: 139120, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                   History
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  861
grade_type           letter_group
Name: 139123, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                   History
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  510
grade_type           letter_group
Name: 139122, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                   Italian
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   16
grade_type           letter_group
Name: 139125, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                   Italian
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  NaN
grade_type           letter_group
Name: 139124, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                     Latin
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   45
grade_type           letter_group
Name: 139127, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                     Latin
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                   25
grade_type           letter_group
Name: 139126, dtype: object
qualification      AdvancedHigher
year                         2016
Subject               Mathematics
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  943
grade_type           letter_group
Name: 139129, dtype: object
qualification      AdvancedHigher
year                         2016
Subject               Mathematics
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                 1526
grade_type           letter_group
Name: 139128, dtype: object
qualification                AdvancedHigher
year                                   2016
Subject            Mathematics of Mechanics
NumberOfCentres                         NaN
gender                               female
grade                                   A-C
NoOfStudents                             36
grade_type                     letter_group
Name: 139131, dtype: object
qualification                AdvancedHigher
year                                   2016
Subject            Mathematics of Mechanics
NumberOfCentres                         NaN
gender                                 male
grade                                   A-C
NoOfStudents                            128
grade_type                     letter_group
Name: 139130, dtype: object
qualification      AdvancedHigher
year                         2016
Subject            Modern Studies
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  473
grade_type           letter_group
Name: 139133, dtype: object
qualification      AdvancedHigher
year                         2016
Subject            Modern Studies
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  222
grade_type           letter_group
Name: 139132, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                     Music
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  898
grade_type           letter_group
Name: 139135, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                     Music
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  684
grade_type           letter_group
Name: 139134, dtype: object
qualification        AdvancedHigher
year                           2016
Subject            Music: Portfolio
NumberOfCentres                 NaN
gender                       female
grade                           A-C
NoOfStudents                    NaN
grade_type             letter_group
Name: 139137, dtype: object
qualification        AdvancedHigher
year                           2016
Subject            Music: Portfolio
NumberOfCentres                 NaN
gender                         male
grade                           A-C
NoOfStudents                     10
grade_type             letter_group
Name: 139136, dtype: object
qualification          AdvancedHigher
year                             2016
Subject            Physical Education
NumberOfCentres                   NaN
gender                         female
grade                             A-C
NoOfStudents                       77
grade_type               letter_group
Name: 139139, dtype: object
qualification          AdvancedHigher
year                             2016
Subject            Physical Education
NumberOfCentres                   NaN
gender                           male
grade                             A-C
NoOfStudents                      104
grade_type               letter_group
Name: 139138, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                   Physics
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  343
grade_type           letter_group
Name: 139141, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                   Physics
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                 1170
grade_type           letter_group
Name: 139140, dtype: object
qualification                                  AdvancedHigher
year                                                     2016
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                 female
grade                                                     A-C
NoOfStudents                                              134
grade_type                                       letter_group
Name: 139143, dtype: object
qualification                                  AdvancedHigher
year                                                     2016
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                   male
grade                                                     A-C
NoOfStudents                                               43
grade_type                                       letter_group
Name: 139142, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                   Spanish
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  291
grade_type           letter_group
Name: 139145, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                   Spanish
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                   98
grade_type           letter_group
Name: 139144, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                Statistics
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   58
grade_type           letter_group
Name: 139147, dtype: object
qualification      AdvancedHigher
year                         2016
Subject                Statistics
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                   83
grade_type           letter_group
Name: 139146, dtype: object
qualification      AdvancedHigher
year                         2017
Subject                Accounting
NumberOfCentres               NaN
gender                     female

Name: 139427, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                   English
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  529
grade_type           letter_group
Name: 139426, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                    French
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  422
grade_type           letter_group
Name: 139429, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                    French
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  132
grade_type           letter_group
Name: 139428, dtype: object
qualification         AdvancedHigher
year                            2018
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                       7
grade_type              letter_group
Name: 139431, dtype: object
qualification         AdvancedHigher
year                            2018
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                     NaN
grade_type              letter_group
Name: 139430, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                 Geography
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  421
grade_type           letter_group
Name: 139435, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                 Geography
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  297
grade_type           letter_group
Name: 139434, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                    German
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   85
grade_type           letter_group
Name: 139437, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                    German
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                   30
grade_type           letter_group
Name: 139436, dtype: object
qualification             AdvancedHigher
year                                2018
Subject            Graphic Communication
NumberOfCentres                      NaN
gender                            female
grade                                A-C
NoOfStudents                         155
grade_type                  letter_group
Name: 139439, dtype: object
qualification             AdvancedHigher
year                                2018
Subject            Graphic Communication
NumberOfCentres                      NaN
gender                              male
grade                                A-C
NoOfStudents                         194
grade_type                  letter_group
Name: 139438, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                  Gàidhlig
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   18
grade_type           letter_group
Name: 139433, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                  Gàidhlig
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                    8
grade_type           letter_group
Name: 139432, dtype: object
qualification                  AdvancedHigher
year                                     2018
Subject            Health and Food Technology
NumberOfCentres                           NaN
gender                                 female
grade                                     A-C
NoOfStudents                               33
grade_type                       letter_group
Name: 139441, dtype: object
qualification                  AdvancedHigher
year                                     2018
Subject            Health and Food Technology
NumberOfCentres                           NaN
gender                                   male
grade                                     A-C
NoOfStudents                              NaN
grade_type                       letter_group
Name: 139440, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                   History
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  772
grade_type           letter_group
Name: 139443, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                   History
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  482
grade_type           letter_group
Name: 139442, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                   Italian
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   24
grade_type           letter_group
Name: 139445, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                   Italian
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                   10
grade_type           letter_group
Name: 139444, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                     Latin
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   27
grade_type           letter_group
Name: 139447, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                     Latin
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                   10
grade_type           letter_group
Name: 139446, dtype: object
qualification      AdvancedHigher
year                         2018
Subject               Mathematics
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                 1134
grade_type           letter_group
Name: 139449, dtype: object
qualification      AdvancedHigher
year                         2018
Subject               Mathematics
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                 1618
grade_type           letter_group
Name: 139448, dtype: object
qualification                AdvancedHigher
year                                   2018
Subject            Mathematics of Mechanics
NumberOfCentres                         NaN
gender                               female
grade                                   A-C
NoOfStudents                             63
grade_type                     letter_group
Name: 139451, dtype: object
qualification                AdvancedHigher
year                                   2018
Subject            Mathematics of Mechanics
NumberOfCentres                         NaN
gender                                 male
grade                                   A-C
NoOfStudents                            180
grade_type                     letter_group
Name: 139450, dtype: object
qualification      AdvancedHigher
year                         2018
Subject            Modern Studies
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  463
grade_type           letter_group
Name: 139453, dtype: object
qualification      AdvancedHigher
year                         2018
Subject            Modern Studies
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  196
grade_type           letter_group
Name: 139452, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                     Music
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  965
grade_type           letter_group
Name: 139455, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                     Music
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  644
grade_type           letter_group
Name: 139454, dtype: object
qualification        AdvancedHigher
year                           2018
Subject            Music: Portfolio
NumberOfCentres                 NaN
gender                       female
grade                           A-C
NoOfStudents                    NaN
grade_type             letter_group
Name: 139457, dtype: object
qualification        AdvancedHigher
year                           2018
Subject            Music: Portfolio
NumberOfCentres                 NaN
gender                         male
grade                           A-C
NoOfStudents                      7
grade_type             letter_group
Name: 139456, dtype: object
qualification          AdvancedHigher
year                             2018
Subject            Physical Education
NumberOfCentres                   NaN
gender                         female
grade                             A-C
NoOfStudents                      153
grade_type               letter_group
Name: 139459, dtype: object
qualification          AdvancedHigher
year                             2018
Subject            Physical Education
NumberOfCentres                   NaN
gender                           male
grade                             A-C
NoOfStudents                      169
grade_type               letter_group
Name: 139458, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                   Physics
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  336
grade_type           letter_group
Name: 139461, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                   Physics
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                 1164
grade_type           letter_group
Name: 139460, dtype: object
qualification                                  AdvancedHigher
year                                                     2018
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                 female
grade                                                     A-C
NoOfStudents                                               81
grade_type                                       letter_group
Name: 139463, dtype: object
qualification                                  AdvancedHigher
year                                                     2018
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                   male
grade                                                     A-C
NoOfStudents                                               26
grade_type                                       letter_group
Name: 139462, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                   Spanish
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  253
grade_type           letter_group
Name: 139465, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                   Spanish
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                   90
grade_type           letter_group
Name: 139464, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                Statistics
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   66
grade_type           letter_group
Name: 139467, dtype: object
qualification      AdvancedHigher
year                         2018
Subject                Statistics
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                   79
grade_type           letter_group
Name: 139466, dtype: object
qualification      AdvancedHigher
year                         2019
Subject                Accounting
NumberOfCentres               NaN
gender              NotApplicable
grade                         A-C
NoOfStudents                  NaN
grade_type           letter_group
Name: 139563, dtype: object
qualification      AdvancedHigher
year                         2019
Subject                Accounting
NumberOfCentres               NaN
gender                   NotKnown
grade                         A-C
NoOfStudents                  NaN
grade_type           letter_group
Name: 139562, dtype: object
qualification      AdvancedHigher
year                         2019
Subject                Accounting
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   24
grade_type           letter_group
Name: 139561, dtype: object
qualification      AdvancedHigher
year                         2019
Subject                Accounting
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                   33
grade_type           letter_group
Name: 139560, dtype: object
qualification               AdvancedHigher
year                                  2019
Subject            Art and Design (Design)
NumberOfCentres                        NaN
gender                       NotApplicable
grade                                  A-C
NoOfStudents                           NaN
grade_type                    letter_group
Name: 139567, dtype: object
qualification               AdvancedHigher
year                                  2019
Subject            Art and Design (Design)
NumberOfCentres                        NaN
gender                            NotKnown
grade                                  A-C
NoOfStudents                           NaN
grade_type                    letter_group
Name: 139566, dtype: object
qualification               AdvancedHigher
year                                  2019
Subject            Art and Design (Design)
NumberOfCentres                        NaN
gender                              female
grade                                  A-C
NoOfStudents                           378
grade_type                    letter_group
Name: 139565, dtype: object
qualification               AdvancedHigher
year                                  2019
Subject            Art and Design (Design)
NumberOfCentres                        NaN
gender                                male
grade                                  A-C
NoOfStudents                            89
grade_type                    letter_group
Name: 139564, dtype: object
qualification                   AdvancedHigher
year                                      2019
Subject            Art and Design (Expressive)
NumberOfCentres                            NaN
gender                           NotApplicable
grade                                      A-C
NoOfStudents                               NaN
grade_type                        letter_group
Name: 139571, dtype: object
qualification                   AdvancedHigher
year                                      2019
Subject            Art and Design (Expressive)
NumberOfCentres                            NaN
gender                                NotKnown
grade                                      A-C
NoOfStudents                               NaN
grade_type                        letter_group
Name: 139570, dtype: object
qualification                   AdvancedHigher
year                                      2019
Subject            Art and Design (Expressive)
NumberOfCentres                            NaN
gender                                  female
grade                                      A-C
NoOfStudents                               724
grade_type                        letter_group
Name: 139569, dtype: object
qualification                   AdvancedHigher
year                                      2019
Subject            Art and Design (Expressive)
NumberOfCentres                            NaN
gender                                    male
grade                                      A-C
NoOfStudents                               130
grade_type                        letter_group
Name: 139568, dtype: object
qualification      AdvancedHigher
year                         2019
Subject                   Biology
NumberOfCentres               NaN
gender              NotApplicable
grade                         A-C
NoOfStudents                  NaN
grade_type           letter_group
Name: 139575, dtype: object
qualification      AdvancedHigher
year                         2019
Subject                   Biology
NumberOfCentres               NaN
gender                   NotKnown
grade                         A-C
NoOfStudents                  NaN
grade_type           letter_group
Name: 139574, dtype: object
qualification      AdvancedHigher
year                         2019
Subject                   Biology
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                 1233
grade_type           letter_group
Name: 139573, dtype: object
qualification      AdvancedHigher
year                         2019
Subject                   Biology
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  483
grade_type           letter_group
Name: 139572, dtype: object
qualification           AdvancedHigher
year                              2019
Subject            Business Management
NumberOfCentres                    NaN
gender                   NotApplicable
grade                              A-C
NoOfStudents                       NaN
grade_type                letter_group
Name: 139579, dtype: object
qualification           AdvancedHigher
year                              2019
Subject            Business Management
NumberOfCentres                    NaN
gender                        NotKnown
grade                              A-C
NoOfStudents                       NaN
grade_type                letter_group
Name: 139578, dtype: object
qualification           AdvancedHigher
year                              2019
Subject            Business Management
NumberOfCentres                    NaN
gender                          female
grade                              A-C
NoOfStudents                       201
grade_type                letter_group
Name: 139577, dtype: object
qualification           AdvancedHigher
year                              2019

Name: 139695, dtype: object
qualification      AdvancedHigher
year                         2019
Subject                Statistics
NumberOfCentres               NaN
gender                   NotKnown
grade                         A-C
NoOfStudents                  NaN
grade_type           letter_group
Name: 139694, dtype: object
qualification      AdvancedHigher
year                         2019
Subject                Statistics
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   68
grade_type           letter_group
Name: 139693, dtype: object
qualification      AdvancedHigher
year                         2019
Subject                Statistics
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                   98
grade_type           letter_group
Name: 139692, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                Accounting
NumberOfCentres               NaN
gender                        all
grade                         A-B
NoOfStudents                   47
grade_type           letter_group
Name: 158122, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                Accounting
NumberOfCentres               NaN
gender                        all
grade                         A-C
NoOfStudents                   58
grade_type           letter_group
Name: 139882, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                Accounting
NumberOfCentres               NaN
gender                        all
grade                        A-D*
NoOfStudents                   60
grade_type           letter_group
Name: 158896, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                Accounting
NumberOfCentres               NaN
gender                     female
grade                         A-B
NoOfStudents                   11
grade_type           letter_group
Name: 158121, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                Accounting
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   13
grade_type           letter_group
Name: 139881, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                Accounting
NumberOfCentres               NaN
gender                     female
grade                        A-D*
NoOfStudents                   13
grade_type           letter_group
Name: 158895, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                Accounting
NumberOfCentres               NaN
gender                       male
grade                         A-B
NoOfStudents                   39
grade_type           letter_group
Name: 158120, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                Accounting
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                   47
grade_type           letter_group
Name: 139880, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                Accounting
NumberOfCentres               NaN
gender                       male
grade                        A-D*
NoOfStudents                   47
grade_type           letter_group
Name: 158894, dtype: object
qualification               AdvancedHigher
year                                  2020
Subject            Art and Design (Design)
NumberOfCentres                        NaN
gender                                 all
grade                                  A-B
NoOfStudents                           407
grade_type                    letter_group
Name: 158125, dtype: object
qualification               AdvancedHigher
year                                  2020
Subject            Art and Design (Design)
NumberOfCentres                        NaN
gender                                 all
grade                                  A-C
NoOfStudents                           509
grade_type                    letter_group
Name: 139885, dtype: object
qualification               AdvancedHigher
year                                  2020
Subject            Art and Design (Design)
NumberOfCentres                        NaN
gender                                 all
grade                                 A-D*
NoOfStudents                           530
grade_type                    letter_group
Name: 158899, dtype: object
qualification               AdvancedHigher
year                                  2020
Subject            Art and Design (Design)
NumberOfCentres                        NaN
gender                              female
grade                                  A-B
NoOfStudents                           336
grade_type                    letter_group
Name: 158124, dtype: object
qualification               AdvancedHigher
year                                  2020
Subject            Art and Design (Design)
NumberOfCentres                        NaN
gender                              female
grade                                  A-C
NoOfStudents                           401
grade_type                    letter_group
Name: 139884, dtype: object
qualification               AdvancedHigher
year                                  2020
Subject            Art and Design (Design)
NumberOfCentres                        NaN
gender                              female
grade                                 A-D*
NoOfStudents                           414
grade_type                    letter_group
Name: 158898, dtype: object
qualification               AdvancedHigher
year                                  2020
Subject            Art and Design (Design)
NumberOfCentres                        NaN
gender                                male
grade                                  A-B
NoOfStudents                            93
grade_type                    letter_group
Name: 158123, dtype: object
qualification               AdvancedHigher
year                                  2020
Subject            Art and Design (Design)
NumberOfCentres                        NaN
gender                                male
grade                                  A-C
NoOfStudents                           113
grade_type                    letter_group
Name: 139883, dtype: object
qualification               AdvancedHigher
year                                  2020
Subject            Art and Design (Design)
NumberOfCentres                        NaN
gender                                male
grade                                 A-D*
NoOfStudents                           116
grade_type                    letter_group
Name: 158897, dtype: object
qualification                   AdvancedHigher
year                                      2020
Subject            Art and Design (Expressive)
NumberOfCentres                            NaN
gender                                     all
grade                                      A-B
NoOfStudents                               747
grade_type                        letter_group
Name: 158128, dtype: object
qualification                   AdvancedHigher
year                                      2020
Subject            Art and Design (Expressive)
NumberOfCentres                            NaN
gender                                     all
grade                                      A-C
NoOfStudents                               983
grade_type                        letter_group
Name: 139888, dtype: object
qualification                   AdvancedHigher
year                                      2020
Subject            Art and Design (Expressive)
NumberOfCentres                            NaN
gender                                     all
grade                                     A-D*
NoOfStudents                              1007
grade_type                        letter_group
Name: 158902, dtype: object
qualification                   AdvancedHigher
year                                      2020
Subject            Art and Design (Expressive)
NumberOfCentres                            NaN
gender                                  female
grade                                      A-B
NoOfStudents                               712
grade_type                        letter_group
Name: 158127, dtype: object
qualification                   AdvancedHigher
year                                      2020
Subject            Art and Design (Expressive)
NumberOfCentres                            NaN
gender                                  female
grade                                      A-C
NoOfStudents                               845
grade_type                        letter_group
Name: 139887, dtype: object
qualification                   AdvancedHigher
year                                      2020
Subject            Art and Design (Expressive)
NumberOfCentres                            NaN
gender                                  female
grade                                     A-D*
NoOfStudents                               862
grade_type                        letter_group
Name: 158901, dtype: object
qualification                   AdvancedHigher
year                                      2020
Subject            Art and Design (Expressive)
NumberOfCentres                            NaN
gender                                    male
grade                                      A-B
NoOfStudents                               103
grade_type                        letter_group
Name: 158126, dtype: object
qualification                   AdvancedHigher
year                                      2020
Subject            Art and Design (Expressive)
NumberOfCentres                            NaN
gender                                    male
grade                                      A-C
NoOfStudents                               140
grade_type                        letter_group
Name: 139886, dtype: object
qualification                   AdvancedHigher
year                                      2020
Subject            Art and Design (Expressive)
NumberOfCentres                            NaN
gender                                    male
grade                                     A-D*
NoOfStudents                               145
grade_type                        letter_group
Name: 158900, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Biology
NumberOfCentres               NaN
gender                        all
grade                         A-B
NoOfStudents                 1495
grade_type           letter_group
Name: 158131, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Biology
NumberOfCentres               NaN
gender                        all
grade                         A-C
NoOfStudents                 2049
grade_type           letter_group
Name: 139891, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Biology
NumberOfCentres               NaN
gender                        all
grade                        A-D*
NoOfStudents                 2311
grade_type           letter_group
Name: 158905, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Biology
NumberOfCentres               NaN
gender                     female
grade                         A-B
NoOfStudents                 1147
grade_type           letter_group
Name: 158130, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Biology
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                 1573
grade_type           letter_group
Name: 139890, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Biology
NumberOfCentres               NaN
gender                     female
grade                        A-D*
NoOfStudents                 1693
grade_type           letter_group
Name: 158904, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Biology
NumberOfCentres               NaN
gender                       male
grade                         A-B
NoOfStudents                  481
grade_type           letter_group
Name: 158129, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Biology
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  667
grade_type           letter_group
Name: 139889, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Biology
NumberOfCentres               NaN
gender                       male
grade                        A-D*
NoOfStudents                  735
grade_type           letter_group
Name: 158903, dtype: object
qualification           AdvancedHigher
year                              2020
Subject            Business Management
NumberOfCentres                    NaN
gender                             all
grade                              A-B
NoOfStudents                       356
grade_type                letter_group
Name: 158134, dtype: object
qualification           AdvancedHigher
year                              2020
Subject            Business Management
NumberOfCentres                    NaN
gender                             all
grade                              A-C
NoOfStudents                       470
grade_type                letter_group
Name: 139894, dtype: object
qualification           AdvancedHigher
year                              2020
Subject            Business Management
NumberOfCentres                    NaN
gender                             all
grade                             A-D*
NoOfStudents                       526
grade_type                letter_group
Name: 158908, dtype: object
qualification           AdvancedHigher
year                              2020
Subject            Business Management
NumberOfCentres                    NaN
gender                          female
grade                              A-B
NoOfStudents                       249
grade_type                letter_group
Name: 158133, dtype: object
qualification           AdvancedHigher
year                              2020
Subject            Business Management
NumberOfCentres                    NaN
gender                          female
grade                              A-C
NoOfStudents                       286
grade_type                letter_group
Name: 139893, dtype: object
qualification           AdvancedHigher
year                              2020
Subject            Business Management
NumberOfCentres                    NaN
gender                          female
grade                             A-D*
NoOfStudents                       291
grade_type                letter_group
Name: 158907, dtype: object
qualification           AdvancedHigher
year                              2020
Subject            Business Management
NumberOfCentres                    NaN
gender                            male
grade                              A-B
NoOfStudents                       203
grade_type                letter_group
Name: 158132, dtype: object
qualification           AdvancedHigher
year                              2020
Subject            Business Management
NumberOfCentres                    NaN
gender                            male
grade                              A-C
NoOfStudents                       250
grade_type                letter_group
Name: 139892, dtype: object
qualification           AdvancedHigher
year                              2020
Subject            Business Management
NumberOfCentres                    NaN
gender                            male
grade                             A-D*
NoOfStudents                       264
grade_type                letter_group
Name: 158906, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                 Chemistry
NumberOfCentres               NaN
gender                        all
grade                         A-B
NoOfStudents                 1643
grade_type           letter_group
Name: 158137, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                 Chemistry
NumberOfCentres               NaN
gender                        all
grade                         A-C
NoOfStudents                 2157
grade_type           letter_group
Name: 139897, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                 Chemistry
NumberOfCentres               NaN
gender                        all
grade                        A-D*
NoOfStudents                 2447
grade_type           letter_group
Name: 158911, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                 Chemistry
NumberOfCentres               NaN
gender                     female
grade                         A-B
NoOfStudents                 1034
grade_type           letter_group
Name: 158136, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                 Chemistry
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                 1330
grade_type           letter_group
Name: 139896, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                 Chemistry
NumberOfCentres               NaN
gender                     female
grade                        A-D*
NoOfStudents                 1395
grade_type           letter_group
Name: 158910, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                 Chemistry
NumberOfCentres               NaN
gender                       male
grade                         A-B
NoOfStudents                  786
grade_type           letter_group
Name: 158135, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                 Chemistry
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                 1039
grade_type           letter_group
Name: 139895, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                 Chemistry
NumberOfCentres               NaN
gender                       male
grade                        A-D*
NoOfStudents                 1110
grade_type           letter_group
Name: 158909, dtype: object
qualification         AdvancedHigher
year                            2020
Subject            Chinese Languages
NumberOfCentres                  NaN
gender                           all
grade                            A-B
NoOfStudents                      61
grade_type              letter_group
Name: 158140, dtype: object
qualification         AdvancedHigher
year                            2020
Subject            Chinese Languages
NumberOfCentres                  NaN
gender                           all
grade                            A-C
NoOfStudents                      61
grade_type              letter_group
Name: 139900, dtype: object
qualification         AdvancedHigher
year                            2020
Subject            Chinese Languages
NumberOfCentres                  NaN
gender                           all
grade                           A-D*
NoOfStudents                      61

Name: 158215, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Physics
NumberOfCentres               NaN
gender                        all
grade                         A-C
NoOfStudents                 1386
grade_type           letter_group
Name: 139975, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Physics
NumberOfCentres               NaN
gender                        all
grade                        A-D*
NoOfStudents                 1609
grade_type           letter_group
Name: 158989, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Physics
NumberOfCentres               NaN
gender                     female
grade                         A-B
NoOfStudents                  321
grade_type           letter_group
Name: 158214, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Physics
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  386
grade_type           letter_group
Name: 139974, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Physics
NumberOfCentres               NaN
gender                     female
grade                        A-D*
NoOfStudents                  398
grade_type           letter_group
Name: 158988, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Physics
NumberOfCentres               NaN
gender                       male
grade                         A-B
NoOfStudents                  964
grade_type           letter_group
Name: 158213, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Physics
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                 1206
grade_type           letter_group
Name: 139973, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Physics
NumberOfCentres               NaN
gender                       male
grade                        A-D*
NoOfStudents                 1270
grade_type           letter_group
Name: 158987, dtype: object
qualification                                  AdvancedHigher
year                                                     2020
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                    all
grade                                                     A-B
NoOfStudents                                              140
grade_type                                       letter_group
Name: 158218, dtype: object
qualification                                  AdvancedHigher
year                                                     2020
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                    all
grade                                                     A-C
NoOfStudents                                              165
grade_type                                       letter_group
Name: 139978, dtype: object
qualification                                  AdvancedHigher
year                                                     2020
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                    all
grade                                                    A-D*
NoOfStudents                                              180
grade_type                                       letter_group
Name: 158992, dtype: object
qualification                                  AdvancedHigher
year                                                     2020
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                 female
grade                                                     A-B
NoOfStudents                                              105
grade_type                                       letter_group
Name: 158217, dtype: object
qualification                                  AdvancedHigher
year                                                     2020
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                 female
grade                                                     A-C
NoOfStudents                                              120
grade_type                                       letter_group
Name: 139977, dtype: object
qualification                                  AdvancedHigher
year                                                     2020
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                 female
grade                                                    A-D*
NoOfStudents                                              124
grade_type                                       letter_group
Name: 158991, dtype: object
qualification                                  AdvancedHigher
year                                                     2020
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                   male
grade                                                     A-B
NoOfStudents                                               44
grade_type                                       letter_group
Name: 158216, dtype: object
qualification                                  AdvancedHigher
year                                                     2020
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                   male
grade                                                     A-C
NoOfStudents                                               54
grade_type                                       letter_group
Name: 139976, dtype: object
qualification                                  AdvancedHigher
year                                                     2020
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                   male
grade                                                    A-D*
NoOfStudents                                               56
grade_type                                       letter_group
Name: 158990, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Spanish
NumberOfCentres               NaN
gender                        all
grade                         A-B
NoOfStudents                  319
grade_type           letter_group
Name: 158221, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Spanish
NumberOfCentres               NaN
gender                        all
grade                         A-C
NoOfStudents                  396
grade_type           letter_group
Name: 139981, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Spanish
NumberOfCentres               NaN
gender                        all
grade                        A-D*
NoOfStudents                  440
grade_type           letter_group
Name: 158995, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Spanish
NumberOfCentres               NaN
gender                     female
grade                         A-B
NoOfStudents                  270
grade_type           letter_group
Name: 158220, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Spanish
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  325
grade_type           letter_group
Name: 139980, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Spanish
NumberOfCentres               NaN
gender                     female
grade                        A-D*
NoOfStudents                  332
grade_type           letter_group
Name: 158994, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Spanish
NumberOfCentres               NaN
gender                       male
grade                         A-B
NoOfStudents                  104
grade_type           letter_group
Name: 158219, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Spanish
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  125
grade_type           letter_group
Name: 139979, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                   Spanish
NumberOfCentres               NaN
gender                       male
grade                        A-D*
NoOfStudents                  129
grade_type           letter_group
Name: 158993, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                Statistics
NumberOfCentres               NaN
gender                        all
grade                         A-B
NoOfStudents                  126
grade_type           letter_group
Name: 158224, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                Statistics
NumberOfCentres               NaN
gender                        all
grade                         A-C
NoOfStudents                  152
grade_type           letter_group
Name: 139984, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                Statistics
NumberOfCentres               NaN
gender                        all
grade                        A-D*
NoOfStudents                  171
grade_type           letter_group
Name: 158998, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                Statistics
NumberOfCentres               NaN
gender                     female
grade                         A-B
NoOfStudents                   58
grade_type           letter_group
Name: 158223, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                Statistics
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   62
grade_type           letter_group
Name: 139983, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                Statistics
NumberOfCentres               NaN
gender                     female
grade                        A-D*
NoOfStudents                   65
grade_type           letter_group
Name: 158997, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                Statistics
NumberOfCentres               NaN
gender                       male
grade                         A-B
NoOfStudents                   82
grade_type           letter_group
Name: 158222, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                Statistics
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  102
grade_type           letter_group
Name: 139982, dtype: object
qualification      AdvancedHigher
year                         2020
Subject                Statistics
NumberOfCentres               NaN
gender                       male
grade                        A-D*
NoOfStudents                  111
grade_type           letter_group
Name: 158996, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                Accounting
NumberOfCentres               NaN
gender                        all
grade                         A-B
NoOfStudents                   54
grade_type           letter_group
Name: 158509, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                Accounting
NumberOfCentres               NaN
gender                        all
grade                         A-C
NoOfStudents                   65
grade_type           letter_group
Name: 140269, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                Accounting
NumberOfCentres               NaN
gender                        all
grade                        A-D*
NoOfStudents                   69
grade_type           letter_group
Name: 159001, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                Accounting
NumberOfCentres               NaN
gender                     female
grade                         A-B
NoOfStudents                  NaN
grade_type           letter_group
Name: 158508, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                Accounting
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  NaN
grade_type           letter_group
Name: 140268, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                Accounting
NumberOfCentres               NaN
gender                     female
grade                        A-D*
NoOfStudents                  NaN
grade_type           letter_group
Name: 159000, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                Accounting
NumberOfCentres               NaN
gender                       male
grade                         A-B
NoOfStudents                  NaN
grade_type           letter_group
Name: 158507, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                Accounting
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  NaN
grade_type           letter_group
Name: 140267, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                Accounting
NumberOfCentres               NaN
gender                       male
grade                        A-D*
NoOfStudents                  NaN
grade_type           letter_group
Name: 158999, dtype: object
qualification               AdvancedHigher
year                                  2021
Subject            Art and Design (Design)
NumberOfCentres                        NaN
gender                                 all
grade                                  A-B
NoOfStudents                           486
grade_type                    letter_group
Name: 158512, dtype: object
qualification               AdvancedHigher
year                                  2021
Subject            Art and Design (Design)
NumberOfCentres                        NaN
gender                                 all
grade                                  A-C
NoOfStudents                           603
grade_type                    letter_group
Name: 140272, dtype: object
qualification               AdvancedHigher
year                                  2021
Subject            Art and Design (Design)
NumberOfCentres                        NaN
gender                                 all
grade                                 A-D*
NoOfStudents                           621
grade_type                    letter_group
Name: 159004, dtype: object
qualification               AdvancedHigher
year                                  2021
Subject            Art and Design (Design)
NumberOfCentres                        NaN
gender                              female
grade                                  A-B
NoOfStudents                           396
grade_type                    letter_group
Name: 158511, dtype: object
qualification               AdvancedHigher
year                                  2021
Subject            Art and Design (Design)
NumberOfCentres                        NaN
gender                              female
grade                                  A-C
NoOfStudents                           486
grade_type                    letter_group
Name: 140271, dtype: object
qualification               AdvancedHigher
year                                  2021
Subject            Art and Design (Design)
NumberOfCentres                        NaN
gender                              female
grade                                 A-D*
NoOfStudents                           503
grade_type                    letter_group
Name: 159003, dtype: object
qualification               AdvancedHigher
year                                  2021
Subject            Art and Design (Design)
NumberOfCentres                        NaN
gender                                male
grade                                  A-B
NoOfStudents                            90
grade_type                    letter_group
Name: 158510, dtype: object
qualification               AdvancedHigher
year                                  2021
Subject            Art and Design (Design)
NumberOfCentres                        NaN
gender                                male
grade                                  A-C
NoOfStudents                           117
grade_type                    letter_group
Name: 140270, dtype: object
qualification               AdvancedHigher
year                                  2021
Subject            Art and Design (Design)
NumberOfCentres                        NaN
gender                                male
grade                                 A-D*
NoOfStudents                           118
grade_type                    letter_group
Name: 159002, dtype: object
qualification                   AdvancedHigher
year                                      2021
Subject            Art and Design (Expressive)
NumberOfCentres                            NaN
gender                                     all
grade                                      A-B
NoOfStudents                               923
grade_type                        letter_group
Name: 158515, dtype: object
qualification                   AdvancedHigher
year                                      2021
Subject            Art and Design (Expressive)
NumberOfCentres                            NaN
gender                                     all
grade                                      A-C
NoOfStudents                              1110
grade_type                        letter_group
Name: 140275, dtype: object
qualification                   AdvancedHigher
year                                      2021
Subject            Art and Design (Expressive)
NumberOfCentres                            NaN
gender                                     all
grade                                     A-D*
NoOfStudents                              1147
grade_type                        letter_group
Name: 159007, dtype: object
qualification                   AdvancedHigher
year                                      2021
Subject            Art and Design (Expressive)
NumberOfCentres                            NaN

Name: 158582, dtype: object
qualification                AdvancedHigher
year                                   2021
Subject            Mathematics of Mechanics
NumberOfCentres                         NaN
gender                                 male
grade                                   A-C
NoOfStudents                            217
grade_type                     letter_group
Name: 140342, dtype: object
qualification                AdvancedHigher
year                                   2021
Subject            Mathematics of Mechanics
NumberOfCentres                         NaN
gender                                 male
grade                                  A-D*
NoOfStudents                            233
grade_type                     letter_group
Name: 159074, dtype: object
qualification      AdvancedHigher
year                         2021
Subject            Modern Studies
NumberOfCentres               NaN
gender                        all
grade                         A-B
NoOfStudents                  789
grade_type           letter_group
Name: 158587, dtype: object
qualification      AdvancedHigher
year                         2021
Subject            Modern Studies
NumberOfCentres               NaN
gender                        all
grade                         A-C
NoOfStudents                  994
grade_type           letter_group
Name: 140347, dtype: object
qualification      AdvancedHigher
year                         2021
Subject            Modern Studies
NumberOfCentres               NaN
gender                        all
grade                        A-D*
NoOfStudents                 1049
grade_type           letter_group
Name: 159079, dtype: object
qualification      AdvancedHigher
year                         2021
Subject            Modern Studies
NumberOfCentres               NaN
gender                     female
grade                         A-B
NoOfStudents                  573
grade_type           letter_group
Name: 158586, dtype: object
qualification      AdvancedHigher
year                         2021
Subject            Modern Studies
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  718
grade_type           letter_group
Name: 140346, dtype: object
qualification      AdvancedHigher
year                         2021
Subject            Modern Studies
NumberOfCentres               NaN
gender                     female
grade                        A-D*
NoOfStudents                  749
grade_type           letter_group
Name: 159078, dtype: object
qualification      AdvancedHigher
year                         2021
Subject            Modern Studies
NumberOfCentres               NaN
gender                       male
grade                         A-B
NoOfStudents                  216
grade_type           letter_group
Name: 158585, dtype: object
qualification      AdvancedHigher
year                         2021
Subject            Modern Studies
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  276
grade_type           letter_group
Name: 140345, dtype: object
qualification      AdvancedHigher
year                         2021
Subject            Modern Studies
NumberOfCentres               NaN
gender                       male
grade                        A-D*
NoOfStudents                  300
grade_type           letter_group
Name: 159077, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                     Music
NumberOfCentres               NaN
gender                        all
grade                         A-B
NoOfStudents                 1650
grade_type           letter_group
Name: 158590, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                     Music
NumberOfCentres               NaN
gender                        all
grade                         A-C
NoOfStudents                 1821
grade_type           letter_group
Name: 140350, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                     Music
NumberOfCentres               NaN
gender                        all
grade                        A-D*
NoOfStudents                 1847
grade_type           letter_group
Name: 159082, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                     Music
NumberOfCentres               NaN
gender                     female
grade                         A-B
NoOfStudents                  926
grade_type           letter_group
Name: 158589, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                     Music
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                 1019
grade_type           letter_group
Name: 140349, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                     Music
NumberOfCentres               NaN
gender                     female
grade                        A-D*
NoOfStudents                 1032
grade_type           letter_group
Name: 159081, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                     Music
NumberOfCentres               NaN
gender                       male
grade                         A-B
NoOfStudents                  724
grade_type           letter_group
Name: 158588, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                     Music
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  802
grade_type           letter_group
Name: 140348, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                     Music
NumberOfCentres               NaN
gender                       male
grade                        A-D*
NoOfStudents                  815
grade_type           letter_group
Name: 159080, dtype: object
qualification        AdvancedHigher
year                           2021
Subject            Music Technology
NumberOfCentres                 NaN
gender                          all
grade                           A-B
NoOfStudents                     33
grade_type             letter_group
Name: 158593, dtype: object
qualification        AdvancedHigher
year                           2021
Subject            Music Technology
NumberOfCentres                 NaN
gender                          all
grade                           A-C
NoOfStudents                     46
grade_type             letter_group
Name: 140353, dtype: object
qualification        AdvancedHigher
year                           2021
Subject            Music Technology
NumberOfCentres                 NaN
gender                          all
grade                          A-D*
NoOfStudents                     48
grade_type             letter_group
Name: 159085, dtype: object
qualification        AdvancedHigher
year                           2021
Subject            Music Technology
NumberOfCentres                 NaN
gender                       female
grade                           A-B
NoOfStudents                      6
grade_type             letter_group
Name: 158592, dtype: object
qualification        AdvancedHigher
year                           2021
Subject            Music Technology
NumberOfCentres                 NaN
gender                       female
grade                           A-C
NoOfStudents                      8
grade_type             letter_group
Name: 140352, dtype: object
qualification        AdvancedHigher
year                           2021
Subject            Music Technology
NumberOfCentres                 NaN
gender                       female
grade                          A-D*
NoOfStudents                      8
grade_type             letter_group
Name: 159084, dtype: object
qualification        AdvancedHigher
year                           2021
Subject            Music Technology
NumberOfCentres                 NaN
gender                         male
grade                           A-B
NoOfStudents                     27
grade_type             letter_group
Name: 158591, dtype: object
qualification        AdvancedHigher
year                           2021
Subject            Music Technology
NumberOfCentres                 NaN
gender                         male
grade                           A-C
NoOfStudents                     38
grade_type             letter_group
Name: 140351, dtype: object
qualification        AdvancedHigher
year                           2021
Subject            Music Technology
NumberOfCentres                 NaN
gender                         male
grade                          A-D*
NoOfStudents                     40
grade_type             letter_group
Name: 159083, dtype: object
qualification        AdvancedHigher
year                           2021
Subject            Music: Portfolio
NumberOfCentres                 NaN
gender                          all
grade                           A-B
NoOfStudents                     15
grade_type             letter_group
Name: 158596, dtype: object
qualification        AdvancedHigher
year                           2021
Subject            Music: Portfolio
NumberOfCentres                 NaN
gender                          all
grade                           A-C
NoOfStudents                     16
grade_type             letter_group
Name: 140356, dtype: object
qualification        AdvancedHigher
year                           2021
Subject            Music: Portfolio
NumberOfCentres                 NaN
gender                          all
grade                          A-D*
NoOfStudents                     16
grade_type             letter_group
Name: 159088, dtype: object
qualification        AdvancedHigher
year                           2021
Subject            Music: Portfolio
NumberOfCentres                 NaN
gender                       female
grade                           A-B
NoOfStudents                      5
grade_type             letter_group
Name: 158595, dtype: object
qualification        AdvancedHigher
year                           2021
Subject            Music: Portfolio
NumberOfCentres                 NaN
gender                       female
grade                           A-C
NoOfStudents                      6
grade_type             letter_group
Name: 140355, dtype: object
qualification        AdvancedHigher
year                           2021
Subject            Music: Portfolio
NumberOfCentres                 NaN
gender                       female
grade                          A-D*
NoOfStudents                      6
grade_type             letter_group
Name: 159087, dtype: object
qualification        AdvancedHigher
year                           2021
Subject            Music: Portfolio
NumberOfCentres                 NaN
gender                         male
grade                           A-B
NoOfStudents                     10
grade_type             letter_group
Name: 158594, dtype: object
qualification        AdvancedHigher
year                           2021
Subject            Music: Portfolio
NumberOfCentres                 NaN
gender                         male
grade                           A-C
NoOfStudents                     10
grade_type             letter_group
Name: 140354, dtype: object
qualification        AdvancedHigher
year                           2021
Subject            Music: Portfolio
NumberOfCentres                 NaN
gender                         male
grade                          A-D*
NoOfStudents                     10
grade_type             letter_group
Name: 159086, dtype: object
qualification          AdvancedHigher
year                             2021
Subject            Physical Education
NumberOfCentres                   NaN
gender                            all
grade                             A-B
NoOfStudents                      624
grade_type               letter_group
Name: 158599, dtype: object
qualification          AdvancedHigher
year                             2021
Subject            Physical Education
NumberOfCentres                   NaN
gender                            all
grade                             A-C
NoOfStudents                      759
grade_type               letter_group
Name: 140359, dtype: object
qualification          AdvancedHigher
year                             2021
Subject            Physical Education
NumberOfCentres                   NaN
gender                            all
grade                            A-D*
NoOfStudents                      793
grade_type               letter_group
Name: 159091, dtype: object
qualification          AdvancedHigher
year                             2021
Subject            Physical Education
NumberOfCentres                   NaN
gender                         female
grade                             A-B
NoOfStudents                      292
grade_type               letter_group
Name: 158598, dtype: object
qualification          AdvancedHigher
year                             2021
Subject            Physical Education
NumberOfCentres                   NaN
gender                         female
grade                             A-C
NoOfStudents                      337
grade_type               letter_group
Name: 140358, dtype: object
qualification          AdvancedHigher
year                             2021
Subject            Physical Education
NumberOfCentres                   NaN
gender                         female
grade                            A-D*
NoOfStudents                      342
grade_type               letter_group
Name: 159090, dtype: object
qualification          AdvancedHigher
year                             2021
Subject            Physical Education
NumberOfCentres                   NaN
gender                           male
grade                             A-B
NoOfStudents                      332
grade_type               letter_group
Name: 158597, dtype: object
qualification          AdvancedHigher
year                             2021
Subject            Physical Education
NumberOfCentres                   NaN
gender                           male
grade                             A-C
NoOfStudents                      422
grade_type               letter_group
Name: 140357, dtype: object
qualification          AdvancedHigher
year                             2021
Subject            Physical Education
NumberOfCentres                   NaN
gender                           male
grade                            A-D*
NoOfStudents                      451
grade_type               letter_group
Name: 159089, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                   Physics
NumberOfCentres               NaN
gender                        all
grade                         A-B
NoOfStudents                 1437
grade_type           letter_group
Name: 158602, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                   Physics
NumberOfCentres               NaN
gender                        all
grade                         A-C
NoOfStudents                 1713
grade_type           letter_group
Name: 140362, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                   Physics
NumberOfCentres               NaN
gender                        all
grade                        A-D*
NoOfStudents                 1845
grade_type           letter_group
Name: 159094, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                   Physics
NumberOfCentres               NaN
gender                     female
grade                         A-B
NoOfStudents                  362
grade_type           letter_group
Name: 158601, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                   Physics
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  412
grade_type           letter_group
Name: 140361, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                   Physics
NumberOfCentres               NaN
gender                     female
grade                        A-D*
NoOfStudents                  433
grade_type           letter_group
Name: 159093, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                   Physics
NumberOfCentres               NaN
gender                       male
grade                         A-B
NoOfStudents                 1075
grade_type           letter_group
Name: 158600, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                   Physics
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                 1301
grade_type           letter_group
Name: 140360, dtype: object
qualification      AdvancedHigher
year                         2021
Subject                   Physics
NumberOfCentres               NaN
gender                       male
grade                        A-D*
NoOfStudents                 1412
grade_type           letter_group
Name: 159092, dtype: object
qualification                                  AdvancedHigher
year                                                     2021
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                    all
grade                                                     A-B
NoOfStudents                                              200
grade_type                                       letter_group
Name: 158605, dtype: object
qualification                                  AdvancedHigher
year                                                     2021
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                    all
grade                                                     A-C
NoOfStudents                                              230
grade_type                                       letter_group
Name: 140365, dtype: object
qualification                                  AdvancedHigher
year                                                     2021
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                    all
grade                                                    A-D*
NoOfStudents                                              234
grade_type                                       letter_group
Name: 159097, dtype: object
qualification                                  AdvancedHigher
year                                                     2021
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                 female
grade                                                     A-B
NoOfStudents                                              149
grade_type                                       letter_group
Name: 158604, dtype: object
qualification                                  AdvancedHigher
year                                                     2021
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                 female

qualification            Higher
year                       2014
Subject              Accounting
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                447
grade_type         letter_group
Name: 138441, dtype: object
qualification            Higher
year                       2014
Subject              Accounting
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                447
grade_type         letter_group
Name: 138440, dtype: object
qualification              Higher
year                         2014
Subject            Administration
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                 1592
grade_type           letter_group
Name: 138443, dtype: object
qualification              Higher
year                         2014
Subject            Administration
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  476
grade_type           letter_group
Name: 138442, dtype: object
qualification              Higher
year                         2014
Subject            Art and Design
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                 4664
grade_type           letter_group
Name: 138445, dtype: object
qualification              Higher
year                         2014
Subject            Art and Design
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  955
grade_type           letter_group
Name: 138444, dtype: object
qualification            Higher
year                       2014
Subject                 Biology
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               4503
grade_type         letter_group
Name: 138447, dtype: object
qualification            Higher
year                       2014
Subject                 Biology
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               2533
grade_type         letter_group
Name: 138446, dtype: object
qualification                 Higher
year                            2014
Subject            Biology (Revised)
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                      61
grade_type              letter_group
Name: 138449, dtype: object
qualification                 Higher
year                            2014
Subject            Biology (Revised)
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                      43
grade_type              letter_group
Name: 138448, dtype: object
qualification             Higher
year                        2014
Subject            Biotechnology
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                  12
grade_type          letter_group
Name: 138451, dtype: object
qualification             Higher
year                        2014
Subject            Biotechnology
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                   9
grade_type          letter_group
Name: 138450, dtype: object
qualification                     Higher
year                                2014
Subject            Building Construction
NumberOfCentres                      NaN
gender                            female
grade                                A-C
NoOfStudents                         NaN
grade_type                  letter_group
Name: 138453, dtype: object
qualification                     Higher
year                                2014
Subject            Building Construction
NumberOfCentres                      NaN
gender                              male
grade                                A-C
NoOfStudents                           2
grade_type                  letter_group
Name: 138452, dtype: object
qualification                   Higher
year                              2014
Subject            Business Management
NumberOfCentres                    NaN
gender                          female
grade                              A-C
NoOfStudents                      3675
grade_type                letter_group
Name: 138455, dtype: object
qualification                   Higher
year                              2014
Subject            Business Management
NumberOfCentres                    NaN
gender                            male
grade                              A-C
NoOfStudents                      2293
grade_type                letter_group
Name: 138454, dtype: object
qualification            Higher
year                       2014
Subject                    Care
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                608
grade_type         letter_group
Name: 138457, dtype: object
qualification            Higher
year                       2014
Subject                    Care
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 45
grade_type         letter_group
Name: 138456, dtype: object
qualification             Higher
year                        2014
Subject            Care Practice
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                 113
grade_type          letter_group
Name: 138459, dtype: object
qualification             Higher
year                        2014
Subject            Care Practice
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                   5
grade_type          letter_group
Name: 138458, dtype: object
qualification            Higher
year                       2014
Subject               Chemistry
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               4072
grade_type         letter_group
Name: 138461, dtype: object
qualification            Higher
year                       2014
Subject               Chemistry
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               4072
grade_type         letter_group
Name: 138460, dtype: object
qualification                   Higher
year                              2014
Subject            Chemistry (Revised)
NumberOfCentres                    NaN
gender                          female
grade                              A-C
NoOfStudents                       273
grade_type                letter_group
Name: 138463, dtype: object
qualification                   Higher
year                              2014
Subject            Chemistry (Revised)
NumberOfCentres                    NaN
gender                            male
grade                              A-C
NoOfStudents                       296
grade_type                letter_group
Name: 138462, dtype: object
qualification                 Higher
year                            2014
Subject            Chinese Languages
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                      59
grade_type              letter_group
Name: 138465, dtype: object
qualification                 Higher
year                            2014
Subject            Chinese Languages
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                      38
grade_type              letter_group
Name: 138464, dtype: object
qualification               Higher
year                          2014
Subject            Classical Greek
NumberOfCentres                NaN
gender                      female
grade                          A-C
NoOfStudents                     7
grade_type            letter_group
Name: 138467, dtype: object
qualification               Higher
year                          2014
Subject            Classical Greek
NumberOfCentres                NaN
gender                        male
grade                          A-C
NoOfStudents                     6
grade_type            letter_group
Name: 138466, dtype: object
qualification                 Higher
year                            2014
Subject            Classical Studies
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                     217
grade_type              letter_group
Name: 138469, dtype: object
qualification                 Higher
year                            2014
Subject            Classical Studies
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                     116
grade_type              letter_group
Name: 138468, dtype: object
qualification            Higher
year                       2014
Subject               Computing
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                653
grade_type         letter_group
Name: 138471, dtype: object
qualification            Higher
year                       2014
Subject               Computing
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               2502
grade_type         letter_group
Name: 138470, dtype: object
qualification              Higher
year                         2014
Subject            Dance Practice
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                  350
grade_type           letter_group
Name: 138473, dtype: object
qualification              Higher
year                         2014
Subject            Dance Practice
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                   15
grade_type           letter_group
Name: 138472, dtype: object
qualification            Higher
year                       2014
Subject                   Drama
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               1902
grade_type         letter_group
Name: 138475, dtype: object
qualification            Higher
year                       2014
Subject                   Drama
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                654
grade_type         letter_group
Name: 138474, dtype: object
qualification                             Higher
year                                        2014
Subject            Early Education and Childcare
NumberOfCentres                              NaN
gender                                    female
grade                                        A-C
NoOfStudents                                 544
grade_type                          letter_group
Name: 138477, dtype: object
qualification                             Higher
year                                        2014
Subject            Early Education and Childcare
NumberOfCentres                              NaN
gender                                      male
grade                                        A-C
NoOfStudents                                  18
grade_type                          letter_group
Name: 138476, dtype: object
qualification            Higher
year                       2014
Subject               Economics
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                194
grade_type         letter_group
Name: 138479, dtype: object
qualification            Higher
year                       2014
Subject               Economics
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                330
grade_type         letter_group
Name: 138478, dtype: object
qualification            Higher
year                       2014
Subject                 English
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents              14351
grade_type         letter_group
Name: 138481, dtype: object
qualification            Higher
year                       2014
Subject                 English
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               9713
grade_type         letter_group
Name: 138480, dtype: object
qualification                                       Higher
year                                                  2014
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                              female
grade                                                  A-C
NoOfStudents                                           348
grade_type                                    letter_group
Name: 138483, dtype: object
qualification                                       Higher
year                                                  2014
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                                male
grade                                                  A-C
NoOfStudents                                           279
grade_type                                    letter_group
Name: 138482, dtype: object
qualification            Higher
year                       2014
Subject                  French
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               2753
grade_type         letter_group
Name: 138485, dtype: object
qualification            Higher
year                       2014
Subject                  French
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                803
grade_type         letter_group
Name: 138484, dtype: object
qualification                 Higher
year                            2014
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                      70
grade_type              letter_group
Name: 138487, dtype: object
qualification                 Higher
year                            2014
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                      20
grade_type              letter_group
Name: 138486, dtype: object
qualification            Higher
year                       2014
Subject               Geography
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               3557
grade_type         letter_group
Name: 138491, dtype: object
qualification            Higher
year                       2014
Subject               Geography
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               2795
grade_type         letter_group
Name: 138490, dtype: object
qualification            Higher
year                       2014
Subject                 Geology
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                 18
grade_type         letter_group
Name: 138493, dtype: object
qualification            Higher
year                       2014
Subject                 Geology
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 19
grade_type         letter_group
Name: 138492, dtype: object
qualification            Higher
year                       2014
Subject                  German
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                534
grade_type         letter_group
Name: 138495, dtype: object
qualification            Higher
year                       2014
Subject                  German
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                238
grade_type         letter_group
Name: 138494, dtype: object
qualification                     Higher
year                                2014
Subject            Graphic Communication
NumberOfCentres                      NaN
gender                            female
grade                                A-C
NoOfStudents                         987
grade_type                  letter_group
Name: 138497, dtype: object
qualification                     Higher
year                                2014
Subject            Graphic Communication
NumberOfCentres                      NaN
gender                              male
grade                                A-C
NoOfStudents                        2298
grade_type                  letter_group
Name: 138496, dtype: object
qualification            Higher
year                       2014
Subject                Gàidhlig
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                 81
grade_type         letter_group
Name: 138489, dtype: object
qualification            Higher
year                       2014
Subject                Gàidhlig
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 28
grade_type         letter_group
Name: 138488, dtype: object
qualification            Higher
year                       2014
Subject                 History
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               5555
grade_type         letter_group
Name: 138499, dtype: object
qualification            Higher
year                       2014
Subject                 History
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               3839
grade_type         letter_group
Name: 138498, dtype: object
qualification                                              Higher
year                                                         2014
Subject            Home Economics: Fashion and Textile Technology
NumberOfCentres                                               NaN
gender                                                     female
grade                                                         A-C
NoOfStudents                                                  130
grade_type                                           letter_group
Name: 138501, dtype: object
qualification                                              Higher
year                                                         2014
Subject            Home Economics: Fashion and Textile Technology
NumberOfCentres                                               NaN
gender                                                       male
grade                                                         A-C
NoOfStudents                                                  NaN
grade_type                                           letter_group
Name: 138500, dtype: object
qualification                                          Higher
year                                                     2014

Name: 138781, dtype: object
qualification               Higher
year                          2015
Subject            Classical Greek
NumberOfCentres                NaN
gender                        male
grade                          A-C
NoOfStudents                   NaN
grade_type            letter_group
Name: 138780, dtype: object
qualification                 Higher
year                            2015
Subject            Classical Studies
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                     169
grade_type              letter_group
Name: 138783, dtype: object
qualification                 Higher
year                            2015
Subject            Classical Studies
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                     106
grade_type              letter_group
Name: 138782, dtype: object
qualification            Higher
year                       2015
Subject               Computing
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                412
grade_type         letter_group
Name: 138785, dtype: object
qualification            Higher
year                       2015
Subject               Computing
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               1632
grade_type         letter_group
Name: 138784, dtype: object
qualification              Higher
year                         2015
Subject            Dance Practice
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   95
grade_type           letter_group
Name: 138787, dtype: object
qualification              Higher
year                         2015
Subject            Dance Practice
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                    5
grade_type           letter_group
Name: 138786, dtype: object
qualification            Higher
year                       2015
Subject                   Drama
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                449
grade_type         letter_group
Name: 138789, dtype: object
qualification            Higher
year                       2015
Subject                   Drama
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                178
grade_type         letter_group
Name: 138788, dtype: object
qualification                             Higher
year                                        2015
Subject            Early Education and Childcare
NumberOfCentres                              NaN
gender                                    female
grade                                        A-C
NoOfStudents                                 372
grade_type                          letter_group
Name: 138791, dtype: object
qualification                             Higher
year                                        2015
Subject            Early Education and Childcare
NumberOfCentres                              NaN
gender                                      male
grade                                        A-C
NoOfStudents                                   9
grade_type                          letter_group
Name: 138790, dtype: object
qualification            Higher
year                       2015
Subject               Economics
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                133
grade_type         letter_group
Name: 138793, dtype: object
qualification            Higher
year                       2015
Subject               Economics
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                244
grade_type         letter_group
Name: 138792, dtype: object
qualification            Higher
year                       2015
Subject                 English
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               6651
grade_type         letter_group
Name: 138795, dtype: object
qualification            Higher
year                       2015
Subject                 English
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               4320
grade_type         letter_group
Name: 138794, dtype: object
qualification                                       Higher
year                                                  2015
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                              female
grade                                                  A-C
NoOfStudents                                           207
grade_type                                    letter_group
Name: 138797, dtype: object
qualification                                       Higher
year                                                  2015
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                                male
grade                                                  A-C
NoOfStudents                                           188
grade_type                                    letter_group
Name: 138796, dtype: object
qualification            Higher
year                       2015
Subject                  French
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               1146
grade_type         letter_group
Name: 138799, dtype: object
qualification            Higher
year                       2015
Subject                  French
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                402
grade_type         letter_group
Name: 138798, dtype: object
qualification                 Higher
year                            2015
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                      36
grade_type              letter_group
Name: 138801, dtype: object
qualification                 Higher
year                            2015
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                      15
grade_type              letter_group
Name: 138800, dtype: object
qualification            Higher
year                       2015
Subject               Geography
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               1840
grade_type         letter_group
Name: 138805, dtype: object
qualification            Higher
year                       2015
Subject               Geography
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               1510
grade_type         letter_group
Name: 138804, dtype: object
qualification            Higher
year                       2015
Subject                 Geology
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                 10
grade_type         letter_group
Name: 138807, dtype: object
qualification            Higher
year                       2015
Subject                 Geology
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 21
grade_type         letter_group
Name: 138806, dtype: object
qualification            Higher
year                       2015
Subject                  German
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                250
grade_type         letter_group
Name: 138809, dtype: object
qualification            Higher
year                       2015
Subject                  German
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                119
grade_type         letter_group
Name: 138808, dtype: object
qualification                     Higher
year                                2015
Subject            Graphic Communication
NumberOfCentres                      NaN
gender                            female
grade                                A-C
NoOfStudents                         168
grade_type                  letter_group
Name: 138811, dtype: object
qualification                     Higher
year                                2015
Subject            Graphic Communication
NumberOfCentres                      NaN
gender                              male
grade                                A-C
NoOfStudents                         397
grade_type                  letter_group
Name: 138810, dtype: object
qualification            Higher
year                       2015
Subject                Gàidhlig
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                 20
grade_type         letter_group
Name: 138803, dtype: object
qualification            Higher
year                       2015
Subject                Gàidhlig
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 20
grade_type         letter_group
Name: 138802, dtype: object
qualification            Higher
year                       2015
Subject                 History
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               2074
grade_type         letter_group
Name: 138813, dtype: object
qualification            Higher
year                       2015
Subject                 History
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               1409
grade_type         letter_group
Name: 138812, dtype: object
qualification                                              Higher
year                                                         2015
Subject            Home Economics: Fashion and Textile Technology
NumberOfCentres                                               NaN
gender                                                     female
grade                                                         A-C
NoOfStudents                                                   21
grade_type                                           letter_group
Name: 138815, dtype: object
qualification                                              Higher
year                                                         2015
Subject            Home Economics: Fashion and Textile Technology
NumberOfCentres                                               NaN
gender                                                       male
grade                                                         A-C
NoOfStudents                                                  NaN
grade_type                                           letter_group
Name: 138814, dtype: object
qualification                                          Higher
year                                                     2015
Subject            Home Economics: Health and Food Technology
NumberOfCentres                                           NaN
gender                                                 female
grade                                                     A-C
NoOfStudents                                              221
grade_type                                       letter_group
Name: 138817, dtype: object
qualification                                          Higher
year                                                     2015
Subject            Home Economics: Health and Food Technology
NumberOfCentres                                           NaN
gender                                                   male
grade                                                     A-C
NoOfStudents                                               35
grade_type                                       letter_group
Name: 138816, dtype: object
qualification                                                 Higher
year                                                            2015
Subject            Home Economics: Lifestyle and Consumer Technology
NumberOfCentres                                                  NaN
gender                                                        female
grade                                                            A-C
NoOfStudents                                                      52
grade_type                                              letter_group
Name: 138819, dtype: object
qualification                                                 Higher
year                                                            2015
Subject            Home Economics: Lifestyle and Consumer Technology
NumberOfCentres                                                  NaN
gender                                                          male
grade                                                            A-C
NoOfStudents                                                       7
grade_type                                              letter_group
Name: 138818, dtype: object
qualification                                  Higher
year                                             2015
Subject            Hospitality - Professional Cookery
NumberOfCentres                                   NaN
gender                                         female
grade                                             A-C
NoOfStudents                                       12
grade_type                               letter_group
Name: 138821, dtype: object
qualification                                  Higher
year                                             2015
Subject            Hospitality - Professional Cookery
NumberOfCentres                                   NaN
gender                                           male
grade                                             A-C
NoOfStudents                                      NaN
grade_type                               letter_group
Name: 138820, dtype: object
qualification             Higher
year                        2015
Subject            Human Biology
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                1333
grade_type          letter_group
Name: 138823, dtype: object
qualification             Higher
year                        2015
Subject            Human Biology
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                 639
grade_type          letter_group
Name: 138822, dtype: object
qualification                       Higher
year                                  2015
Subject            Human Biology (Revised)
NumberOfCentres                        NaN
gender                              female
grade                                  A-C
NoOfStudents                            86
grade_type                    letter_group
Name: 138825, dtype: object
qualification                       Higher
year                                  2015
Subject            Human Biology (Revised)
NumberOfCentres                        NaN
gender                                male
grade                                  A-C
NoOfStudents                            43
grade_type                    letter_group
Name: 138824, dtype: object
qualification                   Higher
year                              2015
Subject            Information Systems
NumberOfCentres                    NaN
gender                          female
grade                              A-C
NoOfStudents                       105
grade_type                letter_group
Name: 138827, dtype: object
qualification                   Higher
year                              2015
Subject            Information Systems
NumberOfCentres                    NaN
gender                            male
grade                              A-C
NoOfStudents                       260
grade_type                letter_group
Name: 138826, dtype: object
qualification            Higher
year                       2015
Subject                 Italian
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                 72
grade_type         letter_group
Name: 138829, dtype: object
qualification            Higher
year                       2015
Subject                 Italian
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 31
grade_type         letter_group
Name: 138828, dtype: object
qualification            Higher
year                       2015
Subject                   Latin
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                 53
grade_type         letter_group
Name: 138831, dtype: object
qualification            Higher
year                       2015
Subject                   Latin
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 35
grade_type         letter_group
Name: 138830, dtype: object
qualification                                Higher
year                                           2015
Subject            Managing Environmental Resources
NumberOfCentres                                 NaN
gender                                       female
grade                                           A-C
NoOfStudents                                     59
grade_type                             letter_group
Name: 138833, dtype: object
qualification                                Higher
year                                           2015
Subject            Managing Environmental Resources
NumberOfCentres                                 NaN
gender                                         male
grade                                           A-C
NoOfStudents                                     42
grade_type                             letter_group
Name: 138832, dtype: object
qualification            Higher
year                       2015
Subject             Mathematics
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               3775
grade_type         letter_group
Name: 138835, dtype: object
qualification            Higher
year                       2015
Subject             Mathematics
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               4142
grade_type         letter_group
Name: 138834, dtype: object
qualification             Higher
year                        2015
Subject            Media Studies
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                 241
grade_type          letter_group
Name: 138837, dtype: object
qualification             Higher
year                        2015
Subject            Media Studies
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                 136
grade_type          letter_group
Name: 138836, dtype: object
qualification                  Higher
year                             2015

Name: 139209, dtype: object
qualification            Higher
year                       2016
Subject                   Latin
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                117
grade_type         letter_group
Name: 139208, dtype: object
qualification            Higher
year                       2016
Subject             Mathematics
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               6794
grade_type         letter_group
Name: 139211, dtype: object
qualification            Higher
year                       2016
Subject             Mathematics
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               7163
grade_type         letter_group
Name: 139210, dtype: object
qualification            Higher
year                       2016
Subject                   Media
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                441
grade_type         letter_group
Name: 139213, dtype: object
qualification            Higher
year                       2016
Subject                   Media
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                279
grade_type         letter_group
Name: 139212, dtype: object
qualification              Higher
year                         2016
Subject            Modern Studies
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                 4840
grade_type           letter_group
Name: 139215, dtype: object
qualification              Higher
year                         2016
Subject            Modern Studies
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                 2478
grade_type           letter_group
Name: 139214, dtype: object
qualification            Higher
year                       2016
Subject                   Music
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               2935
grade_type         letter_group
Name: 139217, dtype: object
qualification            Higher
year                       2016
Subject                   Music
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               2018
grade_type         letter_group
Name: 139216, dtype: object
qualification                Higher
year                           2016
Subject            Music Technology
NumberOfCentres                 NaN
gender                       female
grade                           A-C
NoOfStudents                    128
grade_type             letter_group
Name: 139219, dtype: object
qualification                Higher
year                           2016
Subject            Music Technology
NumberOfCentres                 NaN
gender                         male
grade                           A-C
NoOfStudents                    304
grade_type             letter_group
Name: 139218, dtype: object
qualification            Higher
year                       2016
Subject              Philosophy
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                442
grade_type         letter_group
Name: 139221, dtype: object
qualification            Higher
year                       2016
Subject              Philosophy
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                263
grade_type         letter_group
Name: 139220, dtype: object
qualification            Higher
year                       2016
Subject             Photography
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               1370
grade_type         letter_group
Name: 139223, dtype: object
qualification            Higher
year                       2016
Subject             Photography
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                451
grade_type         letter_group
Name: 139222, dtype: object
qualification                  Higher
year                             2016
Subject            Physical Education
NumberOfCentres                   NaN
gender                         female
grade                             A-C
NoOfStudents                     2770
grade_type               letter_group
Name: 139225, dtype: object
qualification                  Higher
year                             2016
Subject            Physical Education
NumberOfCentres                   NaN
gender                           male
grade                             A-C
NoOfStudents                     5966
grade_type               letter_group
Name: 139224, dtype: object
qualification            Higher
year                       2016
Subject                 Physics
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               1997
grade_type         letter_group
Name: 139227, dtype: object
qualification            Higher
year                       2016
Subject                 Physics
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               4798
grade_type         letter_group
Name: 139226, dtype: object
qualification            Higher
year                       2016
Subject                Politics
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                355
grade_type         letter_group
Name: 139229, dtype: object
qualification            Higher
year                       2016
Subject                Politics
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                269
grade_type         letter_group
Name: 139228, dtype: object
qualification            Higher
year                       2016
Subject              Psychology
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               1855
grade_type         letter_group
Name: 139231, dtype: object
qualification            Higher
year                       2016
Subject              Psychology
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                525
grade_type         letter_group
Name: 139230, dtype: object
qualification                                          Higher
year                                                     2016
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                 female
grade                                                     A-C
NoOfStudents                                             2086
grade_type                                       letter_group
Name: 139233, dtype: object
qualification                                          Higher
year                                                     2016
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                   male
grade                                                     A-C
NoOfStudents                                              789
grade_type                                       letter_group
Name: 139232, dtype: object
qualification            Higher
year                       2016
Subject               Sociology
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                427
grade_type         letter_group
Name: 139235, dtype: object
qualification            Higher
year                       2016
Subject               Sociology
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                174
grade_type         letter_group
Name: 139234, dtype: object
qualification            Higher
year                       2016
Subject                 Spanish
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               1708
grade_type         letter_group
Name: 139237, dtype: object
qualification            Higher
year                       2016
Subject                 Spanish
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                604
grade_type         letter_group
Name: 139236, dtype: object
qualification            Higher
year                       2016
Subject                    Urdu
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                 53
grade_type         letter_group
Name: 139239, dtype: object
qualification            Higher
year                       2016
Subject                    Urdu
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 33
grade_type         letter_group
Name: 139238, dtype: object
qualification            Higher
year                       2017
Subject              Accounting
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                469
grade_type         letter_group
Name: 139309, dtype: object
qualification            Higher
year                       2017
Subject              Accounting
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                573
grade_type         letter_group
Name: 139308, dtype: object
qualification                     Higher
year                                2017
Subject            Administration and IT
NumberOfCentres                      NaN
gender                            female
grade                                A-C
NoOfStudents                        2051
grade_type                  letter_group
Name: 139311, dtype: object
qualification                     Higher
year                                2017
Subject            Administration and IT
NumberOfCentres                      NaN
gender                              male
grade                                A-C
NoOfStudents                        1048
grade_type                  letter_group
Name: 139310, dtype: object
qualification              Higher
year                         2017
Subject            Art and Design
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                 3740
grade_type           letter_group
Name: 139313, dtype: object
qualification              Higher
year                         2017
Subject            Art and Design
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  785
grade_type           letter_group
Name: 139312, dtype: object
qualification            Higher
year                       2017
Subject                 Biology
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               3545
grade_type         letter_group
Name: 139315, dtype: object
qualification            Higher
year                       2017
Subject                 Biology
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               1935
grade_type         letter_group
Name: 139314, dtype: object
qualification                   Higher
year                              2017
Subject            Business Management
NumberOfCentres                    NaN
gender                          female
grade                              A-C
NoOfStudents                      3911
grade_type                letter_group
Name: 139317, dtype: object
qualification                   Higher
year                              2017
Subject            Business Management
NumberOfCentres                    NaN
gender                            male
grade                              A-C
NoOfStudents                      3076
grade_type                letter_group
Name: 139316, dtype: object
qualification            Higher
year                       2017
Subject                    Care
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                760
grade_type         letter_group
Name: 139319, dtype: object
qualification            Higher
year                       2017
Subject                    Care
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 65
grade_type         letter_group
Name: 139318, dtype: object
qualification            Higher
year                       2017
Subject               Chemistry
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               4032
grade_type         letter_group
Name: 139321, dtype: object
qualification            Higher
year                       2017
Subject               Chemistry
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               3724
grade_type         letter_group
Name: 139320, dtype: object
qualification                         Higher
year                                    2017
Subject            Childcare and Development
NumberOfCentres                          NaN
gender                                female
grade                                    A-C
NoOfStudents                             528
grade_type                      letter_group
Name: 139323, dtype: object
qualification                         Higher
year                                    2017
Subject            Childcare and Development
NumberOfCentres                          NaN
gender                                  male
grade                                    A-C
NoOfStudents                              24
grade_type                      letter_group
Name: 139322, dtype: object
qualification                 Higher
year                            2017
Subject            Chinese Languages
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                      73
grade_type              letter_group
Name: 139325, dtype: object
qualification                 Higher
year                            2017
Subject            Chinese Languages
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                      54
grade_type              letter_group
Name: 139324, dtype: object
qualification                 Higher
year                            2017
Subject            Classical Studies
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                     242
grade_type              letter_group
Name: 139327, dtype: object
qualification                 Higher
year                            2017
Subject            Classical Studies
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                     100
grade_type              letter_group
Name: 139326, dtype: object
qualification                 Higher
year                            2017
Subject            Computing Science
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                     463
grade_type              letter_group
Name: 139329, dtype: object
qualification                 Higher
year                            2017
Subject            Computing Science
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                    2435
grade_type              letter_group
Name: 139328, dtype: object
qualification            Higher
year                       2017
Subject                   Dance
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                393
grade_type         letter_group
Name: 139331, dtype: object
qualification            Higher
year                       2017
Subject                   Dance
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 12
grade_type         letter_group
Name: 139330, dtype: object
qualification                      Higher
year                                 2017
Subject            Design and Manufacture
NumberOfCentres                       NaN
gender                             female
grade                                 A-C
NoOfStudents                          689
grade_type                   letter_group
Name: 139333, dtype: object
qualification                      Higher
year                                 2017
Subject            Design and Manufacture
NumberOfCentres                       NaN
gender                               male
grade                                 A-C
NoOfStudents                         1248
grade_type                   letter_group
Name: 139332, dtype: object
qualification            Higher
year                       2017
Subject                   Drama
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               1739
grade_type         letter_group
Name: 139335, dtype: object
qualification            Higher
year                       2017
Subject                   Drama
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                610
grade_type         letter_group
Name: 139334, dtype: object
qualification            Higher
year                       2017
Subject               Economics
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                193
grade_type         letter_group
Name: 139337, dtype: object
qualification            Higher
year                       2017
Subject               Economics
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                331
grade_type         letter_group
Name: 139336, dtype: object
qualification                   Higher
year                              2017
Subject            Engineering Science
NumberOfCentres                    NaN
gender                          female
grade                              A-C
NoOfStudents                        65
grade_type                letter_group
Name: 139339, dtype: object
qualification                   Higher
year                              2017
Subject            Engineering Science
NumberOfCentres                    NaN
gender                            male
grade                              A-C
NoOfStudents                       735
grade_type                letter_group
Name: 139338, dtype: object
qualification            Higher
year                       2017
Subject                 English
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents              16488
grade_type         letter_group
Name: 139341, dtype: object
qualification            Higher
year                       2017
Subject                 English

Name: 139496, dtype: object
qualification                   Higher
year                              2018
Subject            Engineering Science
NumberOfCentres                    NaN
gender                          female
grade                              A-C
NoOfStudents                        77
grade_type                letter_group
Name: 139499, dtype: object
qualification                   Higher
year                              2018
Subject            Engineering Science
NumberOfCentres                    NaN
gender                            male
grade                              A-C
NoOfStudents                       630
grade_type                letter_group
Name: 139498, dtype: object
qualification            Higher
year                       2018
Subject                 English
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents              16998
grade_type         letter_group
Name: 139501, dtype: object
qualification            Higher
year                       2018
Subject                 English
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents              10637
grade_type         letter_group
Name: 139500, dtype: object
qualification                                       Higher
year                                                  2018
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                              female
grade                                                  A-C
NoOfStudents                                           367
grade_type                                    letter_group
Name: 139503, dtype: object
qualification                                       Higher
year                                                  2018
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                                male
grade                                                  A-C
NoOfStudents                                           296
grade_type                                    letter_group
Name: 139502, dtype: object
qualification                     Higher
year                                2018
Subject            Environmental Science
NumberOfCentres                      NaN
gender                            female
grade                                A-C
NoOfStudents                         140
grade_type                  letter_group
Name: 139505, dtype: object
qualification                     Higher
year                                2018
Subject            Environmental Science
NumberOfCentres                      NaN
gender                              male
grade                                A-C
NoOfStudents                         135
grade_type                  letter_group
Name: 139504, dtype: object
qualification                              Higher
year                                         2018
Subject            Fashion and Textile Technology
NumberOfCentres                               NaN
gender                                     female
grade                                         A-C
NoOfStudents                                  298
grade_type                           letter_group
Name: 139507, dtype: object
qualification                              Higher
year                                         2018
Subject            Fashion and Textile Technology
NumberOfCentres                               NaN
gender                                       male
grade                                         A-C
NoOfStudents                                    9
grade_type                           letter_group
Name: 139506, dtype: object
qualification            Higher
year                       2018
Subject                  French
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               2461
grade_type         letter_group
Name: 139509, dtype: object
qualification            Higher
year                       2018
Subject                  French
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                855
grade_type         letter_group
Name: 139508, dtype: object
qualification                 Higher
year                            2018
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                      49
grade_type              letter_group
Name: 139511, dtype: object
qualification                 Higher
year                            2018
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                      13
grade_type              letter_group
Name: 139510, dtype: object
qualification            Higher
year                       2018
Subject               Geography
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               3048
grade_type         letter_group
Name: 139515, dtype: object
qualification            Higher
year                       2018
Subject               Geography
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               2360
grade_type         letter_group
Name: 139514, dtype: object
qualification            Higher
year                       2018
Subject                  German
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                478
grade_type         letter_group
Name: 139517, dtype: object
qualification            Higher
year                       2018
Subject                  German
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                249
grade_type         letter_group
Name: 139516, dtype: object
qualification                     Higher
year                                2018
Subject            Graphic Communication
NumberOfCentres                      NaN
gender                            female
grade                                A-C
NoOfStudents                        1076
grade_type                  letter_group
Name: 139519, dtype: object
qualification                     Higher
year                                2018
Subject            Graphic Communication
NumberOfCentres                      NaN
gender                              male
grade                                A-C
NoOfStudents                        2053
grade_type                  letter_group
Name: 139518, dtype: object
qualification            Higher
year                       2018
Subject                Gàidhlig
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                 79
grade_type         letter_group
Name: 139513, dtype: object
qualification            Higher
year                       2018
Subject                Gàidhlig
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 39
grade_type         letter_group
Name: 139512, dtype: object
qualification                          Higher
year                                     2018
Subject            Health and Food Technology
NumberOfCentres                           NaN
gender                                 female
grade                                     A-C
NoOfStudents                              735
grade_type                       letter_group
Name: 139521, dtype: object
qualification                          Higher
year                                     2018
Subject            Health and Food Technology
NumberOfCentres                           NaN
gender                                   male
grade                                     A-C
NoOfStudents                              146
grade_type                       letter_group
Name: 139520, dtype: object
qualification            Higher
year                       2018
Subject                 History
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               5341
grade_type         letter_group
Name: 139523, dtype: object
qualification            Higher
year                       2018
Subject                 History
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               3173
grade_type         letter_group
Name: 139522, dtype: object
qualification             Higher
year                        2018
Subject            Human Biology
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                2993
grade_type          letter_group
Name: 139525, dtype: object
qualification             Higher
year                        2018
Subject            Human Biology
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                1171
grade_type          letter_group
Name: 139524, dtype: object
qualification            Higher
year                       2018
Subject                 Italian
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                165
grade_type         letter_group
Name: 139527, dtype: object
qualification            Higher
year                       2018
Subject                 Italian
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 66
grade_type         letter_group
Name: 139526, dtype: object
qualification            Higher
year                       2018
Subject                   Latin
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                143
grade_type         letter_group
Name: 139529, dtype: object
qualification            Higher
year                       2018
Subject                   Latin
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 73
grade_type         letter_group
Name: 139528, dtype: object
qualification            Higher
year                       2018
Subject             Mathematics
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               6931
grade_type         letter_group
Name: 139531, dtype: object
qualification            Higher
year                       2018
Subject             Mathematics
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               7119
grade_type         letter_group
Name: 139530, dtype: object
qualification            Higher
year                       2018
Subject                   Media
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                430
grade_type         letter_group
Name: 139533, dtype: object
qualification            Higher
year                       2018
Subject                   Media
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                279
grade_type         letter_group
Name: 139532, dtype: object
qualification              Higher
year                         2018
Subject            Modern Studies
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                 4703
grade_type           letter_group
Name: 139535, dtype: object
qualification              Higher
year                         2018
Subject            Modern Studies
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                 2452
grade_type           letter_group
Name: 139534, dtype: object
qualification            Higher
year                       2018
Subject                   Music
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               2916
grade_type         letter_group
Name: 139537, dtype: object
qualification            Higher
year                       2018
Subject                   Music
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               1903
grade_type         letter_group
Name: 139536, dtype: object
qualification                Higher
year                           2018
Subject            Music Technology
NumberOfCentres                 NaN
gender                       female
grade                           A-C
NoOfStudents                    165
grade_type             letter_group
Name: 139539, dtype: object
qualification                Higher
year                           2018
Subject            Music Technology
NumberOfCentres                 NaN
gender                         male
grade                           A-C
NoOfStudents                    400
grade_type             letter_group
Name: 139538, dtype: object
qualification            Higher
year                       2018
Subject              Philosophy
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                300
grade_type         letter_group
Name: 139541, dtype: object
qualification            Higher
year                       2018
Subject              Philosophy
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                173
grade_type         letter_group
Name: 139540, dtype: object
qualification            Higher
year                       2018
Subject             Photography
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               1441
grade_type         letter_group
Name: 139543, dtype: object
qualification            Higher
year                       2018
Subject             Photography
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                582
grade_type         letter_group
Name: 139542, dtype: object
qualification                  Higher
year                             2018
Subject            Physical Education
NumberOfCentres                   NaN
gender                         female
grade                             A-C
NoOfStudents                     3029
grade_type               letter_group
Name: 139545, dtype: object
qualification                  Higher
year                             2018
Subject            Physical Education
NumberOfCentres                   NaN
gender                           male
grade                             A-C
NoOfStudents                     5746
grade_type               letter_group
Name: 139544, dtype: object
qualification            Higher
year                       2018
Subject                 Physics
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               1901
grade_type         letter_group
Name: 139547, dtype: object
qualification            Higher
year                       2018
Subject                 Physics
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               4412
grade_type         letter_group
Name: 139546, dtype: object
qualification            Higher
year                       2018
Subject                Politics
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                479
grade_type         letter_group
Name: 139549, dtype: object
qualification            Higher
year                       2018
Subject                Politics
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                396
grade_type         letter_group
Name: 139548, dtype: object
qualification            Higher
year                       2018
Subject              Psychology
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               1564
grade_type         letter_group
Name: 139551, dtype: object
qualification            Higher
year                       2018
Subject              Psychology
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                444
grade_type         letter_group
Name: 139550, dtype: object
qualification                                          Higher
year                                                     2018
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                 female
grade                                                     A-C
NoOfStudents                                             2029
grade_type                                       letter_group
Name: 139553, dtype: object
qualification                                          Higher
year                                                     2018
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                   male
grade                                                     A-C
NoOfStudents                                              652
grade_type                                       letter_group
Name: 139552, dtype: object
qualification            Higher
year                       2018
Subject               Sociology
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                448
grade_type         letter_group
Name: 139555, dtype: object
qualification            Higher
year                       2018
Subject               Sociology
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                205
grade_type         letter_group
Name: 139554, dtype: object
qualification            Higher
year                       2018
Subject                 Spanish
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               1737
grade_type         letter_group
Name: 139557, dtype: object
qualification            Higher
year                       2018
Subject                 Spanish
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                603
grade_type         letter_group
Name: 139556, dtype: object
qualification            Higher
year                       2018
Subject                    Urdu
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                 62
grade_type         letter_group
Name: 139559, dtype: object
qualification            Higher
year                       2018
Subject                    Urdu
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 37
grade_type         letter_group
Name: 139558, dtype: object
qualification             Higher
year                        2019
Subject               Accounting
NumberOfCentres              NaN
gender             NotApplicable
grade                        A-C
NoOfStudents                 NaN

Name: 139803, dtype: object
qualification                          Higher
year                                     2019
Subject            Health and Food Technology
NumberOfCentres                           NaN
gender                               NotKnown
grade                                     A-C
NoOfStudents                              NaN
grade_type                       letter_group
Name: 139802, dtype: object
qualification                          Higher
year                                     2019
Subject            Health and Food Technology
NumberOfCentres                           NaN
gender                                 female
grade                                     A-C
NoOfStudents                              625
grade_type                       letter_group
Name: 139801, dtype: object
qualification                          Higher
year                                     2019
Subject            Health and Food Technology
NumberOfCentres                           NaN
gender                                   male
grade                                     A-C
NoOfStudents                               92
grade_type                       letter_group
Name: 139800, dtype: object
qualification             Higher
year                        2019
Subject                  History
NumberOfCentres              NaN
gender             NotApplicable
grade                        A-C
NoOfStudents                 NaN
grade_type          letter_group
Name: 139807, dtype: object
qualification            Higher
year                       2019
Subject                 History
NumberOfCentres             NaN
gender                 NotKnown
grade                       A-C
NoOfStudents                NaN
grade_type         letter_group
Name: 139806, dtype: object
qualification            Higher
year                       2019
Subject                 History
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               4782
grade_type         letter_group
Name: 139805, dtype: object
qualification            Higher
year                       2019
Subject                 History
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               2550
grade_type         letter_group
Name: 139804, dtype: object
qualification             Higher
year                        2019
Subject            Human Biology
NumberOfCentres              NaN
gender             NotApplicable
grade                        A-C
NoOfStudents                 NaN
grade_type          letter_group
Name: 139811, dtype: object
qualification             Higher
year                        2019
Subject            Human Biology
NumberOfCentres              NaN
gender                  NotKnown
grade                        A-C
NoOfStudents                 NaN
grade_type          letter_group
Name: 139810, dtype: object
qualification             Higher
year                        2019
Subject            Human Biology
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                3155
grade_type          letter_group
Name: 139809, dtype: object
qualification             Higher
year                        2019
Subject            Human Biology
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                1216
grade_type          letter_group
Name: 139808, dtype: object
qualification             Higher
year                        2019
Subject                  Italian
NumberOfCentres              NaN
gender             NotApplicable
grade                        A-C
NoOfStudents                 NaN
grade_type          letter_group
Name: 139815, dtype: object
qualification            Higher
year                       2019
Subject                 Italian
NumberOfCentres             NaN
gender                 NotKnown
grade                       A-C
NoOfStudents                NaN
grade_type         letter_group
Name: 139814, dtype: object
qualification            Higher
year                       2019
Subject                 Italian
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                140
grade_type         letter_group
Name: 139813, dtype: object
qualification            Higher
year                       2019
Subject                 Italian
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 58
grade_type         letter_group
Name: 139812, dtype: object
qualification             Higher
year                        2019
Subject                    Latin
NumberOfCentres              NaN
gender             NotApplicable
grade                        A-C
NoOfStudents                 NaN
grade_type          letter_group
Name: 139819, dtype: object
qualification            Higher
year                       2019
Subject                   Latin
NumberOfCentres             NaN
gender                 NotKnown
grade                       A-C
NoOfStudents                NaN
grade_type         letter_group
Name: 139818, dtype: object
qualification            Higher
year                       2019
Subject                   Latin
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                135
grade_type         letter_group
Name: 139817, dtype: object
qualification            Higher
year                       2019
Subject                   Latin
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 98
grade_type         letter_group
Name: 139816, dtype: object
qualification             Higher
year                        2019
Subject              Mathematics
NumberOfCentres              NaN
gender             NotApplicable
grade                        A-C
NoOfStudents                 NaN
grade_type          letter_group
Name: 139823, dtype: object
qualification            Higher
year                       2019
Subject             Mathematics
NumberOfCentres             NaN
gender                 NotKnown
grade                       A-C
NoOfStudents                NaN
grade_type         letter_group
Name: 139822, dtype: object
qualification            Higher
year                       2019
Subject             Mathematics
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               6705
grade_type         letter_group
Name: 139821, dtype: object
qualification            Higher
year                       2019
Subject             Mathematics
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               6780
grade_type         letter_group
Name: 139820, dtype: object
qualification             Higher
year                        2019
Subject                    Media
NumberOfCentres              NaN
gender             NotApplicable
grade                        A-C
NoOfStudents                 NaN
grade_type          letter_group
Name: 139827, dtype: object
qualification            Higher
year                       2019
Subject                   Media
NumberOfCentres             NaN
gender                 NotKnown
grade                       A-C
NoOfStudents                NaN
grade_type         letter_group
Name: 139826, dtype: object
qualification            Higher
year                       2019
Subject                   Media
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                436
grade_type         letter_group
Name: 139825, dtype: object
qualification            Higher
year                       2019
Subject                   Media
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                250
grade_type         letter_group
Name: 139824, dtype: object
qualification              Higher
year                         2019
Subject            Modern Studies
NumberOfCentres               NaN
gender              NotApplicable
grade                         A-C
NoOfStudents                  NaN
grade_type           letter_group
Name: 139831, dtype: object
qualification              Higher
year                         2019
Subject            Modern Studies
NumberOfCentres               NaN
gender                   NotKnown
grade                         A-C
NoOfStudents                  NaN
grade_type           letter_group
Name: 139830, dtype: object
qualification              Higher
year                         2019
Subject            Modern Studies
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                 4252
grade_type           letter_group
Name: 139829, dtype: object
qualification              Higher
year                         2019
Subject            Modern Studies
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                 2369
grade_type           letter_group
Name: 139828, dtype: object
qualification             Higher
year                        2019
Subject                    Music
NumberOfCentres              NaN
gender             NotApplicable
grade                        A-C
NoOfStudents                 NaN
grade_type          letter_group
Name: 139835, dtype: object
qualification            Higher
year                       2019
Subject                   Music
NumberOfCentres             NaN
gender                 NotKnown
grade                       A-C
NoOfStudents                NaN
grade_type         letter_group
Name: 139834, dtype: object
qualification            Higher
year                       2019
Subject                   Music
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               2733
grade_type         letter_group
Name: 139833, dtype: object
qualification            Higher
year                       2019
Subject                   Music
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               1959
grade_type         letter_group
Name: 139832, dtype: object
qualification                Higher
year                           2019
Subject            Music Technology
NumberOfCentres                 NaN
gender                NotApplicable
grade                           A-C
NoOfStudents                    NaN
grade_type             letter_group
Name: 139839, dtype: object
qualification                Higher
year                           2019
Subject            Music Technology
NumberOfCentres                 NaN
gender                     NotKnown
grade                           A-C
NoOfStudents                    NaN
grade_type             letter_group
Name: 139838, dtype: object
qualification                Higher
year                           2019
Subject            Music Technology
NumberOfCentres                 NaN
gender                       female
grade                           A-C
NoOfStudents                    200
grade_type             letter_group
Name: 139837, dtype: object
qualification                Higher
year                           2019
Subject            Music Technology
NumberOfCentres                 NaN
gender                         male
grade                           A-C
NoOfStudents                    404
grade_type             letter_group
Name: 139836, dtype: object
qualification             Higher
year                        2019
Subject               Philosophy
NumberOfCentres              NaN
gender             NotApplicable
grade                        A-C
NoOfStudents                 NaN
grade_type          letter_group
Name: 139843, dtype: object
qualification            Higher
year                       2019
Subject              Philosophy
NumberOfCentres             NaN
gender                 NotKnown
grade                       A-C
NoOfStudents                NaN
grade_type         letter_group
Name: 139842, dtype: object
qualification            Higher
year                       2019
Subject              Philosophy
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                277
grade_type         letter_group
Name: 139841, dtype: object
qualification            Higher
year                       2019
Subject              Philosophy
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                145
grade_type         letter_group
Name: 139840, dtype: object
qualification             Higher
year                        2019
Subject              Photography
NumberOfCentres              NaN
gender             NotApplicable
grade                        A-C
NoOfStudents                 NaN
grade_type          letter_group
Name: 139847, dtype: object
qualification            Higher
year                       2019
Subject             Photography
NumberOfCentres             NaN
gender                 NotKnown
grade                       A-C
NoOfStudents                NaN
grade_type         letter_group
Name: 139846, dtype: object
qualification            Higher
year                       2019
Subject             Photography
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               1365
grade_type         letter_group
Name: 139845, dtype: object
qualification            Higher
year                       2019
Subject             Photography
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                549
grade_type         letter_group
Name: 139844, dtype: object
qualification                  Higher
year                             2019
Subject            Physical Education
NumberOfCentres                   NaN
gender                  NotApplicable
grade                             A-C
NoOfStudents                      NaN
grade_type               letter_group
Name: 139851, dtype: object
qualification                  Higher
year                             2019
Subject            Physical Education
NumberOfCentres                   NaN
gender                       NotKnown
grade                             A-C
NoOfStudents                      NaN
grade_type               letter_group
Name: 139850, dtype: object
qualification                  Higher
year                             2019
Subject            Physical Education
NumberOfCentres                   NaN
gender                         female
grade                             A-C
NoOfStudents                     2874
grade_type               letter_group
Name: 139849, dtype: object
qualification                  Higher
year                             2019
Subject            Physical Education
NumberOfCentres                   NaN
gender                           male
grade                             A-C
NoOfStudents                     5834
grade_type               letter_group
Name: 139848, dtype: object
qualification             Higher
year                        2019
Subject                  Physics
NumberOfCentres              NaN
gender             NotApplicable
grade                        A-C
NoOfStudents                 NaN
grade_type          letter_group
Name: 139855, dtype: object
qualification            Higher
year                       2019
Subject                 Physics
NumberOfCentres             NaN
gender                 NotKnown
grade                       A-C
NoOfStudents                NaN
grade_type         letter_group
Name: 139854, dtype: object
qualification            Higher
year                       2019
Subject                 Physics
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               1912
grade_type         letter_group
Name: 139853, dtype: object
qualification            Higher
year                       2019
Subject                 Physics
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               4316
grade_type         letter_group
Name: 139852, dtype: object
qualification             Higher
year                        2019
Subject                 Politics
NumberOfCentres              NaN
gender             NotApplicable
grade                        A-C
NoOfStudents                 NaN
grade_type          letter_group
Name: 139859, dtype: object
qualification            Higher
year                       2019
Subject                Politics
NumberOfCentres             NaN
gender                 NotKnown
grade                       A-C
NoOfStudents                NaN
grade_type         letter_group
Name: 139858, dtype: object
qualification            Higher
year                       2019
Subject                Politics
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                598
grade_type         letter_group
Name: 139857, dtype: object
qualification            Higher
year                       2019
Subject                Politics
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                417
grade_type         letter_group
Name: 139856, dtype: object
qualification             Higher
year                        2019
Subject               Psychology
NumberOfCentres              NaN
gender             NotApplicable
grade                        A-C
NoOfStudents                 NaN
grade_type          letter_group
Name: 139863, dtype: object
qualification            Higher
year                       2019
Subject              Psychology
NumberOfCentres             NaN
gender                 NotKnown
grade                       A-C
NoOfStudents                NaN
grade_type         letter_group
Name: 139862, dtype: object
qualification            Higher
year                       2019
Subject              Psychology
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               1218
grade_type         letter_group
Name: 139861, dtype: object
qualification            Higher
year                       2019
Subject              Psychology
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                311
grade_type         letter_group
Name: 139860, dtype: object
qualification                                          Higher
year                                                     2019
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                          NotApplicable
grade                                                     A-C
NoOfStudents                                              NaN
grade_type                                       letter_group
Name: 139867, dtype: object
qualification                                          Higher
year                                                     2019
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                               NotKnown
grade                                                     A-C
NoOfStudents                                              NaN
grade_type                                       letter_group
Name: 139866, dtype: object
qualification                                          Higher
year                                                     2019
Subject            Religious, Moral and Philosophical Studies

Name: 158268, dtype: object
qualification            Higher
year                       2020
Subject               Economics
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                189
grade_type         letter_group
Name: 140028, dtype: object
qualification            Higher
year                       2020
Subject               Economics
NumberOfCentres             NaN
gender                   female
grade                       A-D
NoOfStudents                197
grade_type         letter_group
Name: 159147, dtype: object
qualification            Higher
year                       2020
Subject               Economics
NumberOfCentres             NaN
gender                     male
grade                       A-B
NoOfStudents                271
grade_type         letter_group
Name: 158267, dtype: object
qualification            Higher
year                       2020
Subject               Economics
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                332
grade_type         letter_group
Name: 140027, dtype: object
qualification            Higher
year                       2020
Subject               Economics
NumberOfCentres             NaN
gender                     male
grade                       A-D
NoOfStudents                354
grade_type         letter_group
Name: 159146, dtype: object
qualification                   Higher
year                              2020
Subject            Engineering Science
NumberOfCentres                    NaN
gender                             all
grade                              A-B
NoOfStudents                       590
grade_type                letter_group
Name: 158272, dtype: object
qualification                   Higher
year                              2020
Subject            Engineering Science
NumberOfCentres                    NaN
gender                             all
grade                              A-C
NoOfStudents                       782
grade_type                letter_group
Name: 140032, dtype: object
qualification                   Higher
year                              2020
Subject            Engineering Science
NumberOfCentres                    NaN
gender                             all
grade                              A-D
NoOfStudents                       934
grade_type                letter_group
Name: 159151, dtype: object
qualification                   Higher
year                              2020
Subject            Engineering Science
NumberOfCentres                    NaN
gender                          female
grade                              A-B
NoOfStudents                        90
grade_type                letter_group
Name: 158271, dtype: object
qualification                   Higher
year                              2020
Subject            Engineering Science
NumberOfCentres                    NaN
gender                          female
grade                              A-C
NoOfStudents                       114
grade_type                letter_group
Name: 140031, dtype: object
qualification                   Higher
year                              2020
Subject            Engineering Science
NumberOfCentres                    NaN
gender                          female
grade                              A-D
NoOfStudents                       121
grade_type                letter_group
Name: 159150, dtype: object
qualification                   Higher
year                              2020
Subject            Engineering Science
NumberOfCentres                    NaN
gender                            male
grade                              A-B
NoOfStudents                       629
grade_type                letter_group
Name: 158270, dtype: object
qualification                   Higher
year                              2020
Subject            Engineering Science
NumberOfCentres                    NaN
gender                            male
grade                              A-C
NoOfStudents                       836
grade_type                letter_group
Name: 140030, dtype: object
qualification                   Higher
year                              2020
Subject            Engineering Science
NumberOfCentres                    NaN
gender                            male
grade                              A-D
NoOfStudents                       910
grade_type                letter_group
Name: 159149, dtype: object
qualification            Higher
year                       2020
Subject                 English
NumberOfCentres             NaN
gender                      all
grade                       A-B
NoOfStudents              19078
grade_type         letter_group
Name: 158275, dtype: object
qualification            Higher
year                       2020
Subject                 English
NumberOfCentres             NaN
gender                      all
grade                       A-C
NoOfStudents              27736
grade_type         letter_group
Name: 140035, dtype: object
qualification            Higher
year                       2020
Subject                 English
NumberOfCentres             NaN
gender                      all
grade                       A-D
NoOfStudents              34052
grade_type         letter_group
Name: 159154, dtype: object
qualification            Higher
year                       2020
Subject                 English
NumberOfCentres             NaN
gender                   female
grade                       A-B
NoOfStudents              13806
grade_type         letter_group
Name: 158274, dtype: object
qualification            Higher
year                       2020
Subject                 English
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents              18973
grade_type         letter_group
Name: 140034, dtype: object
qualification            Higher
year                       2020
Subject                 English
NumberOfCentres             NaN
gender                   female
grade                       A-D
NoOfStudents              20533
grade_type         letter_group
Name: 159153, dtype: object
qualification            Higher
year                       2020
Subject                 English
NumberOfCentres             NaN
gender                     male
grade                       A-B
NoOfStudents               8208
grade_type         letter_group
Name: 158273, dtype: object
qualification            Higher
year                       2020
Subject                 English
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents              12816
grade_type         letter_group
Name: 140033, dtype: object
qualification            Higher
year                       2020
Subject                 English
NumberOfCentres             NaN
gender                     male
grade                       A-D
NoOfStudents              14556
grade_type         letter_group
Name: 159152, dtype: object
qualification                                       Higher
year                                                  2020
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                                 all
grade                                                  A-B
NoOfStudents                                           514
grade_type                                    letter_group
Name: 158278, dtype: object
qualification                                       Higher
year                                                  2020
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                                 all
grade                                                  A-C
NoOfStudents                                           679
grade_type                                    letter_group
Name: 140038, dtype: object
qualification                                       Higher
year                                                  2020
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                                 all
grade                                                  A-D
NoOfStudents                                           727
grade_type                                    letter_group
Name: 159157, dtype: object
qualification                                       Higher
year                                                  2020
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                              female
grade                                                  A-B
NoOfStudents                                           348
grade_type                                    letter_group
Name: 158277, dtype: object
qualification                                       Higher
year                                                  2020
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                              female
grade                                                  A-C
NoOfStudents                                           412
grade_type                                    letter_group
Name: 140037, dtype: object
qualification                                       Higher
year                                                  2020
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                              female
grade                                                  A-D
NoOfStudents                                           415
grade_type                                    letter_group
Name: 159156, dtype: object
qualification                                       Higher
year                                                  2020
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                                male
grade                                                  A-B
NoOfStudents                                           244
grade_type                                    letter_group
Name: 158276, dtype: object
qualification                                       Higher
year                                                  2020
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                                male
grade                                                  A-C
NoOfStudents                                           312
grade_type                                    letter_group
Name: 140036, dtype: object
qualification                                       Higher
year                                                  2020
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                                male
grade                                                  A-D
NoOfStudents                                           323
grade_type                                    letter_group
Name: 159155, dtype: object
qualification                     Higher
year                                2020
Subject            Environmental Science
NumberOfCentres                      NaN
gender                               all
grade                                A-B
NoOfStudents                         185
grade_type                  letter_group
Name: 158281, dtype: object
qualification                     Higher
year                                2020
Subject            Environmental Science
NumberOfCentres                      NaN
gender                               all
grade                                A-C
NoOfStudents                         281
grade_type                  letter_group
Name: 140041, dtype: object
qualification                     Higher
year                                2020
Subject            Environmental Science
NumberOfCentres                      NaN
gender                               all
grade                                A-D
NoOfStudents                         328
grade_type                  letter_group
Name: 159160, dtype: object
qualification                     Higher
year                                2020
Subject            Environmental Science
NumberOfCentres                      NaN
gender                            female
grade                                A-B
NoOfStudents                         140
grade_type                  letter_group
Name: 158280, dtype: object
qualification                     Higher
year                                2020
Subject            Environmental Science
NumberOfCentres                      NaN
gender                            female
grade                                A-C
NoOfStudents                         185
grade_type                  letter_group
Name: 140040, dtype: object
qualification                     Higher
year                                2020
Subject            Environmental Science
NumberOfCentres                      NaN
gender                            female
grade                                A-D
NoOfStudents                         200
grade_type                  letter_group
Name: 159159, dtype: object
qualification                     Higher
year                                2020
Subject            Environmental Science
NumberOfCentres                      NaN
gender                              male
grade                                A-B
NoOfStudents                          77
grade_type                  letter_group
Name: 158279, dtype: object
qualification                     Higher
year                                2020
Subject            Environmental Science
NumberOfCentres                      NaN
gender                              male
grade                                A-C
NoOfStudents                         137
grade_type                  letter_group
Name: 140039, dtype: object
qualification                     Higher
year                                2020
Subject            Environmental Science
NumberOfCentres                      NaN
gender                              male
grade                                A-D
NoOfStudents                         151
grade_type                  letter_group
Name: 159158, dtype: object
qualification                              Higher
year                                         2020
Subject            Fashion and Textile Technology
NumberOfCentres                               NaN
gender                                        all
grade                                         A-B
NoOfStudents                                   95
grade_type                           letter_group
Name: 158284, dtype: object
qualification                              Higher
year                                         2020
Subject            Fashion and Textile Technology
NumberOfCentres                               NaN
gender                                        all
grade                                         A-C
NoOfStudents                                  142
grade_type                           letter_group
Name: 140044, dtype: object
qualification                              Higher
year                                         2020
Subject            Fashion and Textile Technology
NumberOfCentres                               NaN
gender                                        all
grade                                         A-D
NoOfStudents                                  161
grade_type                           letter_group
Name: 159163, dtype: object
qualification                              Higher
year                                         2020
Subject            Fashion and Textile Technology
NumberOfCentres                               NaN
gender                                     female
grade                                         A-B
NoOfStudents                                  116
grade_type                           letter_group
Name: 158283, dtype: object
qualification                              Higher
year                                         2020
Subject            Fashion and Textile Technology
NumberOfCentres                               NaN
gender                                     female
grade                                         A-C
NoOfStudents                                  152
grade_type                           letter_group
Name: 140043, dtype: object
qualification                              Higher
year                                         2020
Subject            Fashion and Textile Technology
NumberOfCentres                               NaN
gender                                     female
grade                                         A-D
NoOfStudents                                  157
grade_type                           letter_group
Name: 159162, dtype: object
qualification                              Higher
year                                         2020
Subject            Fashion and Textile Technology
NumberOfCentres                               NaN
gender                                       male
grade                                         A-B
NoOfStudents                                    4
grade_type                           letter_group
Name: 158282, dtype: object
qualification                              Higher
year                                         2020
Subject            Fashion and Textile Technology
NumberOfCentres                               NaN
gender                                       male
grade                                         A-C
NoOfStudents                                    8
grade_type                           letter_group
Name: 140042, dtype: object
qualification                              Higher
year                                         2020
Subject            Fashion and Textile Technology
NumberOfCentres                               NaN
gender                                       male
grade                                         A-D
NoOfStudents                                    8
grade_type                           letter_group
Name: 159161, dtype: object
qualification            Higher
year                       2020
Subject                  French
NumberOfCentres             NaN
gender                      all
grade                       A-B
NoOfStudents               2320
grade_type         letter_group
Name: 158287, dtype: object
qualification            Higher
year                       2020
Subject                  French
NumberOfCentres             NaN
gender                      all
grade                       A-C
NoOfStudents               2802
grade_type         letter_group
Name: 140047, dtype: object
qualification            Higher
year                       2020
Subject                  French
NumberOfCentres             NaN
gender                      all
grade                       A-D
NoOfStudents               3053
grade_type         letter_group
Name: 159166, dtype: object
qualification            Higher
year                       2020
Subject                  French
NumberOfCentres             NaN
gender                   female
grade                       A-B
NoOfStudents               2044
grade_type         letter_group
Name: 158286, dtype: object
qualification            Higher
year                       2020
Subject                  French
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               2287

Name: 158357, dtype: object
qualification            Higher
year                       2020
Subject                 Spanish
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                765
grade_type         letter_group
Name: 140117, dtype: object
qualification            Higher
year                       2020
Subject                 Spanish
NumberOfCentres             NaN
gender                     male
grade                       A-D
NoOfStudents                790
grade_type         letter_group
Name: 159236, dtype: object
qualification            Higher
year                       2020
Subject                    Urdu
NumberOfCentres             NaN
gender                      all
grade                       A-B
NoOfStudents                117
grade_type         letter_group
Name: 158362, dtype: object
qualification            Higher
year                       2020
Subject                    Urdu
NumberOfCentres             NaN
gender                      all
grade                       A-C
NoOfStudents                117
grade_type         letter_group
Name: 140122, dtype: object
qualification            Higher
year                       2020
Subject                    Urdu
NumberOfCentres             NaN
gender                      all
grade                       A-D
NoOfStudents                117
grade_type         letter_group
Name: 159241, dtype: object
qualification            Higher
year                       2020
Subject                    Urdu
NumberOfCentres             NaN
gender                   female
grade                       A-B
NoOfStudents                 79
grade_type         letter_group
Name: 158361, dtype: object
qualification            Higher
year                       2020
Subject                    Urdu
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                 79
grade_type         letter_group
Name: 140121, dtype: object
qualification            Higher
year                       2020
Subject                    Urdu
NumberOfCentres             NaN
gender                   female
grade                       A-D
NoOfStudents                 80
grade_type         letter_group
Name: 159240, dtype: object
qualification            Higher
year                       2020
Subject                    Urdu
NumberOfCentres             NaN
gender                     male
grade                       A-B
NoOfStudents                 38
grade_type         letter_group
Name: 158360, dtype: object
qualification            Higher
year                       2020
Subject                    Urdu
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 38
grade_type         letter_group
Name: 140120, dtype: object
qualification            Higher
year                       2020
Subject                    Urdu
NumberOfCentres             NaN
gender                     male
grade                       A-D
NoOfStudents                 38
grade_type         letter_group
Name: 159239, dtype: object
qualification            Higher
year                       2021
Subject              Accounting
NumberOfCentres             NaN
gender                      all
grade                       A-B
NoOfStudents               1058
grade_type         letter_group
Name: 158614, dtype: object
qualification            Higher
year                       2021
Subject              Accounting
NumberOfCentres             NaN
gender                      all
grade                       A-C
NoOfStudents               1213
grade_type         letter_group
Name: 140374, dtype: object
qualification            Higher
year                       2021
Subject              Accounting
NumberOfCentres             NaN
gender                      all
grade                       A-D
NoOfStudents               1276
grade_type         letter_group
Name: 159388, dtype: object
qualification            Higher
year                       2021
Subject              Accounting
NumberOfCentres             NaN
gender                   female
grade                       A-B
NoOfStudents                505
grade_type         letter_group
Name: 158613, dtype: object
qualification            Higher
year                       2021
Subject              Accounting
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                561
grade_type         letter_group
Name: 140373, dtype: object
qualification            Higher
year                       2021
Subject              Accounting
NumberOfCentres             NaN
gender                   female
grade                       A-D
NoOfStudents                584
grade_type         letter_group
Name: 159387, dtype: object
qualification            Higher
year                       2021
Subject              Accounting
NumberOfCentres             NaN
gender                     male
grade                       A-B
NoOfStudents                553
grade_type         letter_group
Name: 158612, dtype: object
qualification            Higher
year                       2021
Subject              Accounting
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                652
grade_type         letter_group
Name: 140372, dtype: object
qualification            Higher
year                       2021
Subject              Accounting
NumberOfCentres             NaN
gender                     male
grade                       A-D
NoOfStudents                692
grade_type         letter_group
Name: 159386, dtype: object
qualification                     Higher
year                                2021
Subject            Administration and IT
NumberOfCentres                      NaN
gender                               all
grade                                A-B
NoOfStudents                        3221
grade_type                  letter_group
Name: 158617, dtype: object
qualification                     Higher
year                                2021
Subject            Administration and IT
NumberOfCentres                      NaN
gender                               all
grade                                A-C
NoOfStudents                        3963
grade_type                  letter_group
Name: 140377, dtype: object
qualification                     Higher
year                                2021
Subject            Administration and IT
NumberOfCentres                      NaN
gender                               all
grade                                A-D
NoOfStudents                        4232
grade_type                  letter_group
Name: 159391, dtype: object
qualification                     Higher
year                                2021
Subject            Administration and IT
NumberOfCentres                      NaN
gender                            female
grade                                A-B
NoOfStudents                        2137
grade_type                  letter_group
Name: 158616, dtype: object
qualification                     Higher
year                                2021
Subject            Administration and IT
NumberOfCentres                      NaN
gender                            female
grade                                A-C
NoOfStudents                        2554
grade_type                  letter_group
Name: 140376, dtype: object
qualification                     Higher
year                                2021
Subject            Administration and IT
NumberOfCentres                      NaN
gender                            female
grade                                A-D
NoOfStudents                        2701
grade_type                  letter_group
Name: 159390, dtype: object
qualification                     Higher
year                                2021
Subject            Administration and IT
NumberOfCentres                      NaN
gender                              male
grade                                A-B
NoOfStudents                        1084
grade_type                  letter_group
Name: 158615, dtype: object
qualification                     Higher
year                                2021
Subject            Administration and IT
NumberOfCentres                      NaN
gender                              male
grade                                A-C
NoOfStudents                        1409
grade_type                  letter_group
Name: 140375, dtype: object
qualification                     Higher
year                                2021
Subject            Administration and IT
NumberOfCentres                      NaN
gender                              male
grade                                A-D
NoOfStudents                        1531
grade_type                  letter_group
Name: 159389, dtype: object
qualification              Higher
year                         2021
Subject            Art and Design
NumberOfCentres               NaN
gender                        all
grade                         A-B
NoOfStudents                 4383
grade_type           letter_group
Name: 158620, dtype: object
qualification              Higher
year                         2021
Subject            Art and Design
NumberOfCentres               NaN
gender                        all
grade                         A-C
NoOfStudents                 5425
grade_type           letter_group
Name: 140380, dtype: object
qualification              Higher
year                         2021
Subject            Art and Design
NumberOfCentres               NaN
gender                        all
grade                         A-D
NoOfStudents                 5625
grade_type           letter_group
Name: 159394, dtype: object
qualification              Higher
year                         2021
Subject            Art and Design
NumberOfCentres               NaN
gender                     female
grade                         A-B
NoOfStudents                 3607
grade_type           letter_group
Name: 158619, dtype: object
qualification              Higher
year                         2021
Subject            Art and Design
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                 4371
grade_type           letter_group
Name: 140379, dtype: object
qualification              Higher
year                         2021
Subject            Art and Design
NumberOfCentres               NaN
gender                     female
grade                         A-D
NoOfStudents                 4511
grade_type           letter_group
Name: 159393, dtype: object
qualification              Higher
year                         2021
Subject            Art and Design
NumberOfCentres               NaN
gender                       male
grade                         A-B
NoOfStudents                  776
grade_type           letter_group
Name: 158618, dtype: object
qualification              Higher
year                         2021
Subject            Art and Design
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                 1054
grade_type           letter_group
Name: 140378, dtype: object
qualification              Higher
year                         2021
Subject            Art and Design
NumberOfCentres               NaN
gender                       male
grade                         A-D
NoOfStudents                 1114
grade_type           letter_group
Name: 159392, dtype: object
qualification            Higher
year                       2021
Subject                 Biology
NumberOfCentres             NaN
gender                      all
grade                       A-B
NoOfStudents               4307
grade_type         letter_group
Name: 158623, dtype: object
qualification            Higher
year                       2021
Subject                 Biology
NumberOfCentres             NaN
gender                      all
grade                       A-C
NoOfStudents               5775
grade_type         letter_group
Name: 140383, dtype: object
qualification            Higher
year                       2021
Subject                 Biology
NumberOfCentres             NaN
gender                      all
grade                       A-D
NoOfStudents               6634
grade_type         letter_group
Name: 159397, dtype: object
qualification            Higher
year                       2021
Subject                 Biology
NumberOfCentres             NaN
gender                   female
grade                       A-B
NoOfStudents               2842
grade_type         letter_group
Name: 158622, dtype: object
qualification            Higher
year                       2021
Subject                 Biology
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               3795
grade_type         letter_group
Name: 140382, dtype: object
qualification            Higher
year                       2021
Subject                 Biology
NumberOfCentres             NaN
gender                   female
grade                       A-D
NoOfStudents               4340
grade_type         letter_group
Name: 159396, dtype: object
qualification            Higher
year                       2021
Subject                 Biology
NumberOfCentres             NaN
gender                     male
grade                       A-B
NoOfStudents               1465
grade_type         letter_group
Name: 158621, dtype: object
qualification            Higher
year                       2021
Subject                 Biology
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               1980
grade_type         letter_group
Name: 140381, dtype: object
qualification            Higher
year                       2021
Subject                 Biology
NumberOfCentres             NaN
gender                     male
grade                       A-D
NoOfStudents               2294
grade_type         letter_group
Name: 159395, dtype: object
qualification                   Higher
year                              2021
Subject            Business Management
NumberOfCentres                    NaN
gender                             all
grade                              A-B
NoOfStudents                      6313
grade_type                letter_group
Name: 158626, dtype: object
qualification                   Higher
year                              2021
Subject            Business Management
NumberOfCentres                    NaN
gender                             all
grade                              A-C
NoOfStudents                      7708
grade_type                letter_group
Name: 140386, dtype: object
qualification                   Higher
year                              2021
Subject            Business Management
NumberOfCentres                    NaN
gender                             all
grade                              A-D
NoOfStudents                      8276
grade_type                letter_group
Name: 159400, dtype: object
qualification                   Higher
year                              2021
Subject            Business Management
NumberOfCentres                    NaN
gender                          female
grade                              A-B
NoOfStudents                      3542
grade_type                letter_group
Name: 158625, dtype: object
qualification                   Higher
year                              2021
Subject            Business Management
NumberOfCentres                    NaN
gender                          female
grade                              A-C
NoOfStudents                      4187
grade_type                letter_group
Name: 140385, dtype: object
qualification                   Higher
year                              2021
Subject            Business Management
NumberOfCentres                    NaN
gender                          female
grade                              A-D
NoOfStudents                      4443
grade_type                letter_group
Name: 159399, dtype: object
qualification                   Higher
year                              2021
Subject            Business Management
NumberOfCentres                    NaN
gender                            male
grade                              A-B
NoOfStudents                      2771
grade_type                letter_group
Name: 158624, dtype: object
qualification                   Higher
year                              2021
Subject            Business Management
NumberOfCentres                    NaN
gender                            male
grade                              A-C
NoOfStudents                      3521
grade_type                letter_group
Name: 140384, dtype: object
qualification                   Higher
year                              2021
Subject            Business Management
NumberOfCentres                    NaN
gender                            male
grade                              A-D
NoOfStudents                      3833
grade_type                letter_group
Name: 159398, dtype: object
qualification            Higher
year                       2021
Subject                    Care
NumberOfCentres             NaN
gender                      all
grade                       A-B
NoOfStudents                192
grade_type         letter_group
Name: 158629, dtype: object
qualification            Higher
year                       2021
Subject                    Care
NumberOfCentres             NaN
gender                      all
grade                       A-C
NoOfStudents                282
grade_type         letter_group
Name: 140389, dtype: object
qualification            Higher
year                       2021
Subject                    Care
NumberOfCentres             NaN
gender                      all
grade                       A-D
NoOfStudents                310
grade_type         letter_group
Name: 159403, dtype: object
qualification            Higher
year                       2021
Subject                    Care
NumberOfCentres             NaN
gender                   female
grade                       A-B
NoOfStudents                176
grade_type         letter_group
Name: 158628, dtype: object
qualification            Higher
year                       2021
Subject                    Care
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                252
grade_type         letter_group
Name: 140388, dtype: object
qualification            Higher
year                       2021
Subject                    Care
NumberOfCentres             NaN
gender                   female
grade                       A-D
NoOfStudents                277
grade_type         letter_group
Name: 159402, dtype: object
qualification            Higher
year                       2021
Subject                    Care
NumberOfCentres             NaN
gender                     male
grade                       A-B
NoOfStudents                 16
grade_type         letter_group
Name: 158627, dtype: object
qualification            Higher
year                       2021
Subject                    Care
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 30
grade_type         letter_group
Name: 140387, dtype: object
qualification            Higher
year                       2021
Subject                    Care
NumberOfCentres             NaN
gender                     male
grade                       A-D
NoOfStudents                 33
grade_type         letter_group
Name: 159401, dtype: object
qualification            Higher
year                       2021
Subject               Chemistry
NumberOfCentres             NaN
gender                      all
grade                       A-B

Name: 158702, dtype: object
qualification            Higher
year                       2021
Subject                   Latin
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                113
grade_type         letter_group
Name: 140462, dtype: object
qualification            Higher
year                       2021
Subject                   Latin
NumberOfCentres             NaN
gender                     male
grade                       A-D
NoOfStudents                114
grade_type         letter_group
Name: 159476, dtype: object
qualification            Higher
year                       2021
Subject             Mathematics
NumberOfCentres             NaN
gender                      all
grade                       A-B
NoOfStudents              12541
grade_type         letter_group
Name: 158707, dtype: object
qualification            Higher
year                       2021
Subject             Mathematics
NumberOfCentres             NaN
gender                      all
grade                       A-C
NoOfStudents              15562
grade_type         letter_group
Name: 140467, dtype: object
qualification            Higher
year                       2021
Subject             Mathematics
NumberOfCentres             NaN
gender                      all
grade                       A-D
NoOfStudents              16995
grade_type         letter_group
Name: 159481, dtype: object
qualification            Higher
year                       2021
Subject             Mathematics
NumberOfCentres             NaN
gender                   female
grade                       A-B
NoOfStudents               6172
grade_type         letter_group
Name: 158706, dtype: object
qualification            Higher
year                       2021
Subject             Mathematics
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               7538
grade_type         letter_group
Name: 140466, dtype: object
qualification            Higher
year                       2021
Subject             Mathematics
NumberOfCentres             NaN
gender                   female
grade                       A-D
NoOfStudents               8193
grade_type         letter_group
Name: 159480, dtype: object
qualification            Higher
year                       2021
Subject             Mathematics
NumberOfCentres             NaN
gender                     male
grade                       A-B
NoOfStudents               6369
grade_type         letter_group
Name: 158705, dtype: object
qualification            Higher
year                       2021
Subject             Mathematics
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               8024
grade_type         letter_group
Name: 140465, dtype: object
qualification            Higher
year                       2021
Subject             Mathematics
NumberOfCentres             NaN
gender                     male
grade                       A-D
NoOfStudents               8802
grade_type         letter_group
Name: 159479, dtype: object
qualification            Higher
year                       2021
Subject                   Media
NumberOfCentres             NaN
gender                      all
grade                       A-B
NoOfStudents                772
grade_type         letter_group
Name: 158710, dtype: object
qualification            Higher
year                       2021
Subject                   Media
NumberOfCentres             NaN
gender                      all
grade                       A-C
NoOfStudents                937
grade_type         letter_group
Name: 140470, dtype: object
qualification            Higher
year                       2021
Subject                   Media
NumberOfCentres             NaN
gender                      all
grade                       A-D
NoOfStudents                986
grade_type         letter_group
Name: 159484, dtype: object
qualification            Higher
year                       2021
Subject                   Media
NumberOfCentres             NaN
gender                   female
grade                       A-B
NoOfStudents                476
grade_type         letter_group
Name: 158709, dtype: object
qualification            Higher
year                       2021
Subject                   Media
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                547
grade_type         letter_group
Name: 140469, dtype: object
qualification            Higher
year                       2021
Subject                   Media
NumberOfCentres             NaN
gender                   female
grade                       A-D
NoOfStudents                564
grade_type         letter_group
Name: 159483, dtype: object
qualification            Higher
year                       2021
Subject                   Media
NumberOfCentres             NaN
gender                     male
grade                       A-B
NoOfStudents                296
grade_type         letter_group
Name: 158708, dtype: object
qualification            Higher
year                       2021
Subject                   Media
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                390
grade_type         letter_group
Name: 140468, dtype: object
qualification            Higher
year                       2021
Subject                   Media
NumberOfCentres             NaN
gender                     male
grade                       A-D
NoOfStudents                422
grade_type         letter_group
Name: 159482, dtype: object
qualification              Higher
year                         2021
Subject            Modern Studies
NumberOfCentres               NaN
gender                        all
grade                         A-B
NoOfStudents                 7321
grade_type           letter_group
Name: 158713, dtype: object
qualification              Higher
year                         2021
Subject            Modern Studies
NumberOfCentres               NaN
gender                        all
grade                         A-C
NoOfStudents                 8646
grade_type           letter_group
Name: 140473, dtype: object
qualification              Higher
year                         2021
Subject            Modern Studies
NumberOfCentres               NaN
gender                        all
grade                         A-D
NoOfStudents                 9167
grade_type           letter_group
Name: 159487, dtype: object
qualification              Higher
year                         2021
Subject            Modern Studies
NumberOfCentres               NaN
gender                     female
grade                         A-B
NoOfStudents                 4781
grade_type           letter_group
Name: 158712, dtype: object
qualification              Higher
year                         2021
Subject            Modern Studies
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                 5514
grade_type           letter_group
Name: 140472, dtype: object
qualification              Higher
year                         2021
Subject            Modern Studies
NumberOfCentres               NaN
gender                     female
grade                         A-D
NoOfStudents                 5792
grade_type           letter_group
Name: 159486, dtype: object
qualification              Higher
year                         2021
Subject            Modern Studies
NumberOfCentres               NaN
gender                       male
grade                         A-B
NoOfStudents                 2540
grade_type           letter_group
Name: 158711, dtype: object
qualification              Higher
year                         2021
Subject            Modern Studies
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                 3132
grade_type           letter_group
Name: 140471, dtype: object
qualification              Higher
year                         2021
Subject            Modern Studies
NumberOfCentres               NaN
gender                       male
grade                         A-D
NoOfStudents                 3375
grade_type           letter_group
Name: 159485, dtype: object
qualification            Higher
year                       2021
Subject                   Music
NumberOfCentres             NaN
gender                      all
grade                       A-B
NoOfStudents               4525
grade_type         letter_group
Name: 158716, dtype: object
qualification            Higher
year                       2021
Subject                   Music
NumberOfCentres             NaN
gender                      all
grade                       A-C
NoOfStudents               5081
grade_type         letter_group
Name: 140476, dtype: object
qualification            Higher
year                       2021
Subject                   Music
NumberOfCentres             NaN
gender                      all
grade                       A-D
NoOfStudents               5167
grade_type         letter_group
Name: 159490, dtype: object
qualification            Higher
year                       2021
Subject                   Music
NumberOfCentres             NaN
gender                   female
grade                       A-B
NoOfStudents               2551
grade_type         letter_group
Name: 158715, dtype: object
qualification            Higher
year                       2021
Subject                   Music
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               2833
grade_type         letter_group
Name: 140475, dtype: object
qualification            Higher
year                       2021
Subject                   Music
NumberOfCentres             NaN
gender                   female
grade                       A-D
NoOfStudents               2872
grade_type         letter_group
Name: 159489, dtype: object
qualification            Higher
year                       2021
Subject                   Music
NumberOfCentres             NaN
gender                     male
grade                       A-B
NoOfStudents               1974
grade_type         letter_group
Name: 158714, dtype: object
qualification            Higher
year                       2021
Subject                   Music
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               2248
grade_type         letter_group
Name: 140474, dtype: object
qualification            Higher
year                       2021
Subject                   Music
NumberOfCentres             NaN
gender                     male
grade                       A-D
NoOfStudents               2295
grade_type         letter_group
Name: 159488, dtype: object
qualification                Higher
year                           2021
Subject            Music Technology
NumberOfCentres                 NaN
gender                          all
grade                           A-B
NoOfStudents                    716
grade_type             letter_group
Name: 158719, dtype: object
qualification                Higher
year                           2021
Subject            Music Technology
NumberOfCentres                 NaN
gender                          all
grade                           A-C
NoOfStudents                    857
grade_type             letter_group
Name: 140479, dtype: object
qualification                Higher
year                           2021
Subject            Music Technology
NumberOfCentres                 NaN
gender                          all
grade                           A-D
NoOfStudents                    895
grade_type             letter_group
Name: 159493, dtype: object
qualification                Higher
year                           2021
Subject            Music Technology
NumberOfCentres                 NaN
gender                       female
grade                           A-B
NoOfStudents                    196
grade_type             letter_group
Name: 158718, dtype: object
qualification                Higher
year                           2021
Subject            Music Technology
NumberOfCentres                 NaN
gender                       female
grade                           A-C
NoOfStudents                    223
grade_type             letter_group
Name: 140478, dtype: object
qualification                Higher
year                           2021
Subject            Music Technology
NumberOfCentres                 NaN
gender                       female
grade                           A-D
NoOfStudents                    230
grade_type             letter_group
Name: 159492, dtype: object
qualification                Higher
year                           2021
Subject            Music Technology
NumberOfCentres                 NaN
gender                         male
grade                           A-B
NoOfStudents                    520
grade_type             letter_group
Name: 158717, dtype: object
qualification                Higher
year                           2021
Subject            Music Technology
NumberOfCentres                 NaN
gender                         male
grade                           A-C
NoOfStudents                    634
grade_type             letter_group
Name: 140477, dtype: object
qualification                Higher
year                           2021
Subject            Music Technology
NumberOfCentres                 NaN
gender                         male
grade                           A-D
NoOfStudents                    665
grade_type             letter_group
Name: 159491, dtype: object
qualification            Higher
year                       2021
Subject              Philosophy
NumberOfCentres             NaN
gender                      all
grade                       A-B
NoOfStudents                589
grade_type         letter_group
Name: 158722, dtype: object
qualification            Higher
year                       2021
Subject              Philosophy
NumberOfCentres             NaN
gender                      all
grade                       A-C
NoOfStudents                717
grade_type         letter_group
Name: 140482, dtype: object
qualification            Higher
year                       2021
Subject              Philosophy
NumberOfCentres             NaN
gender                      all
grade                       A-D
NoOfStudents                774
grade_type         letter_group
Name: 159496, dtype: object
qualification            Higher
year                       2021
Subject              Philosophy
NumberOfCentres             NaN
gender                   female
grade                       A-B
NoOfStudents                389
grade_type         letter_group
Name: 158721, dtype: object
qualification            Higher
year                       2021
Subject              Philosophy
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                466
grade_type         letter_group
Name: 140481, dtype: object
qualification            Higher
year                       2021
Subject              Philosophy
NumberOfCentres             NaN
gender                   female
grade                       A-D
NoOfStudents                511
grade_type         letter_group
Name: 159495, dtype: object
qualification            Higher
year                       2021
Subject              Philosophy
NumberOfCentres             NaN
gender                     male
grade                       A-B
NoOfStudents                200
grade_type         letter_group
Name: 158720, dtype: object
qualification            Higher
year                       2021
Subject              Philosophy
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                251
grade_type         letter_group
Name: 140480, dtype: object
qualification            Higher
year                       2021
Subject              Philosophy
NumberOfCentres             NaN
gender                     male
grade                       A-D
NoOfStudents                263
grade_type         letter_group
Name: 159494, dtype: object
qualification            Higher
year                       2021
Subject             Photography
NumberOfCentres             NaN
gender                      all
grade                       A-B
NoOfStudents               1835
grade_type         letter_group
Name: 158725, dtype: object
qualification            Higher
year                       2021
Subject             Photography
NumberOfCentres             NaN
gender                      all
grade                       A-C
NoOfStudents               2335
grade_type         letter_group
Name: 140485, dtype: object
qualification            Higher
year                       2021
Subject             Photography
NumberOfCentres             NaN
gender                      all
grade                       A-D
NoOfStudents               2439
grade_type         letter_group
Name: 159499, dtype: object
qualification            Higher
year                       2021
Subject             Photography
NumberOfCentres             NaN
gender                   female
grade                       A-B
NoOfStudents               1356
grade_type         letter_group
Name: 158724, dtype: object
qualification            Higher
year                       2021
Subject             Photography
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               1692
grade_type         letter_group
Name: 140484, dtype: object
qualification            Higher
year                       2021
Subject             Photography
NumberOfCentres             NaN
gender                   female
grade                       A-D
NoOfStudents               1749
grade_type         letter_group
Name: 159498, dtype: object
qualification            Higher
year                       2021
Subject             Photography
NumberOfCentres             NaN
gender                     male
grade                       A-B
NoOfStudents                479
grade_type         letter_group
Name: 158723, dtype: object
qualification            Higher
year                       2021
Subject             Photography
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                643
grade_type         letter_group
Name: 140483, dtype: object
qualification            Higher
year                       2021
Subject             Photography
NumberOfCentres             NaN
gender                     male
grade                       A-D
NoOfStudents                690
grade_type         letter_group
Name: 159497, dtype: object
qualification                  Higher
year                             2021
Subject            Physical Education
NumberOfCentres                   NaN
gender                            all
grade                             A-B
NoOfStudents                     8510
grade_type               letter_group
Name: 158728, dtype: object
qualification                  Higher
year                             2021
Subject            Physical Education
NumberOfCentres                   NaN
gender                            all
grade                             A-C
NoOfStudents                    10957
grade_type               letter_group
Name: 140488, dtype: object
qualification                  Higher
year                             2021
Subject            Physical Education
NumberOfCentres                   NaN
gender                            all
grade                             A-D
NoOfStudents                    11614
grade_type               letter_group
Name: 159502, dtype: object
qualification                  Higher
year                             2021

qualification      Intermediate2
year                        2014
Subject               Accounting
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                  87
grade_type          letter_group
Name: 138567, dtype: object
qualification      Intermediate2
year                        2014
Subject               Accounting
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                  62
grade_type          letter_group
Name: 138566, dtype: object
qualification       Intermediate2
year                         2014
Subject            Administration
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                 1056
grade_type           letter_group
Name: 138569, dtype: object
qualification       Intermediate2
year                         2014
Subject            Administration
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  428
grade_type           letter_group
Name: 138568, dtype: object
qualification       Intermediate2
year                         2014
Subject            Art and Design
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                 1958
grade_type           letter_group
Name: 138571, dtype: object
qualification       Intermediate2
year                         2014
Subject            Art and Design
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  749
grade_type           letter_group
Name: 138570, dtype: object
qualification      Intermediate2
year                        2014
Subject                  Biology
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                2872
grade_type          letter_group
Name: 138573, dtype: object
qualification      Intermediate2
year                        2014
Subject                  Biology
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                1661
grade_type          letter_group
Name: 138572, dtype: object
qualification      Intermediate2
year                        2014
Subject            Biotechnology
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                  21
grade_type          letter_group
Name: 138575, dtype: object
qualification      Intermediate2
year                        2014
Subject            Biotechnology
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                  23
grade_type          letter_group
Name: 138574, dtype: object
qualification            Intermediate2
year                              2014
Subject            Business Management
NumberOfCentres                    NaN
gender                          female
grade                              A-C
NoOfStudents                       961
grade_type                letter_group
Name: 138577, dtype: object
qualification            Intermediate2
year                              2014
Subject            Business Management
NumberOfCentres                    NaN
gender                            male
grade                              A-C
NoOfStudents                       806
grade_type                letter_group
Name: 138576, dtype: object
qualification      Intermediate2
year                        2014
Subject                     Care
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                 467
grade_type          letter_group
Name: 138579, dtype: object
qualification      Intermediate2
year                        2014
Subject                     Care
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                  33
grade_type          letter_group
Name: 138578, dtype: object
qualification                            Intermediate2
year                                              2014
Subject            Care Issues for Society: Child Care
NumberOfCentres                                    NaN
gender                                          female
grade                                              A-C
NoOfStudents                                        24
grade_type                                letter_group
Name: 138581, dtype: object
qualification                            Intermediate2
year                                              2014
Subject            Care Issues for Society: Child Care
NumberOfCentres                                    NaN
gender                                            male
grade                                              A-C
NoOfStudents                                       NaN
grade_type                                letter_group
Name: 138580, dtype: object
qualification                              Intermediate2
year                                                2014
Subject            Care Issues for Society: Older People
NumberOfCentres                                      NaN
gender                                            female
grade                                                A-C
NoOfStudents                                          60
grade_type                                  letter_group
Name: 138583, dtype: object
qualification                              Intermediate2
year                                                2014
Subject            Care Issues for Society: Older People
NumberOfCentres                                      NaN
gender                                              male
grade                                                A-C
NoOfStudents                                           9
grade_type                                  letter_group
Name: 138582, dtype: object
qualification      Intermediate2
year                        2014
Subject                Chemistry
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                1307
grade_type          letter_group
Name: 138585, dtype: object
qualification      Intermediate2
year                        2014
Subject                Chemistry
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                1389
grade_type          letter_group
Name: 138584, dtype: object
qualification          Intermediate2
year                            2014
Subject            Chinese Languages
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                      28
grade_type              letter_group
Name: 138587, dtype: object
qualification          Intermediate2
year                            2014
Subject            Chinese Languages
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                      24
grade_type              letter_group
Name: 138586, dtype: object
qualification        Intermediate2
year                          2014
Subject            Classical Greek
NumberOfCentres                NaN
gender                      female
grade                          A-C
NoOfStudents                   NaN
grade_type            letter_group
Name: 138589, dtype: object
qualification        Intermediate2
year                          2014
Subject            Classical Greek
NumberOfCentres                NaN
gender                        male
grade                          A-C
NoOfStudents                   NaN
grade_type            letter_group
Name: 138588, dtype: object
qualification          Intermediate2
year                            2014
Subject            Classical Studies
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                      35
grade_type              letter_group
Name: 138591, dtype: object
qualification          Intermediate2
year                            2014
Subject            Classical Studies
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                      57
grade_type              letter_group
Name: 138590, dtype: object
qualification      Intermediate2
year                        2014
Subject                Computing
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                 298
grade_type          letter_group
Name: 138593, dtype: object
qualification      Intermediate2
year                        2014
Subject                Computing
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                1186
grade_type          letter_group
Name: 138592, dtype: object
qualification                 Intermediate2
year                                   2014
Subject            Creative Cake Production
NumberOfCentres                         NaN
gender                               female
grade                                   A-C
NoOfStudents                            654
grade_type                     letter_group
Name: 138595, dtype: object
qualification                 Intermediate2
year                                   2014
Subject            Creative Cake Production
NumberOfCentres                         NaN
gender                                 male
grade                                   A-C
NoOfStudents                            165
grade_type                     letter_group
Name: 138594, dtype: object
qualification      Intermediate2
year                        2014
Subject                    Drama
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                 424
grade_type          letter_group
Name: 138597, dtype: object
qualification      Intermediate2
year                        2014
Subject                    Drama
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                 323
grade_type          letter_group
Name: 138596, dtype: object
qualification      Intermediate2
year                        2014
Subject                Economics
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                  59
grade_type          letter_group
Name: 138599, dtype: object
qualification      Intermediate2
year                        2014
Subject                Economics
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                 113
grade_type          letter_group
Name: 138598, dtype: object
qualification                             Intermediate2
year                                               2014
Subject            Electrical Installation Fundamentals
NumberOfCentres                                     NaN
gender                                           female
grade                                               A-C
NoOfStudents                                        NaN
grade_type                                 letter_group
Name: 138601, dtype: object
qualification                             Intermediate2
year                                               2014
Subject            Electrical Installation Fundamentals
NumberOfCentres                                     NaN
gender                                             male
grade                                               A-C
NoOfStudents                                         58
grade_type                                 letter_group
Name: 138600, dtype: object
qualification                               Intermediate2
year                                                 2014
Subject            Electronic and Electrical Fundamentals
NumberOfCentres                                       NaN
gender                                             female
grade                                                 A-C
NoOfStudents                                          NaN
grade_type                                   letter_group
Name: 138603, dtype: object
qualification                               Intermediate2
year                                                 2014
Subject            Electronic and Electrical Fundamentals
NumberOfCentres                                       NaN
gender                                               male
grade                                                 A-C
NoOfStudents                                           17
grade_type                                   letter_group
Name: 138602, dtype: object
qualification                 Intermediate2
year                                   2014
Subject            Engineering Craft Skills
NumberOfCentres                         NaN
gender                               female
grade                                   A-C
NoOfStudents                             32
grade_type                     letter_group
Name: 138605, dtype: object
qualification                 Intermediate2
year                                   2014
Subject            Engineering Craft Skills
NumberOfCentres                         NaN
gender                                 male
grade                                   A-C
NoOfStudents                            740
grade_type                     letter_group
Name: 138604, dtype: object
qualification      Intermediate2
year                        2014
Subject                  English
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                8030
grade_type          letter_group
Name: 138607, dtype: object
qualification      Intermediate2
year                        2014
Subject                  English
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                7789
grade_type          letter_group
Name: 138606, dtype: object
qualification                                Intermediate2
year                                                  2014
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                              female
grade                                                  A-C
NoOfStudents                                           271
grade_type                                    letter_group
Name: 138609, dtype: object
qualification                                Intermediate2
year                                                  2014
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                                male
grade                                                  A-C
NoOfStudents                                           174
grade_type                                    letter_group
Name: 138608, dtype: object
qualification      Intermediate2
year                        2014
Subject                   French
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                1377
grade_type          letter_group
Name: 138611, dtype: object
qualification      Intermediate2
year                        2014
Subject                   French
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                 878
grade_type          letter_group
Name: 138610, dtype: object
qualification          Intermediate2
year                            2014
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                       7
grade_type              letter_group
Name: 138613, dtype: object
qualification          Intermediate2
year                            2014
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                       5
grade_type              letter_group
Name: 138612, dtype: object
qualification      Intermediate2
year                        2014
Subject                Geography
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                 795
grade_type          letter_group
Name: 138617, dtype: object
qualification      Intermediate2
year                        2014
Subject                Geography
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                1054
grade_type          letter_group
Name: 138616, dtype: object
qualification      Intermediate2
year                        2014
Subject                  Geology
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                 NaN
grade_type          letter_group
Name: 138619, dtype: object
qualification      Intermediate2
year                        2014
Subject                  Geology
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                   7
grade_type          letter_group
Name: 138618, dtype: object
qualification      Intermediate2
year                        2014
Subject                   German
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                 178
grade_type          letter_group
Name: 138621, dtype: object
qualification      Intermediate2
year                        2014
Subject                   German
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                 143
grade_type          letter_group
Name: 138620, dtype: object
qualification              Intermediate2
year                                2014
Subject            Graphic Communication
NumberOfCentres                      NaN
gender                            female
grade                                A-C
NoOfStudents                         272
grade_type                  letter_group
Name: 138623, dtype: object
qualification              Intermediate2
year                                2014
Subject            Graphic Communication
NumberOfCentres                      NaN
gender                              male
grade                                A-C
NoOfStudents                         829
grade_type                  letter_group
Name: 138622, dtype: object
qualification      Intermediate2
year                        2014
Subject                 Gàidhlig
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                   6
grade_type          letter_group
Name: 138615, dtype: object
qualification      Intermediate2
year                        2014
Subject                 Gàidhlig
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                   8
grade_type          letter_group
Name: 138614, dtype: object
qualification                           Intermediate2
year                                             2014
Subject            Health and Safety in Care Settings
NumberOfCentres                                   NaN
gender                                         female

qualification      Intermediate2
year                        2015
Subject                  English
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                 673
grade_type          letter_group
Name: 138919, dtype: object
qualification      Intermediate2
year                        2015
Subject                  English
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                 706
grade_type          letter_group
Name: 138918, dtype: object
qualification                                Intermediate2
year                                                  2015
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                              female
grade                                                  A-C
NoOfStudents                                            59
grade_type                                    letter_group
Name: 138921, dtype: object
qualification                                Intermediate2
year                                                  2015
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                                male
grade                                                  A-C
NoOfStudents                                            46
grade_type                                    letter_group
Name: 138920, dtype: object
qualification      Intermediate2
year                        2015
Subject                   French
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                  86
grade_type          letter_group
Name: 138923, dtype: object
qualification      Intermediate2
year                        2015
Subject                   French
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                  73
grade_type          letter_group
Name: 138922, dtype: object
qualification          Intermediate2
year                            2015
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                     NaN
grade_type              letter_group
Name: 138925, dtype: object
qualification          Intermediate2
year                            2015
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                     NaN
grade_type              letter_group
Name: 138924, dtype: object
qualification      Intermediate2
year                        2015
Subject                Geography
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                  88
grade_type          letter_group
Name: 138929, dtype: object
qualification      Intermediate2
year                        2015
Subject                Geography
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                  91
grade_type          letter_group
Name: 138928, dtype: object
qualification      Intermediate2
year                        2015
Subject                  Geology
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                 NaN
grade_type          letter_group
Name: 138931, dtype: object
qualification      Intermediate2
year                        2015
Subject                  Geology
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                 NaN
grade_type          letter_group
Name: 138930, dtype: object
qualification      Intermediate2
year                        2015
Subject                   German
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                  24
grade_type          letter_group
Name: 138933, dtype: object
qualification      Intermediate2
year                        2015
Subject                   German
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                  12
grade_type          letter_group
Name: 138932, dtype: object
qualification              Intermediate2
year                                2015
Subject            Graphic Communication
NumberOfCentres                      NaN
gender                            female
grade                                A-C
NoOfStudents                          10
grade_type                  letter_group
Name: 138935, dtype: object
qualification              Intermediate2
year                                2015
Subject            Graphic Communication
NumberOfCentres                      NaN
gender                              male
grade                                A-C
NoOfStudents                          44
grade_type                  letter_group
Name: 138934, dtype: object
qualification      Intermediate2
year                        2015
Subject                 Gàidhlig
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                 NaN
grade_type          letter_group
Name: 138927, dtype: object
qualification      Intermediate2
year                        2015
Subject                 Gàidhlig
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                 NaN
grade_type          letter_group
Name: 138926, dtype: object
qualification                           Intermediate2
year                                             2015
Subject            Health and Safety in Care Settings
NumberOfCentres                                   NaN
gender                                         female
grade                                             A-C
NoOfStudents                                      170
grade_type                               letter_group
Name: 138937, dtype: object
qualification                           Intermediate2
year                                             2015
Subject            Health and Safety in Care Settings
NumberOfCentres                                   NaN
gender                                           male
grade                                             A-C
NoOfStudents                                        7
grade_type                               letter_group
Name: 138936, dtype: object
qualification      Intermediate2
year                        2015
Subject                  History
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                 135
grade_type          letter_group
Name: 138939, dtype: object
qualification      Intermediate2
year                        2015
Subject                  History
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                 117
grade_type          letter_group
Name: 138938, dtype: object
qualification                                   Intermediate2
year                                                     2015
Subject            Home Economics: Health and Food Technology
NumberOfCentres                                           NaN
gender                                                 female
grade                                                     A-C
NoOfStudents                                               12
grade_type                                       letter_group
Name: 138941, dtype: object
qualification                                   Intermediate2
year                                                     2015
Subject            Home Economics: Health and Food Technology
NumberOfCentres                                           NaN
gender                                                   male
grade                                                     A-C
NoOfStudents                                              NaN
grade_type                                       letter_group
Name: 138940, dtype: object
qualification                         Intermediate2
year                                           2015
Subject            Hospitality - General Operations
NumberOfCentres                                 NaN
gender                                       female
grade                                           A-C
NoOfStudents                                     11
grade_type                             letter_group
Name: 138943, dtype: object
qualification                         Intermediate2
year                                           2015
Subject            Hospitality - General Operations
NumberOfCentres                                 NaN
gender                                         male
grade                                           A-C
NoOfStudents                                     13
grade_type                             letter_group
Name: 138942, dtype: object
qualification                           Intermediate2
year                                             2015
Subject            Hospitality - Professional Cookery
NumberOfCentres                                   NaN
gender                                         female
grade                                             A-C
NoOfStudents                                       17
grade_type                               letter_group
Name: 138945, dtype: object
qualification                           Intermediate2
year                                             2015
Subject            Hospitality - Professional Cookery
NumberOfCentres                                   NaN
gender                                           male
grade                                             A-C
NoOfStudents                                       12
grade_type                               letter_group
Name: 138944, dtype: object
qualification                       Intermediate2
year                                         2015
Subject            Hospitality: Practical Cookery
NumberOfCentres                               NaN
gender                                     female
grade                                         A-C
NoOfStudents                                  118
grade_type                           letter_group
Name: 138947, dtype: object
qualification                       Intermediate2
year                                         2015
Subject            Hospitality: Practical Cookery
NumberOfCentres                               NaN
gender                                       male
grade                                         A-C
NoOfStudents                                  110
grade_type                           letter_group
Name: 138946, dtype: object
qualification            Intermediate2
year                              2015
Subject            Information Systems
NumberOfCentres                    NaN
gender                          female
grade                              A-C
NoOfStudents                        12
grade_type                letter_group
Name: 138949, dtype: object
qualification            Intermediate2
year                              2015
Subject            Information Systems
NumberOfCentres                    NaN
gender                            male
grade                              A-C
NoOfStudents                        37
grade_type                letter_group
Name: 138948, dtype: object
qualification      Intermediate2
year                        2015
Subject                  Italian
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                  12
grade_type          letter_group
Name: 138951, dtype: object
qualification      Intermediate2
year                        2015
Subject                  Italian
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                   6
grade_type          letter_group
Name: 138950, dtype: object
qualification      Intermediate2
year                        2015
Subject                    Latin
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                   9
grade_type          letter_group
Name: 138953, dtype: object
qualification      Intermediate2
year                        2015
Subject                    Latin
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                   5
grade_type          letter_group
Name: 138952, dtype: object
qualification                         Intermediate2
year                                           2015
Subject            Managing Environmental Resources
NumberOfCentres                                 NaN
gender                                       female
grade                                           A-C
NoOfStudents                                      4
grade_type                             letter_group
Name: 138955, dtype: object
qualification                         Intermediate2
year                                           2015
Subject            Managing Environmental Resources
NumberOfCentres                                 NaN
gender                                         male
grade                                           A-C
NoOfStudents                                     20
grade_type                             letter_group
Name: 138954, dtype: object
qualification      Intermediate2
year                        2015
Subject              Mathematics
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                 709
grade_type          letter_group
Name: 138957, dtype: object
qualification      Intermediate2
year                        2015
Subject              Mathematics
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                 540
grade_type          letter_group
Name: 138956, dtype: object
qualification      Intermediate2
year                        2015
Subject            Media Studies
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                  32
grade_type          letter_group
Name: 138959, dtype: object
qualification      Intermediate2
year                        2015
Subject            Media Studies
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                  50
grade_type          letter_group
Name: 138958, dtype: object
qualification       Intermediate2
year                         2015
Subject            Modern Studies
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   52
grade_type           letter_group
Name: 138961, dtype: object
qualification       Intermediate2
year                         2015
Subject            Modern Studies
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                   59
grade_type           letter_group
Name: 138960, dtype: object
qualification      Intermediate2
year                        2015
Subject                    Music
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                  33
grade_type          letter_group
Name: 138963, dtype: object
qualification      Intermediate2
year                        2015
Subject                    Music
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                  15
grade_type          letter_group
Name: 138962, dtype: object
qualification      Intermediate2
year                        2015
Subject               Philosophy
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                  24
grade_type          letter_group
Name: 138965, dtype: object
qualification      Intermediate2
year                        2015
Subject               Philosophy
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                  19
grade_type          letter_group
Name: 138964, dtype: object
qualification           Intermediate2
year                             2015
Subject            Physical Education
NumberOfCentres                   NaN
gender                         female
grade                             A-C
NoOfStudents                       78
grade_type               letter_group
Name: 138967, dtype: object
qualification           Intermediate2
year                             2015
Subject            Physical Education
NumberOfCentres                   NaN
gender                           male
grade                             A-C
NoOfStudents                      221
grade_type               letter_group
Name: 138966, dtype: object
qualification      Intermediate2
year                        2015
Subject                  Physics
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                 124
grade_type          letter_group
Name: 138969, dtype: object
qualification      Intermediate2
year                        2015
Subject                  Physics
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                 178
grade_type          letter_group
Name: 138968, dtype: object
qualification       Intermediate2
year                         2015
Subject            Product Design
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                   14
grade_type           letter_group
Name: 138971, dtype: object
qualification       Intermediate2
year                         2015
Subject            Product Design
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                   67
grade_type           letter_group
Name: 138970, dtype: object
qualification      Intermediate2
year                        2015
Subject               Psychology
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                 152
grade_type          letter_group
Name: 138973, dtype: object
qualification      Intermediate2
year                        2015
Subject               Psychology
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                  49
grade_type          letter_group
Name: 138972, dtype: object
qualification                                   Intermediate2
year                                                     2015
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN
gender                                                 female
grade                                                     A-C
NoOfStudents                                               68
grade_type                                       letter_group
Name: 138975, dtype: object
qualification                                   Intermediate2
year                                                     2015
Subject            Religious, Moral and Philosophical Studies
NumberOfCentres                                           NaN

qualification         National5
year                       2020
Subject              Accounting
NumberOfCentres             NaN
gender                      all
grade                       A-B
NoOfStudents                674
grade_type         letter_group
Name: 158365, dtype: object
qualification         National5
year                       2020
Subject              Accounting
NumberOfCentres             NaN
gender                      all
grade                       A-C
NoOfStudents                794
grade_type         letter_group
Name: 140125, dtype: object
qualification         National5
year                       2020
Subject              Accounting
NumberOfCentres             NaN
gender                      all
grade                       A-D
NoOfStudents                849
grade_type         letter_group
Name: 159244, dtype: object
qualification         National5
year                       2020
Subject              Accounting
NumberOfCentres             NaN
gender                   female
grade                       A-B
NoOfStudents                353
grade_type         letter_group
Name: 158364, dtype: object
qualification         National5
year                       2020
Subject              Accounting
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                408
grade_type         letter_group
Name: 140124, dtype: object
qualification         National5
year                       2020
Subject              Accounting
NumberOfCentres             NaN
gender                   female
grade                       A-D
NoOfStudents                428
grade_type         letter_group
Name: 159243, dtype: object
qualification         National5
year                       2020
Subject              Accounting
NumberOfCentres             NaN
gender                     male
grade                       A-B
NoOfStudents                354
grade_type         letter_group
Name: 158363, dtype: object
qualification         National5
year                       2020
Subject              Accounting
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                422
grade_type         letter_group
Name: 140123, dtype: object
qualification         National5
year                       2020
Subject              Accounting
NumberOfCentres             NaN
gender                     male
grade                       A-D
NoOfStudents                452
grade_type         letter_group
Name: 159242, dtype: object
qualification                  National5
year                                2020
Subject            Administration and IT
NumberOfCentres                      NaN
gender                               all
grade                                A-B
NoOfStudents                        3168
grade_type                  letter_group
Name: 158368, dtype: object
qualification                  National5
year                                2020
Subject            Administration and IT
NumberOfCentres                      NaN
gender                               all
grade                                A-C
NoOfStudents                        4238
grade_type                  letter_group
Name: 140128, dtype: object
qualification                  National5
year                                2020
Subject            Administration and IT
NumberOfCentres                      NaN
gender                               all
grade                                A-D
NoOfStudents                        4850
grade_type                  letter_group
Name: 159247, dtype: object
qualification                  National5
year                                2020
Subject            Administration and IT
NumberOfCentres                      NaN
gender                            female
grade                                A-B
NoOfStudents                        2350
grade_type                  letter_group
Name: 158367, dtype: object
qualification                  National5
year                                2020
Subject            Administration and IT
NumberOfCentres                      NaN
gender                            female
grade                                A-C
NoOfStudents                        3091
grade_type                  letter_group
Name: 140127, dtype: object
qualification                  National5
year                                2020
Subject            Administration and IT
NumberOfCentres                      NaN
gender                            female
grade                                A-D
NoOfStudents                        3251
grade_type                  letter_group
Name: 159246, dtype: object
qualification                  National5
year                                2020
Subject            Administration and IT
NumberOfCentres                      NaN
gender                              male
grade                                A-B
NoOfStudents                        1180
grade_type                  letter_group
Name: 158366, dtype: object
qualification                  National5
year                                2020
Subject            Administration and IT
NumberOfCentres                      NaN
gender                              male
grade                                A-C
NoOfStudents                        1693
grade_type                  letter_group
Name: 140126, dtype: object
qualification                  National5
year                                2020
Subject            Administration and IT
NumberOfCentres                      NaN
gender                              male
grade                                A-D
NoOfStudents                        1839
grade_type                  letter_group
Name: 159245, dtype: object
qualification                        National5
year                                      2020
Subject            Applications of Mathematics
NumberOfCentres                            NaN
gender                                     all
grade                                      A-B
NoOfStudents                              4724
grade_type                        letter_group
Name: 158371, dtype: object
qualification                        National5
year                                      2020
Subject            Applications of Mathematics
NumberOfCentres                            NaN
gender                                     all
grade                                      A-C
NoOfStudents                              7023
grade_type                        letter_group
Name: 140131, dtype: object
qualification                        National5
year                                      2020
Subject            Applications of Mathematics
NumberOfCentres                            NaN
gender                                     all
grade                                      A-D
NoOfStudents                              8737
grade_type                        letter_group
Name: 159250, dtype: object
qualification                        National5
year                                      2020
Subject            Applications of Mathematics
NumberOfCentres                            NaN
gender                                  female
grade                                      A-B
NoOfStudents                              2545
grade_type                        letter_group
Name: 158370, dtype: object
qualification                        National5
year                                      2020
Subject            Applications of Mathematics
NumberOfCentres                            NaN
gender                                  female
grade                                      A-C
NoOfStudents                              3934
grade_type                        letter_group
Name: 140130, dtype: object
qualification                        National5
year                                      2020
Subject            Applications of Mathematics
NumberOfCentres                            NaN
gender                                  female
grade                                      A-D
NoOfStudents                              4608
grade_type                        letter_group
Name: 159249, dtype: object
qualification                        National5
year                                      2020
Subject            Applications of Mathematics
NumberOfCentres                            NaN
gender                                    male
grade                                      A-B
NoOfStudents                              2536
grade_type                        letter_group
Name: 158369, dtype: object
qualification                        National5
year                                      2020
Subject            Applications of Mathematics
NumberOfCentres                            NaN
gender                                    male
grade                                      A-C
NoOfStudents                              3916
grade_type                        letter_group
Name: 140129, dtype: object
qualification                        National5
year                                      2020
Subject            Applications of Mathematics
NumberOfCentres                            NaN
gender                                    male
grade                                      A-D
NoOfStudents                              4534
grade_type                        letter_group
Name: 159248, dtype: object
qualification           National5
year                         2020
Subject            Art and Design
NumberOfCentres               NaN
gender                        all
grade                         A-B
NoOfStudents                 7351
grade_type           letter_group
Name: 158374, dtype: object
qualification           National5
year                         2020
Subject            Art and Design
NumberOfCentres               NaN
gender                        all
grade                         A-C
NoOfStudents                 9079
grade_type           letter_group
Name: 140134, dtype: object
qualification           National5
year                         2020
Subject            Art and Design
NumberOfCentres               NaN
gender                        all
grade                         A-D
NoOfStudents                 9729
grade_type           letter_group
Name: 159253, dtype: object
qualification           National5
year                         2020
Subject            Art and Design
NumberOfCentres               NaN
gender                     female
grade                         A-B
NoOfStudents                 6008
grade_type           letter_group
Name: 158373, dtype: object
qualification           National5
year                         2020
Subject            Art and Design
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                 7248
grade_type           letter_group
Name: 140133, dtype: object
qualification           National5
year                         2020
Subject            Art and Design
NumberOfCentres               NaN
gender                     female
grade                         A-D
NoOfStudents                 7394
grade_type           letter_group
Name: 159252, dtype: object
qualification           National5
year                         2020
Subject            Art and Design
NumberOfCentres               NaN
gender                       male
grade                         A-B
NoOfStudents                 1607
grade_type           letter_group
Name: 158372, dtype: object
qualification           National5
year                         2020
Subject            Art and Design
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                 2308
grade_type           letter_group
Name: 140132, dtype: object
qualification           National5
year                         2020
Subject            Art and Design
NumberOfCentres               NaN
gender                       male
grade                         A-D
NoOfStudents                 2422
grade_type           letter_group
Name: 159251, dtype: object
qualification         National5
year                       2020
Subject                 Biology
NumberOfCentres             NaN
gender                      all
grade                       A-B
NoOfStudents              11965
grade_type         letter_group
Name: 158377, dtype: object
qualification         National5
year                       2020
Subject                 Biology
NumberOfCentres             NaN
gender                      all
grade                       A-C
NoOfStudents              16154
grade_type         letter_group
Name: 140137, dtype: object
qualification         National5
year                       2020
Subject                 Biology
NumberOfCentres             NaN
gender                      all
grade                       A-D
NoOfStudents              19733
grade_type         letter_group
Name: 159256, dtype: object
qualification         National5
year                       2020
Subject                 Biology
NumberOfCentres             NaN
gender                   female
grade                       A-B
NoOfStudents               8462
grade_type         letter_group
Name: 158376, dtype: object
qualification         National5
year                       2020
Subject                 Biology
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents              12060
grade_type         letter_group
Name: 140136, dtype: object
qualification         National5
year                       2020
Subject                 Biology
NumberOfCentres             NaN
gender                   female
grade                       A-D
NoOfStudents              13656
grade_type         letter_group
Name: 159255, dtype: object
qualification         National5
year                       2020
Subject                 Biology
NumberOfCentres             NaN
gender                     male
grade                       A-B
NoOfStudents               4259
grade_type         letter_group
Name: 158375, dtype: object
qualification         National5
year                       2020
Subject                 Biology
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               6102
grade_type         letter_group
Name: 140135, dtype: object
qualification         National5
year                       2020
Subject                 Biology
NumberOfCentres             NaN
gender                     male
grade                       A-D
NoOfStudents               6997
grade_type         letter_group
Name: 159254, dtype: object
qualification                National5
year                              2020
Subject            Business Management
NumberOfCentres                    NaN
gender                             all
grade                              A-B
NoOfStudents                      4800
grade_type                letter_group
Name: 158380, dtype: object
qualification                National5
year                              2020
Subject            Business Management
NumberOfCentres                    NaN
gender                             all
grade                              A-C
NoOfStudents                      6528
grade_type                letter_group
Name: 140140, dtype: object
qualification                National5
year                              2020
Subject            Business Management
NumberOfCentres                    NaN
gender                             all
grade                              A-D
NoOfStudents                      7419
grade_type                letter_group
Name: 159259, dtype: object
qualification                National5
year                              2020
Subject            Business Management
NumberOfCentres                    NaN
gender                          female
grade                              A-B
NoOfStudents                      2635
grade_type                letter_group
Name: 158379, dtype: object
qualification                National5
year                              2020
Subject            Business Management
NumberOfCentres                    NaN
gender                          female
grade                              A-C
NoOfStudents                      3497
grade_type                letter_group
Name: 140139, dtype: object
qualification                National5
year                              2020
Subject            Business Management
NumberOfCentres                    NaN
gender                          female
grade                              A-D
NoOfStudents                      3727
grade_type                letter_group
Name: 159258, dtype: object
qualification                National5
year                              2020
Subject            Business Management
NumberOfCentres                    NaN
gender                            male
grade                              A-B
NoOfStudents                      2446
grade_type                letter_group
Name: 158378, dtype: object
qualification                National5
year                              2020
Subject            Business Management
NumberOfCentres                    NaN
gender                            male
grade                              A-C
NoOfStudents                      3539
grade_type                letter_group
Name: 140138, dtype: object
qualification                National5
year                              2020
Subject            Business Management
NumberOfCentres                    NaN
gender                            male
grade                              A-D
NoOfStudents                      3901
grade_type                letter_group
Name: 159257, dtype: object
qualification         National5
year                       2020
Subject                    Care
NumberOfCentres             NaN
gender                      all
grade                       A-B
NoOfStudents                287
grade_type         letter_group
Name: 158383, dtype: object
qualification         National5
year                       2020
Subject                    Care
NumberOfCentres             NaN
gender                      all
grade                       A-C
NoOfStudents                389
grade_type         letter_group
Name: 140143, dtype: object
qualification         National5
year                       2020
Subject                    Care
NumberOfCentres             NaN
gender                      all
grade                       A-D
NoOfStudents                437
grade_type         letter_group
Name: 159262, dtype: object
qualification         National5
year                       2020
Subject                    Care
NumberOfCentres             NaN
gender                   female
grade                       A-B
NoOfStudents                274
grade_type         letter_group
Name: 158382, dtype: object
qualification         National5
year                       2020
Subject                    Care
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                365
grade_type         letter_group
Name: 140142, dtype: object
qualification         National5
year                       2020
Subject                    Care
NumberOfCentres             NaN
gender                   female
grade                       A-D
NoOfStudents                397
grade_type         letter_group
Name: 159261, dtype: object
qualification         National5
year                       2020
Subject                    Care
NumberOfCentres             NaN
gender                     male
grade                       A-B
NoOfStudents                 23
grade_type         letter_group
Name: 158381, dtype: object
qualification         National5
year                       2020
Subject                    Care
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 33
grade_type         letter_group
Name: 140141, dtype: object

Name: 158458, dtype: object
qualification         National5
year                       2020
Subject                   Media
NumberOfCentres             NaN
gender                      all
grade                       A-C
NoOfStudents                703
grade_type         letter_group
Name: 140218, dtype: object
qualification         National5
year                       2020
Subject                   Media
NumberOfCentres             NaN
gender                      all
grade                       A-D
NoOfStudents                858
grade_type         letter_group
Name: 159337, dtype: object
qualification         National5
year                       2020
Subject                   Media
NumberOfCentres             NaN
gender                   female
grade                       A-B
NoOfStudents                361
grade_type         letter_group
Name: 158457, dtype: object
qualification         National5
year                       2020
Subject                   Media
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                464
grade_type         letter_group
Name: 140217, dtype: object
qualification         National5
year                       2020
Subject                   Media
NumberOfCentres             NaN
gender                   female
grade                       A-D
NoOfStudents                482
grade_type         letter_group
Name: 159336, dtype: object
qualification         National5
year                       2020
Subject                   Media
NumberOfCentres             NaN
gender                     male
grade                       A-B
NoOfStudents                272
grade_type         letter_group
Name: 158456, dtype: object
qualification         National5
year                       2020
Subject                   Media
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                427
grade_type         letter_group
Name: 140216, dtype: object
qualification         National5
year                       2020
Subject                   Media
NumberOfCentres             NaN
gender                     male
grade                       A-D
NoOfStudents                469
grade_type         letter_group
Name: 159335, dtype: object
qualification           National5
year                         2020
Subject            Modern Studies
NumberOfCentres               NaN
gender                        all
grade                         A-B
NoOfStudents                 6805
grade_type           letter_group
Name: 158461, dtype: object
qualification           National5
year                         2020
Subject            Modern Studies
NumberOfCentres               NaN
gender                        all
grade                         A-C
NoOfStudents                 9314
grade_type           letter_group
Name: 140221, dtype: object
qualification           National5
year                         2020
Subject            Modern Studies
NumberOfCentres               NaN
gender                        all
grade                         A-D
NoOfStudents                11006
grade_type           letter_group
Name: 159340, dtype: object
qualification           National5
year                         2020
Subject            Modern Studies
NumberOfCentres               NaN
gender                     female
grade                         A-B
NoOfStudents                 4866
grade_type           letter_group
Name: 158460, dtype: object
qualification           National5
year                         2020
Subject            Modern Studies
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                 6484
grade_type           letter_group
Name: 140220, dtype: object
qualification           National5
year                         2020
Subject            Modern Studies
NumberOfCentres               NaN
gender                     female
grade                         A-D
NoOfStudents                 6985
grade_type           letter_group
Name: 159339, dtype: object
qualification           National5
year                         2020
Subject            Modern Studies
NumberOfCentres               NaN
gender                       male
grade                         A-B
NoOfStudents                 3056
grade_type           letter_group
Name: 158459, dtype: object
qualification           National5
year                         2020
Subject            Modern Studies
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                 4375
grade_type           letter_group
Name: 140219, dtype: object
qualification           National5
year                         2020
Subject            Modern Studies
NumberOfCentres               NaN
gender                       male
grade                         A-D
NoOfStudents                 4826
grade_type           letter_group
Name: 159338, dtype: object
qualification         National5
year                       2020
Subject                   Music
NumberOfCentres             NaN
gender                      all
grade                       A-B
NoOfStudents               6427
grade_type         letter_group
Name: 158464, dtype: object
qualification         National5
year                       2020
Subject                   Music
NumberOfCentres             NaN
gender                      all
grade                       A-C
NoOfStudents               7336
grade_type         letter_group
Name: 140224, dtype: object
qualification         National5
year                       2020
Subject                   Music
NumberOfCentres             NaN
gender                      all
grade                       A-D
NoOfStudents               7569
grade_type         letter_group
Name: 159343, dtype: object
qualification         National5
year                       2020
Subject                   Music
NumberOfCentres             NaN
gender                   female
grade                       A-B
NoOfStudents               3675
grade_type         letter_group
Name: 158463, dtype: object
qualification         National5
year                       2020
Subject                   Music
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               4130
grade_type         letter_group
Name: 140223, dtype: object
qualification         National5
year                       2020
Subject                   Music
NumberOfCentres             NaN
gender                   female
grade                       A-D
NoOfStudents               4203
grade_type         letter_group
Name: 159342, dtype: object
qualification         National5
year                       2020
Subject                   Music
NumberOfCentres             NaN
gender                     male
grade                       A-B
NoOfStudents               2803
grade_type         letter_group
Name: 158462, dtype: object
qualification         National5
year                       2020
Subject                   Music
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               3298
grade_type         letter_group
Name: 140222, dtype: object
qualification         National5
year                       2020
Subject                   Music
NumberOfCentres             NaN
gender                     male
grade                       A-D
NoOfStudents               3383
grade_type         letter_group
Name: 159341, dtype: object
qualification             National5
year                           2020
Subject            Music Technology
NumberOfCentres                 NaN
gender                          all
grade                           A-B
NoOfStudents                    865
grade_type             letter_group
Name: 158467, dtype: object
qualification             National5
year                           2020
Subject            Music Technology
NumberOfCentres                 NaN
gender                          all
grade                           A-C
NoOfStudents                   1059
grade_type             letter_group
Name: 140227, dtype: object
qualification             National5
year                           2020
Subject            Music Technology
NumberOfCentres                 NaN
gender                          all
grade                           A-D
NoOfStudents                   1139
grade_type             letter_group
Name: 159346, dtype: object
qualification             National5
year                           2020
Subject            Music Technology
NumberOfCentres                 NaN
gender                       female
grade                           A-B
NoOfStudents                    245
grade_type             letter_group
Name: 158466, dtype: object
qualification             National5
year                           2020
Subject            Music Technology
NumberOfCentres                 NaN
gender                       female
grade                           A-C
NoOfStudents                    289
grade_type             letter_group
Name: 140226, dtype: object
qualification             National5
year                           2020
Subject            Music Technology
NumberOfCentres                 NaN
gender                       female
grade                           A-D
NoOfStudents                    297
grade_type             letter_group
Name: 159345, dtype: object
qualification             National5
year                           2020
Subject            Music Technology
NumberOfCentres                 NaN
gender                         male
grade                           A-B
NoOfStudents                    650
grade_type             letter_group
Name: 158465, dtype: object
qualification             National5
year                           2020
Subject            Music Technology
NumberOfCentres                 NaN
gender                         male
grade                           A-C
NoOfStudents                    823
grade_type             letter_group
Name: 140225, dtype: object
qualification             National5
year                           2020
Subject            Music Technology
NumberOfCentres                 NaN
gender                         male
grade                           A-D
NoOfStudents                    857
grade_type             letter_group
Name: 159344, dtype: object
qualification         National5
year                       2020
Subject              Philosophy
NumberOfCentres             NaN
gender                      all
grade                       A-B
NoOfStudents                176
grade_type         letter_group
Name: 158470, dtype: object
qualification         National5
year                       2020
Subject              Philosophy
NumberOfCentres             NaN
gender                      all
grade                       A-C
NoOfStudents                237
grade_type         letter_group
Name: 140230, dtype: object
qualification         National5
year                       2020
Subject              Philosophy
NumberOfCentres             NaN
gender                      all
grade                       A-D
NoOfStudents                265
grade_type         letter_group
Name: 159349, dtype: object
qualification         National5
year                       2020
Subject              Philosophy
NumberOfCentres             NaN
gender                   female
grade                       A-B
NoOfStudents                128
grade_type         letter_group
Name: 158469, dtype: object
qualification         National5
year                       2020
Subject              Philosophy
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                165
grade_type         letter_group
Name: 140229, dtype: object
qualification         National5
year                       2020
Subject              Philosophy
NumberOfCentres             NaN
gender                   female
grade                       A-D
NoOfStudents                182
grade_type         letter_group
Name: 159348, dtype: object
qualification         National5
year                       2020
Subject              Philosophy
NumberOfCentres             NaN
gender                     male
grade                       A-B
NoOfStudents                 59
grade_type         letter_group
Name: 158468, dtype: object
qualification         National5
year                       2020
Subject              Philosophy
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 88
grade_type         letter_group
Name: 140228, dtype: object
qualification         National5
year                       2020
Subject              Philosophy
NumberOfCentres             NaN
gender                     male
grade                       A-D
NoOfStudents                103
grade_type         letter_group
Name: 159347, dtype: object
qualification               National5
year                             2020
Subject            Physical Education
NumberOfCentres                   NaN
gender                            all
grade                             A-B
NoOfStudents                    13636
grade_type               letter_group
Name: 158473, dtype: object
qualification               National5
year                             2020
Subject            Physical Education
NumberOfCentres                   NaN
gender                            all
grade                             A-C
NoOfStudents                    16327
grade_type               letter_group
Name: 140233, dtype: object
qualification               National5
year                             2020
Subject            Physical Education
NumberOfCentres                   NaN
gender                            all
grade                             A-D
NoOfStudents                    17056
grade_type               letter_group
Name: 159352, dtype: object
qualification               National5
year                             2020
Subject            Physical Education
NumberOfCentres                   NaN
gender                         female
grade                             A-B
NoOfStudents                     5223
grade_type               letter_group
Name: 158472, dtype: object
qualification               National5
year                             2020
Subject            Physical Education
NumberOfCentres                   NaN
gender                         female
grade                             A-C
NoOfStudents                     5830
grade_type               letter_group
Name: 140232, dtype: object
qualification               National5
year                             2020
Subject            Physical Education
NumberOfCentres                   NaN
gender                         female
grade                             A-D
NoOfStudents                     5927
grade_type               letter_group
Name: 159351, dtype: object
qualification               National5
year                             2020
Subject            Physical Education
NumberOfCentres                   NaN
gender                           male
grade                             A-B
NoOfStudents                     9480
grade_type               letter_group
Name: 158471, dtype: object
qualification               National5
year                             2020
Subject            Physical Education
NumberOfCentres                   NaN
gender                           male
grade                             A-C
NoOfStudents                    10992
grade_type               letter_group
Name: 140231, dtype: object
qualification               National5
year                             2020
Subject            Physical Education
NumberOfCentres                   NaN
gender                           male
grade                             A-D
NoOfStudents                    11215
grade_type               letter_group
Name: 159350, dtype: object
qualification         National5
year                       2020
Subject                 Physics
NumberOfCentres             NaN
gender                      all
grade                       A-B
NoOfStudents               7775
grade_type         letter_group
Name: 158476, dtype: object
qualification         National5
year                       2020
Subject                 Physics
NumberOfCentres             NaN
gender                      all
grade                       A-C
NoOfStudents              10439
grade_type         letter_group
Name: 140236, dtype: object
qualification         National5
year                       2020
Subject                 Physics
NumberOfCentres             NaN
gender                      all
grade                       A-D
NoOfStudents              12361
grade_type         letter_group
Name: 159355, dtype: object
qualification         National5
year                       2020
Subject                 Physics
NumberOfCentres             NaN
gender                   female
grade                       A-B
NoOfStudents               2852
grade_type         letter_group
Name: 158475, dtype: object
qualification         National5
year                       2020
Subject                 Physics
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               3581
grade_type         letter_group
Name: 140235, dtype: object
qualification         National5
year                       2020
Subject                 Physics
NumberOfCentres             NaN
gender                   female
grade                       A-D
NoOfStudents               3848
grade_type         letter_group
Name: 159354, dtype: object
qualification         National5
year                       2020
Subject                 Physics
NumberOfCentres             NaN
gender                     male
grade                       A-B
NoOfStudents               5850
grade_type         letter_group
Name: 158474, dtype: object
qualification         National5
year                       2020
Subject                 Physics
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               8158
grade_type         letter_group
Name: 140234, dtype: object
qualification         National5
year                       2020
Subject                 Physics
NumberOfCentres             NaN
gender                     male
grade                       A-D
NoOfStudents               9150
grade_type         letter_group
Name: 159353, dtype: object
qualification                                              National5
year                                                            2020
Subject            Practical Cake Craft (Hospitality: Practical C...
NumberOfCentres                                                  NaN
gender                                                           all
grade                                                            A-B
NoOfStudents                                                     584
grade_type                                              letter_group
Name: 158479, dtype: object
qualification                                              National5
year                                                            2020
Subject            Practical Cake Craft (Hospitality: Practical C...
NumberOfCentres                                                  NaN
gender                                                           all
grade                                                            A-C
NoOfStudents                                                     904
grade_type                                              letter_group
Name: 140239, dtype: object
qualification                                              National5
year                                                            2020
Subject            Practical Cake Craft (Hospitality: Practical C...
NumberOfCentres                                                  NaN

Name: 159570, dtype: object
qualification                National5
year                              2021
Subject            Engineering Science
NumberOfCentres                    NaN
gender                            male
grade                              A-B
NoOfStudents                      1131
grade_type                letter_group
Name: 158795, dtype: object
qualification                National5
year                              2021
Subject            Engineering Science
NumberOfCentres                    NaN
gender                            male
grade                              A-C
NoOfStudents                      1407
grade_type                letter_group
Name: 140555, dtype: object
qualification                National5
year                              2021
Subject            Engineering Science
NumberOfCentres                    NaN
gender                            male
grade                              A-D
NoOfStudents                      1549
grade_type                letter_group
Name: 159569, dtype: object
qualification         National5
year                       2021
Subject                 English
NumberOfCentres             NaN
gender                      all
grade                       A-B
NoOfStudents              33571
grade_type         letter_group
Name: 158800, dtype: object
qualification         National5
year                       2021
Subject                 English
NumberOfCentres             NaN
gender                      all
grade                       A-C
NoOfStudents              42632
grade_type         letter_group
Name: 140560, dtype: object
qualification         National5
year                       2021
Subject                 English
NumberOfCentres             NaN
gender                      all
grade                       A-D
NoOfStudents              45679
grade_type         letter_group
Name: 159574, dtype: object
qualification         National5
year                       2021
Subject                 English
NumberOfCentres             NaN
gender                   female
grade                       A-B
NoOfStudents              18528
grade_type         letter_group
Name: 158799, dtype: object
qualification         National5
year                       2021
Subject                 English
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents              22167
grade_type         letter_group
Name: 140559, dtype: object
qualification         National5
year                       2021
Subject                 English
NumberOfCentres             NaN
gender                   female
grade                       A-D
NoOfStudents              23332
grade_type         letter_group
Name: 159573, dtype: object
qualification         National5
year                       2021
Subject                 English
NumberOfCentres             NaN
gender                     male
grade                       A-B
NoOfStudents              15031
grade_type         letter_group
Name: 158798, dtype: object
qualification         National5
year                       2021
Subject                 English
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents              20453
grade_type         letter_group
Name: 140558, dtype: object
qualification         National5
year                       2021
Subject                 English
NumberOfCentres             NaN
gender                     male
grade                       A-D
NoOfStudents              22334
grade_type         letter_group
Name: 159572, dtype: object
qualification                                    National5
year                                                  2021
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                                 all
grade                                                  A-B
NoOfStudents                                           622
grade_type                                    letter_group
Name: 158803, dtype: object
qualification                                    National5
year                                                  2021
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                                 all
grade                                                  A-C
NoOfStudents                                           826
grade_type                                    letter_group
Name: 140563, dtype: object
qualification                                    National5
year                                                  2021
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                                 all
grade                                                  A-D
NoOfStudents                                           887
grade_type                                    letter_group
Name: 159577, dtype: object
qualification                                    National5
year                                                  2021
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                              female
grade                                                  A-B
NoOfStudents                                           382
grade_type                                    letter_group
Name: 158802, dtype: object
qualification                                    National5
year                                                  2021
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                              female
grade                                                  A-C
NoOfStudents                                           498
grade_type                                    letter_group
Name: 140562, dtype: object
qualification                                    National5
year                                                  2021
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                              female
grade                                                  A-D
NoOfStudents                                           534
grade_type                                    letter_group
Name: 159576, dtype: object
qualification                                    National5
year                                                  2021
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                                male
grade                                                  A-B
NoOfStudents                                           239
grade_type                                    letter_group
Name: 158801, dtype: object
qualification                                    National5
year                                                  2021
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                                male
grade                                                  A-C
NoOfStudents                                           327
grade_type                                    letter_group
Name: 140561, dtype: object
qualification                                    National5
year                                                  2021
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                                male
grade                                                  A-D
NoOfStudents                                           352
grade_type                                    letter_group
Name: 159575, dtype: object
qualification                  National5
year                                2021
Subject            Environmental Science
NumberOfCentres                      NaN
gender                               all
grade                                A-B
NoOfStudents                         181
grade_type                  letter_group
Name: 158806, dtype: object
qualification                  National5
year                                2021
Subject            Environmental Science
NumberOfCentres                      NaN
gender                               all
grade                                A-C
NoOfStudents                         274
grade_type                  letter_group
Name: 140566, dtype: object
qualification                  National5
year                                2021
Subject            Environmental Science
NumberOfCentres                      NaN
gender                               all
grade                                A-D
NoOfStudents                         322
grade_type                  letter_group
Name: 159580, dtype: object
qualification                  National5
year                                2021
Subject            Environmental Science
NumberOfCentres                      NaN
gender                            female
grade                                A-B
NoOfStudents                          80
grade_type                  letter_group
Name: 158805, dtype: object
qualification                  National5
year                                2021
Subject            Environmental Science
NumberOfCentres                      NaN
gender                            female
grade                                A-C
NoOfStudents                         113
grade_type                  letter_group
Name: 140565, dtype: object
qualification                  National5
year                                2021
Subject            Environmental Science
NumberOfCentres                      NaN
gender                            female
grade                                A-D
NoOfStudents                         133
grade_type                  letter_group
Name: 159579, dtype: object
qualification                  National5
year                                2021
Subject            Environmental Science
NumberOfCentres                      NaN
gender                              male
grade                                A-B
NoOfStudents                         101
grade_type                  letter_group
Name: 158804, dtype: object
qualification                  National5
year                                2021
Subject            Environmental Science
NumberOfCentres                      NaN
gender                              male
grade                                A-C
NoOfStudents                         161
grade_type                  letter_group
Name: 140564, dtype: object
qualification                  National5
year                                2021
Subject            Environmental Science
NumberOfCentres                      NaN
gender                              male
grade                                A-D
NoOfStudents                         189
grade_type                  letter_group
Name: 159578, dtype: object
qualification                           National5
year                                         2021
Subject            Fashion and Textile Technology
NumberOfCentres                               NaN
gender                                        all
grade                                         A-B
NoOfStudents                                  374
grade_type                           letter_group
Name: 158809, dtype: object
qualification                           National5
year                                         2021
Subject            Fashion and Textile Technology
NumberOfCentres                               NaN
gender                                        all
grade                                         A-C
NoOfStudents                                  462
grade_type                           letter_group
Name: 140569, dtype: object
qualification                           National5
year                                         2021
Subject            Fashion and Textile Technology
NumberOfCentres                               NaN
gender                                        all
grade                                         A-D
NoOfStudents                                  497
grade_type                           letter_group
Name: 159583, dtype: object
qualification                           National5
year                                         2021
Subject            Fashion and Textile Technology
NumberOfCentres                               NaN
gender                                     female
grade                                         A-B
NoOfStudents                                  357
grade_type                           letter_group
Name: 158808, dtype: object
qualification                           National5
year                                         2021
Subject            Fashion and Textile Technology
NumberOfCentres                               NaN
gender                                     female
grade                                         A-C
NoOfStudents                                  441
grade_type                           letter_group
Name: 140568, dtype: object
qualification                           National5
year                                         2021
Subject            Fashion and Textile Technology
NumberOfCentres                               NaN
gender                                     female
grade                                         A-D
NoOfStudents                                  474
grade_type                           letter_group
Name: 159582, dtype: object
qualification                           National5
year                                         2021
Subject            Fashion and Textile Technology
NumberOfCentres                               NaN
gender                                       male
grade                                         A-B
NoOfStudents                                   17
grade_type                           letter_group
Name: 158807, dtype: object
qualification                           National5
year                                         2021
Subject            Fashion and Textile Technology
NumberOfCentres                               NaN
gender                                       male
grade                                         A-C
NoOfStudents                                   21
grade_type                           letter_group
Name: 140567, dtype: object
qualification                           National5
year                                         2021
Subject            Fashion and Textile Technology
NumberOfCentres                               NaN
gender                                       male
grade                                         A-D
NoOfStudents                                   23
grade_type                           letter_group
Name: 159581, dtype: object
qualification         National5
year                       2021
Subject                  French
NumberOfCentres             NaN
gender                      all
grade                       A-B
NoOfStudents               5473
grade_type         letter_group
Name: 158812, dtype: object
qualification         National5
year                       2021
Subject                  French
NumberOfCentres             NaN
gender                      all
grade                       A-C
NoOfStudents               6505
grade_type         letter_group
Name: 140572, dtype: object
qualification         National5
year                       2021
Subject                  French
NumberOfCentres             NaN
gender                      all
grade                       A-D
NoOfStudents               6928
grade_type         letter_group
Name: 159586, dtype: object
qualification         National5
year                       2021
Subject                  French
NumberOfCentres             NaN
gender                   female
grade                       A-B
NoOfStudents               3680
grade_type         letter_group
Name: 158811, dtype: object
qualification         National5
year                       2021
Subject                  French
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               4267
grade_type         letter_group
Name: 140571, dtype: object
qualification         National5
year                       2021
Subject                  French
NumberOfCentres             NaN
gender                   female
grade                       A-D
NoOfStudents               4518
grade_type         letter_group
Name: 159585, dtype: object
qualification         National5
year                       2021
Subject                  French
NumberOfCentres             NaN
gender                     male
grade                       A-B
NoOfStudents               1793
grade_type         letter_group
Name: 158810, dtype: object
qualification         National5
year                       2021
Subject                  French
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               2238
grade_type         letter_group
Name: 140570, dtype: object
qualification         National5
year                       2021
Subject                  French
NumberOfCentres             NaN
gender                     male
grade                       A-D
NoOfStudents               2410
grade_type         letter_group
Name: 159584, dtype: object
qualification              National5
year                            2021
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                           all
grade                            A-B
NoOfStudents                     125
grade_type              letter_group
Name: 158815, dtype: object
qualification              National5
year                            2021
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                           all
grade                            A-C
NoOfStudents                     142
grade_type              letter_group
Name: 140575, dtype: object
qualification              National5
year                            2021
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                           all
grade                            A-D
NoOfStudents                     156
grade_type              letter_group
Name: 159589, dtype: object
qualification              National5
year                            2021
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                        female
grade                            A-B
NoOfStudents                      94
grade_type              letter_group
Name: 158814, dtype: object
qualification              National5
year                            2021
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                     108
grade_type              letter_group
Name: 140574, dtype: object
qualification              National5
year                            2021
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                        female
grade                            A-D
NoOfStudents                     117
grade_type              letter_group
Name: 159588, dtype: object
qualification              National5
year                            2021
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                          male
grade                            A-B
NoOfStudents                      31
grade_type              letter_group
Name: 158813, dtype: object

qualification         NewHigher
year                       2015
Subject              Accounting
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                238
grade_type         letter_group
Name: 138989, dtype: object
qualification         NewHigher
year                       2015
Subject              Accounting
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                207
grade_type         letter_group
Name: 138988, dtype: object
qualification                  NewHigher
year                                2015
Subject            Administration and IT
NumberOfCentres                      NaN
gender                            female
grade                                A-C
NoOfStudents                        1899
grade_type                  letter_group
Name: 138991, dtype: object
qualification                  NewHigher
year                                2015
Subject            Administration and IT
NumberOfCentres                      NaN
gender                              male
grade                                A-C
NoOfStudents                         686
grade_type                  letter_group
Name: 138990, dtype: object
qualification           NewHigher
year                         2015
Subject            Art and Design
NumberOfCentres               NaN
gender                     female
grade                         A-C
NoOfStudents                 2940
grade_type           letter_group
Name: 138993, dtype: object
qualification           NewHigher
year                         2015
Subject            Art and Design
NumberOfCentres               NaN
gender                       male
grade                         A-C
NoOfStudents                  635
grade_type           letter_group
Name: 138992, dtype: object
qualification         NewHigher
year                       2015
Subject                 Biology
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               1223
grade_type         letter_group
Name: 138995, dtype: object
qualification         NewHigher
year                       2015
Subject                 Biology
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                637
grade_type         letter_group
Name: 138994, dtype: object
qualification                NewHigher
year                              2015
Subject            Business Management
NumberOfCentres                    NaN
gender                          female
grade                              A-C
NoOfStudents                      2501
grade_type                letter_group
Name: 138997, dtype: object
qualification                NewHigher
year                              2015
Subject            Business Management
NumberOfCentres                    NaN
gender                            male
grade                              A-C
NoOfStudents                      1701
grade_type                letter_group
Name: 138996, dtype: object
qualification         NewHigher
year                       2015
Subject                    Care
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                186
grade_type         letter_group
Name: 138999, dtype: object
qualification         NewHigher
year                       2015
Subject                    Care
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 16
grade_type         letter_group
Name: 138998, dtype: object
qualification         NewHigher
year                       2015
Subject               Chemistry
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               1508
grade_type         letter_group
Name: 139001, dtype: object
qualification         NewHigher
year                       2015
Subject               Chemistry
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               1467
grade_type         letter_group
Name: 139000, dtype: object
qualification                      NewHigher
year                                    2015
Subject            Childcare and Development
NumberOfCentres                          NaN
gender                                female
grade                                    A-C
NoOfStudents                              30
grade_type                      letter_group
Name: 139003, dtype: object
qualification                      NewHigher
year                                    2015
Subject            Childcare and Development
NumberOfCentres                          NaN
gender                                  male
grade                                    A-C
NoOfStudents                             NaN
grade_type                      letter_group
Name: 139002, dtype: object
qualification              NewHigher
year                            2015
Subject            Chinese Languages
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                      13
grade_type              letter_group
Name: 139005, dtype: object
qualification              NewHigher
year                            2015
Subject            Chinese Languages
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                       7
grade_type              letter_group
Name: 139004, dtype: object
qualification              NewHigher
year                            2015
Subject            Classical Studies
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                      43
grade_type              letter_group
Name: 139007, dtype: object
qualification              NewHigher
year                            2015
Subject            Classical Studies
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                      42
grade_type              letter_group
Name: 139006, dtype: object
qualification              NewHigher
year                            2015
Subject            Computing Science
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                     124
grade_type              letter_group
Name: 139009, dtype: object
qualification              NewHigher
year                            2015
Subject            Computing Science
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                     693
grade_type              letter_group
Name: 139008, dtype: object
qualification         NewHigher
year                       2015
Subject                   Dance
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                311
grade_type         letter_group
Name: 139011, dtype: object
qualification         NewHigher
year                       2015
Subject                   Dance
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 14
grade_type         letter_group
Name: 139010, dtype: object
qualification                   NewHigher
year                                 2015
Subject            Design and Manufacture
NumberOfCentres                       NaN
gender                             female
grade                                 A-C
NoOfStudents                          497
grade_type                   letter_group
Name: 139013, dtype: object
qualification                   NewHigher
year                                 2015
Subject            Design and Manufacture
NumberOfCentres                       NaN
gender                               male
grade                                 A-C
NoOfStudents                         1026
grade_type                   letter_group
Name: 139012, dtype: object
qualification         NewHigher
year                       2015
Subject                   Drama
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               1567
grade_type         letter_group
Name: 139015, dtype: object
qualification         NewHigher
year                       2015
Subject                   Drama
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                605
grade_type         letter_group
Name: 139014, dtype: object
qualification         NewHigher
year                       2015
Subject               Economics
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                 55
grade_type         letter_group
Name: 139017, dtype: object
qualification         NewHigher
year                       2015
Subject               Economics
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 91
grade_type         letter_group
Name: 139016, dtype: object
qualification                NewHigher
year                              2015
Subject            Engineering Science
NumberOfCentres                    NaN
gender                          female
grade                              A-C
NoOfStudents                        63
grade_type                letter_group
Name: 139019, dtype: object
qualification                NewHigher
year                              2015
Subject            Engineering Science
NumberOfCentres                    NaN
gender                            male
grade                              A-C
NoOfStudents                       593
grade_type                letter_group
Name: 139018, dtype: object
qualification         NewHigher
year                       2015
Subject                 English
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents              10786
grade_type         letter_group
Name: 139021, dtype: object
qualification         NewHigher
year                       2015
Subject                 English
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               6430
grade_type         letter_group
Name: 139020, dtype: object
qualification                                    NewHigher
year                                                  2015
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                              female
grade                                                  A-C
NoOfStudents                                           129
grade_type                                    letter_group
Name: 139023, dtype: object
qualification                                    NewHigher
year                                                  2015
Subject            English for Speakers of Other Languages
NumberOfCentres                                        NaN
gender                                                male
grade                                                  A-C
NoOfStudents                                            87
grade_type                                    letter_group
Name: 139022, dtype: object
qualification                  NewHigher
year                                2015
Subject            Environmental Science
NumberOfCentres                      NaN
gender                            female
grade                                A-C
NoOfStudents                          29
grade_type                  letter_group
Name: 139025, dtype: object
qualification                  NewHigher
year                                2015
Subject            Environmental Science
NumberOfCentres                      NaN
gender                              male
grade                                A-C
NoOfStudents                          26
grade_type                  letter_group
Name: 139024, dtype: object
qualification                           NewHigher
year                                         2015
Subject            Fashion and Textile Technology
NumberOfCentres                               NaN
gender                                     female
grade                                         A-C
NoOfStudents                                  200
grade_type                           letter_group
Name: 139027, dtype: object
qualification                           NewHigher
year                                         2015
Subject            Fashion and Textile Technology
NumberOfCentres                               NaN
gender                                       male
grade                                         A-C
NoOfStudents                                  NaN
grade_type                           letter_group
Name: 139026, dtype: object
qualification         NewHigher
year                       2015
Subject                  French
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               1795
grade_type         letter_group
Name: 139029, dtype: object
qualification         NewHigher
year                       2015
Subject                  French
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                619
grade_type         letter_group
Name: 139028, dtype: object
qualification              NewHigher
year                            2015
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                        female
grade                            A-C
NoOfStudents                      31
grade_type              letter_group
Name: 139031, dtype: object
qualification              NewHigher
year                            2015
Subject            Gaelic (Learners)
NumberOfCentres                  NaN
gender                          male
grade                            A-C
NoOfStudents                       6
grade_type              letter_group
Name: 139030, dtype: object
qualification         NewHigher
year                       2015
Subject               Geography
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               1558
grade_type         letter_group
Name: 139035, dtype: object
qualification         NewHigher
year                       2015
Subject               Geography
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               1288
grade_type         letter_group
Name: 139034, dtype: object
qualification         NewHigher
year                       2015
Subject                  German
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                364
grade_type         letter_group
Name: 139037, dtype: object
qualification         NewHigher
year                       2015
Subject                  German
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                167
grade_type         letter_group
Name: 139036, dtype: object
qualification                  NewHigher
year                                2015
Subject            Graphic Communication
NumberOfCentres                      NaN
gender                            female
grade                                A-C
NoOfStudents                        1040
grade_type                  letter_group
Name: 139039, dtype: object
qualification                  NewHigher
year                                2015
Subject            Graphic Communication
NumberOfCentres                      NaN
gender                              male
grade                                A-C
NoOfStudents                        2125
grade_type                  letter_group
Name: 139038, dtype: object
qualification         NewHigher
year                       2015
Subject                Gàidhlig
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                 54
grade_type         letter_group
Name: 139033, dtype: object
qualification         NewHigher
year                       2015
Subject                Gàidhlig
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 18
grade_type         letter_group
Name: 139032, dtype: object
qualification                       NewHigher
year                                     2015
Subject            Health and Food Technology
NumberOfCentres                           NaN
gender                                 female
grade                                     A-C
NoOfStudents                              607
grade_type                       letter_group
Name: 139041, dtype: object
qualification                       NewHigher
year                                     2015
Subject            Health and Food Technology
NumberOfCentres                           NaN
gender                                   male
grade                                     A-C
NoOfStudents                               79
grade_type                       letter_group
Name: 139040, dtype: object
qualification         NewHigher
year                       2015
Subject                 History
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents               3850
grade_type         letter_group
Name: 139043, dtype: object
qualification         NewHigher
year                       2015
Subject                 History
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents               2360
grade_type         letter_group
Name: 139042, dtype: object
qualification          NewHigher
year                        2015
Subject            Human Biology
NumberOfCentres              NaN
gender                    female
grade                        A-C
NoOfStudents                 814
grade_type          letter_group
Name: 139045, dtype: object
qualification          NewHigher
year                        2015
Subject            Human Biology
NumberOfCentres              NaN
gender                      male
grade                        A-C
NoOfStudents                 366
grade_type          letter_group
Name: 139044, dtype: object
qualification         NewHigher
year                       2015
Subject                 Italian
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                 77
grade_type         letter_group
Name: 139047, dtype: object
qualification         NewHigher
year                       2015
Subject                 Italian
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 27
grade_type         letter_group
Name: 139046, dtype: object
qualification         NewHigher
year                       2015
Subject                   Latin
NumberOfCentres             NaN
gender                   female
grade                       A-C
NoOfStudents                 89
grade_type         letter_group
Name: 139049, dtype: object
qualification         NewHigher
year                       2015
Subject                   Latin
NumberOfCentres             NaN
gender                     male
grade                       A-C
NoOfStudents                 70
grade_type         letter_group
Name: 139048, dtype: object
qualification         NewHigher

#### Exploring the grades further below

In [32]:
df3.loc[(df3['qualification'] == 'AdvancedHigher') & (df3['year'] == '2004') & (df3['Subject'] == 'Music')]

,qualification,year,Subject,NumberOfCentres,gender,grade,NoOfStudents
64071,AdvancedHigher,2004,Music,266.0,male,Entries,384.0
64072,AdvancedHigher,2004,Music,266.0,male,percentage,43.0
64073,AdvancedHigher,2004,Music,266.0,male,A,182.0
64074,AdvancedHigher,2004,Music,266.0,male,B,112.0
64075,AdvancedHigher,2004,Music,266.0,male,C,60.0
64076,AdvancedHigher,2004,Music,266.0,male,Passes,354.0
64077,AdvancedHigher,2004,Music,266.0,male,COMP,7.0
64078,AdvancedHigher,2004,Music,266.0,female,Entries,508.0
64079,AdvancedHigher,2004,Music,266.0,female,percentage,57.0
64080,AdvancedHigher,2004,Music,266.0,female,A,270.0
64081,AdvancedHigher,2004,Music,266.0,female,B,139.0
64082,AdvancedHigher,2004,Music,266.0,female,C,63.0
64083,AdvancedHigher,2004,Music,266.0,female,Passes,472.0
64084,AdvancedHigher,2004,Music,266.0,female,COMP,15.0
64085,AdvancedHigher,2004,Music,266.0,all,Entries,892.0
64086,AdvancedHigher,2004,Music,266.0,all,A,452.0
64087,AdvancedHigher,2004,Music,266.0,all,B,251.0
64088,AdvancedHigher,2004,Music,266.0,all,C,123.0
64089,AdvancedHigher,2004,Music,266.0,all,Passes,826.0
64090,AdvancedHigher,2004,Music,266.0,all,COMP,22.0

In [14]:
df3.loc[(df3['qualification'] == 'OrdinaryGrade') & (df3['Subject'] == 'Biology') & (df3['year'] == '1993')]

,qualification,year,Subject,NumberOfCentres,gender,grade,NoOfStudents
24486,OrdinaryGrade,1993,Biology,12.0,male,Entries,9.0
24487,OrdinaryGrade,1993,Biology,12.0,male,percentage,0.0
24488,OrdinaryGrade,1993,Biology,12.0,male,1,NaN
24489,OrdinaryGrade,1993,Biology,12.0,male,2,NaN
24490,OrdinaryGrade,1993,Biology,12.0,male,3,2.0
24491,OrdinaryGrade,1993,Biology,12.0,male,4,2.0
24492,OrdinaryGrade,1993,Biology,12.0,male,5,3.0
24493,OrdinaryGrade,1993,Biology,12.0,female,Entries,9.0
24494,OrdinaryGrade,1993,Biology,12.0,female,percentage,0.0
24495,OrdinaryGrade,1993,Biology,12.0,female,1,NaN
24496,OrdinaryGrade,1993,Biology,12.0,female,2,3.0
24497,OrdinaryGrade,1993,Biology,12.0,female,3,2.0
24498,OrdinaryGrade,1993,Biology,12.0,female,4,3.0
24499,OrdinaryGrade,1993,Biology,12.0,female,5,1.0
24500,OrdinaryGrade,1993,Biology,12.0,all,Entries,18.0
24501,OrdinaryGrade,1993,Biology,12.0,all,1,NaN
24502,OrdinaryGrade,1993,Biology,12.0,all,2,3.0
24503,OrdinaryGrade,1993,Biology,12.0,all,3,4.0
24504,OrdinaryGrade,1993,Biology,12.0,all,4,5.0
24505,OrdinaryGrade,1993,Biology,12.0,all,5,4.0

In [12]:
df3.loc[(df3['qualification'] == 'National5') & (~df3['NoOfStudents'].isnull())]

,qualification,year,Subject,NumberOfCentres,gender,grade,NoOfStudents
124203,National5,2014,Accounting,NaN,all,Entries,777.0
124204,National5,2014,Accounting,NaN,male,Entries,350.0
124205,National5,2014,Accounting,NaN,female,Entries,427.0
124206,National5,2014,Accounting,NaN,all,A,381.0
124207,National5,2014,Accounting,NaN,all,B,148.0
...,...,...,...,...,...,...,...
155880,National5,2021,Urdu,NaN,all,A,52.0
155881,National5,2021,Urdu,NaN,all,A-B,64.0
155882,National5,2021,Urdu,NaN,all,A-C,66.0
155883,National5,2021,Urdu,NaN,all,A-D,66.0
155884,National5,2021,Urdu,NaN,all,NoAward,0.0

In [13]:
df3.loc[(df3['qualification'] == 'National5') & (df3['Subject'] == 'Urdu')]

,qualification,year,Subject,NumberOfCentres,gender,grade,NoOfStudents
124720,National5,2014,Urdu,NaN,all,Entries,42.0
124721,National5,2014,Urdu,NaN,male,Entries,17.0
124722,National5,2014,Urdu,NaN,female,Entries,25.0
124723,National5,2014,Urdu,NaN,all,A,34.0
124724,National5,2014,Urdu,NaN,all,B,3.0
124725,National5,2014,Urdu,NaN,all,C,5.0
124726,National5,2014,Urdu,NaN,all,D,0.0
124727,National5,2014,Urdu,NaN,male,A,12.0
124728,National5,2014,Urdu,NaN,female,A,22.0
124729,National5,2014,Urdu,NaN,male,Pass,17.0
124730,National5,2014,Urdu,NaN,female,Pass,25.0
129734,National5,2015,Urdu,NaN,all,Entries,49.0
129735,National5,2015,Urdu,NaN,male,Entries,18.0
129736,National5,2015,Urdu,NaN,female,Entries,31.0
129737,National5,2015,Urdu,NaN,all,A,37.0
129738,National5,2015,Urdu,NaN,all,B,3.0
129739,National5,2015,Urdu,NaN,all,C,4.0
129740,National5,2015,Urdu,NaN,all,D,1.0
129741,National5,2015,Urdu,NaN,male,A,11.0
129742,National5,2015,Urdu,NaN,female,A,26.0
129743,National5,2015,Urdu,NaN,male,Pass,15.0
129744,National5,2015,Urdu,NaN,female,Pass,29.0
133850,National5,2016,Urdu,NaN,all,Entries,62.0
133851,National5,2016,Urdu,NaN,male,Entries,26.0
133852,National5,2016,Urdu,NaN,female,Entries,36.0
133853,National5,2016,Urdu,NaN,all,A,45.0
133854,National5,2016,Urdu,NaN,all,B,6.0
133855,National5,2016,Urdu,NaN,all,C,6.0
133856,National5,2016,Urdu,NaN,all,D,3.0
133857,National5,2016,Urdu,NaN,male,A,20.0
133858,National5,2016,Urdu,NaN,female,A,25.0
133859,National5,2016,Urdu,NaN,male,Pass,24.0
133860,National5,2016,Urdu,NaN,female,Pass,33.0
137442,National5,2017,Urdu,NaN,all,Entries,74.0
137443,National5,2017,Urdu,NaN,male,Entries,33.0
137444,National5,2017,Urdu,NaN,female,Entries,41.0
137445,National5,2017,Urdu,NaN,all,A,50.0
137446,National5,2017,Urdu,NaN,all,B,11.0
137447,National5,2017,Urdu,NaN,all,C,7.0
137448,National5,2017,Urdu,NaN,all,D,3.0
137449,National5,2017,Urdu,NaN,male,A,21.0
137450,National5,2017,Urdu,NaN,female,A,29.0
137451,National5,2017,Urdu,NaN,male,Pass,29.0
137452,National5,2017,Urdu,NaN,female,Pass,39.0
141031,National5,2018,Urdu,NaN,all,Entries,45.0
141032,National5,2018,Urdu,NaN,male,Entries,21.0
141033,National5,2018,Urdu,NaN,female,Entries,24.0
141034,National5,2018,Urdu,NaN,all,A,35.0
141035,National5,2018,Urdu,NaN,all,B,5.0
141036,National5,2018,Urdu,NaN,all,C,5.0
141037,National5,2018,Urdu,NaN,all,D,0.0
141038,National5,2018,Urdu,NaN,male,A,16.0
141039,National5,2018,Urdu,NaN,female,A,19.0
141040,National5,2018,Urdu,NaN,male,Pass,21.0
141041,National5,2018,Urdu,NaN,female,Pass,24.0
145638,National5,2019,Urdu,NaN,all,Entries,74.0
145639,National5,2019,Urdu,NaN,male,Entries,25.0
145640,National5,2019,Urdu,NaN,female,Entries,49.0
145641,National5,2019,Urdu,NaN,all,A,64.0
145642,National5,2019,Urdu,NaN,all,B,8.0
145643,National5,2019,Urdu,NaN,all,C,1.0
145644,National5,2019,Urdu,NaN,all,D,1.0
145645,National5,2019,Urdu,NaN,male,A,21.0
145646,National5,2019,Urdu,NaN,female,A,43.0
145647,National5,2019,Urdu,NaN,male,Pass,25.0
145648,National5,2019,Urdu,NaN,female,Pass,48.0
150749,National5,2020,Urdu,NaN,male,Entries,36.0
150750,National5,2020,Urdu,NaN,male,A,34.0
150751,National5,2020,Urdu,NaN,male,A-B,35.0
150752,National5,2020,Urdu,NaN,male,A-C,36.0
150753,National5,2020,Urdu,NaN,male,A-D,36.0
150754,National5,2020,Urdu,NaN,male,NoAward,0.0
150755,National5,2020,Urdu,NaN,female,Entries,51.0
150756,National5,2020,Urdu,NaN,female,A,44.0
150757,National5,2020,Urdu,NaN,female,A-B,50.0
150758,National5,2020,Urdu,NaN,female,A-C,51.0
150759,National5,2020,Urdu,NaN,female,A-D,51.0
150760,National5,2020,Urdu,NaN,female,NoAward,0.0
150761,National5,2020,Urdu,NaN,all,Entries,87.0
150762,National5,2020,Urdu,NaN,all,A,67.0
150763,National5,2020,Urdu,NaN,all,A-B,82.0
150764,National5,2020,Urdu,NaN,all,A-C,85.0
150765,National5,2020,Urdu,NaN,all,A-D,86.0
150766,National5,2020,Urdu,NaN,all,NoAward,1.0
155867,National5,2021,Urdu,NaN,male,Entries,24.0
155868,National5,2021,Urdu,NaN,male,A,15.0
155869,National5,2021,Urdu,NaN,male,A-B,23.0
155870,National5,2021,Urdu,NaN,male,A-C,24.0
155871,National5,2021,Urdu,NaN,male,A-D,24.0
155872,National5,2021,Urdu,NaN,male,NoAward,0.0
155873,National5,2021,Urdu,NaN,female,Entries,42.0
155874,National5,2021,Urdu,NaN,female,A,37.0
155875,National5,2021,Urdu,NaN,female,A-B,41.0
155876,National5,2021,Urdu,NaN,female,A-C,42.0
155877,National5,2021,Urdu,NaN,female,A-D,42.0
155878,National5,2021,Urdu,NaN,female,NoAward,0.0
155879,National5,2021,Urdu,NaN,all,Entries,66.0
155880,National5,2021,Urdu,NaN,all,A,52.0
155881,National5,2021,Urdu,NaN,all,A-B,64.0
155882,National5,2021,Urdu,NaN,all,A-C,66.0
155883,National5,2021,Urdu,NaN,all,A-D,66.0
155884,National5,2021,Urdu,NaN,all,NoAward,0.0

In [14]:
df3.loc[(df3['year'] == '2017') & (df3['qualification'] == 'Higher')]

,qualification,year,Subject,NumberOfCentres,gender,grade,NoOfStudents
135843,Higher,2017,Accounting,NaN,all,Entries,1319.0
135844,Higher,2017,Accounting,NaN,male,Entries,725.0
135845,Higher,2017,Accounting,NaN,female,Entries,594.0
135846,Higher,2017,Accounting,NaN,male,A,276.0
135847,Higher,2017,Accounting,NaN,female,A,220.0
...,...,...,...,...,...,...,...
136344,Higher,2017,Urdu,NaN,female,A-C,68.0
136345,Higher,2017,Urdu,NaN,all,A,84.0
136346,Higher,2017,Urdu,NaN,all,B,11.0
136347,Higher,2017,Urdu,NaN,all,C,5.0
136348,Higher,2017,Urdu,NaN,all,D,3.0

#### Create a subset of sqa_data with qualifications from 2000 onwards

In [15]:
df_subset2000_21 = df3.loc[(df3['year'] == '2000') | (df3['year'] == '2001') | (df3['year'] == '2002') | (df3['year'] == '2003') | 
                           (df3['year'] == '2004') | (df3['year'] == '2005') | (df3['year'] == '2006') | (df3['year'] == '2007') | 
                          (df3['year'] == '2008') | (df3['year'] == '2009') | (df3['year'] == '2010') | (df3['year'] == '2011') | 
                          (df3['year'] == '2012') | (df3['year'] == '2013') | 
                           (df3['year'] == '2014') | (df3['year'] == '2015') | (df3['year'] == '2016') | (df3['year'] == '2017') | 
                          (df3['year'] == '2018') | (df3['year'] == '2019') | (df3['year'] == '2020') | (df3['year'] == '2021')]

In [19]:
df_subset_quali = df3.loc[(df3['qualification'] == 'Higher') | (df3['qualification'] == 'Intermediate1') |
                           (df3['qualification'] == 'Intermediate2') | (df3['qualification'] == 'NewHigher') |
                           (df3['qualification'] == 'AdvancedHigher') | (df3['qualification'] == 'National2') | 
                           (df3['qualification'] == 'National3')| (df3['qualification'] == 'National4') |
                           (df3['qualification'] == 'National5') | (df3['qualification'] == 'NationalCertificate') |
                           (df3['qualification'] == 'NationalProgressionAward')]

In [20]:
df_subset_quali.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 117932 entries, 500 to 159667
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   qualification    117932 non-null  object
 1   year             117932 non-null  object
 2   Subject          117932 non-null  object
 3   NumberOfCentres  78342 non-null   float64
 4   gender           117932 non-null  object
 5   grade            117932 non-null  object
 6   NoOfStudents     96274 non-null   float64
dtypes: float64(2), object(5)
memory usage: 7.2+ MB

In [22]:
df_subset2000_21['year'].unique()

array(['2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
       '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019', '2020', '2021'], dtype=object)

In [21]:
df_subset_quali['grade'].unique()

array(['Entries', 'A', 'B', 'C', 'Passes', 'D', 'percentage', 'Comp',
       'COMP', 'PassesesInUngradedCourses', 'PassesUngraded',
       'PassesUngradedCourses', 'A-C', 'Pass', 'Attainment', 'SCQF3',
       'SCQF4', 'SCQF5', 'SCQF6', 'SCQF2', '3', 'NoAward', 'A-B', 'A-D*',
       'A-D'], dtype=object)

In [37]:
df_subset_quali.loc[(df_subset_quali['qualification'] == 'Higher') & (df_subset_quali['Subject'] == 'Accounting') & (df_subset_quali['year'] == '2014') ]

,qualification,year,Subject,NumberOfCentres,gender,grade,NoOfStudents
121816,Higher,2014,Accounting,NaN,all,Entries,1277.0
121817,Higher,2014,Accounting,NaN,male,Entries,638.0
121818,Higher,2014,Accounting,NaN,female,Entries,638.0
121819,Higher,2014,Accounting,NaN,male,A,217.0
121820,Higher,2014,Accounting,NaN,female,A,211.0
121821,Higher,2014,Accounting,NaN,male,A-C,447.0
121822,Higher,2014,Accounting,NaN,female,A-C,447.0
121823,Higher,2014,Accounting,NaN,all,A,434.0
121824,Higher,2014,Accounting,NaN,all,B,255.0
121825,Higher,2014,Accounting,NaN,all,C,217.0
121826,Higher,2014,Accounting,NaN,all,D,77.0